### ISSUE TITLE
如何提高推理的性能

### ISSUE THREAD

**Issue by ianzangwill2** [LianjiaTech/BELLE#101]
你好，我使用 BELLE-LLAMA-7B-2M或者 BELLE-7B-2M的模型去推理，在4090显卡上，速度总是特别慢，需要约7分钟才能得到一个推理结果，而且和输入的token数似乎关系不大，即使是比较短的prompt，速度也很慢。请问下有没有什么参数可以调整，能够让推理性能变快的？ 谢谢！

目前就是默认参数：
device = torch.device('cuda')
model = LlamaForCausalLM.from_pretrained(ckpt, device_map='auto', low_cpu_mem_usage=True)
tokenizer = AutoTokenizer.from_pretrained(ckpt)
prompt = "Human: 写一首中文歌曲，赞美大自然 \n\nAssistant: "
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)
generate_ids = model.generate(input_ids, max_new_tokens=500, do_sample = True, top_k = 30, top_p = 0.85, temperature = 0.5, repetition_penalty=1., eos_token_id=2, bos_token_id=1, pad_token_id=0)
这样子

**Comment by 78** [comment]
vram可能不够，试试gptq的版本或者load_in_8bit=True

**Comment by bestpredicts** [comment]
7分钟包括模型加载时间嘛？

**Comment by ToSev7en** [comment]
我也遇到类似的情况，LLAMA-7B + LoRA 微调之后，在 A100（80G）上面推理好慢

**Comment by ianzangwill2** [comment]
7分钟包括模型加载时间嘛？ -- 不包括。 忘了说了，我是在 windows11上安装了 WSL2， WSL2 里使用ubuntu，再进行推理。
load_in_8bit=True  请问这个参数是在哪个函数里？ 谢谢

**Comment by 78** [comment]
加载后print(model.dtype)看看对不对

**Comment by ianzangwill2** [comment]
我测试了下，报错信息如下：

如果不使用  load_in_8bit=True，那么模型加载和推理速度很慢，要5-7分钟才能出结果。
      此时模型的dype显示为torch.float32  

如果使用了 load_in_8bit=True，报错信息如下：

      Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
      WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
      CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
      CUDA SETUP: CUDA path found: /usr/local/cuda/lib64/libcudart.so
      Exception: CUDA exception! Error code: no CUDA-capable device is detected

![image](https://user-images.githubusercontent.com/63735533/230766818-117b4492-8971-403b-be38-e3eae793e049.png)

**Comment by Tongjilibo** [comment]
有兴趣可以试试看复刻的版本，int8量化后大概是8g左右显存，单卡跑起来推理速度还行，[belle](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_belle.py)，同时复刻了chatglm和原版belle

**Comment by ianzangwill2** [comment]
我试了两次，但是好像占用内存比较多？ 在已经allocate 30GB内存的情况下好像还在读取，然后就被os强制杀死了。








                       
Original Email
                       
                     

Sender:"Bo仔很忙"< ***@***.*** &gt;;

Sent Time:2023/4/11 1:30

To:"LianjiaTech/BELLE"< ***@***.*** &gt;;

Cc recipient:"ianzangwill2"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [LianjiaTech/BELLE] 如何提高推理的性能 (Issue #101)




 
有兴趣可以试试看复刻的版本，int8量化后大概是8g左右显存，单卡跑起来推理速度还行，belle，同时复刻了chatglm和原版belle

**Comment by Tongjilibo** [comment]
我本机32g内存是没有问题，没出现这种情况，我看下

**Comment by Tongjilibo** [comment]
> 我试了两次，但是好像占用内存比较多？ 在已经allocate 30GB内存的情况下好像还在读取，然后就被os强制杀死了

我本机32g内存是没有问题，没出现这种情况，我看下是不是存在这样的问题~

**Comment by Tongjilibo** [comment]
> 你是用 windows+WSL，还是原生linux？ Original Email Sender:"Bo仔很忙"< ***@***.*** &gt;; Sent Time:2023/4/17 11:17 To:"LianjiaTech/BELLE"< ***@***.*** &gt;; Cc recipient:"ianzangwill2"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;; Subject:Re: [LianjiaTech/BELLE] 如何提高推理的性能 (Issue #101) 我试了两次，但是好像占用内存比较多？ 在已经allocate 30GB内存的情况下好像还在读取，然后就被os强制杀死了 我本机32g内存是没有问题，没出现这种情况，我看下是不是存在这样的问题~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我是直接在windows下面跑的

**Comment by ianzangwill2** [comment]
不好意思，最近比较忙，一直没回复。
windows下直接调用python的库吗？








                       
Original Email
                       
                     

Sender:"Bo仔很忙"< ***@***.*** &gt;;

Sent Time:2023/4/18 10:19

To:"LianjiaTech/BELLE"< ***@***.*** &gt;;

Cc recipient:"ianzangwill2"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [LianjiaTech/BELLE] 如何提高推理的性能 (Issue #101)




  
你是用 windows+WSL，还是原生linux？ Original Email Sender:"Bo仔很忙"< @.*** &gt;; Sent Time:2023/4/17 11:17 To:"LianjiaTech/BELLE"< @.*** &gt;; Cc recipient:"ianzangwill2"< @.*** &gt;;"Author"< @.*** &gt;; Subject:Re: [LianjiaTech/BELLE] 如何提高推理的性能 (Issue #101) 我试了两次，但是好像占用内存比较多？ 在已经allocate 30GB内存的情况下好像还在读取，然后就被os强制杀死了 我本机32g内存是没有问题，没出现这种情况，我看下是不是存在这样的问题~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我是直接在windows下面跑的

**Comment by Tongjilibo** [comment]
就是windows环境下直接跑的
