### ISSUE TITLE
ERROR: Could not consume arg: --model_config_file

### ISSUE THREAD

**Issue by bittteerr** [LianjiaTech/BELLE#102]
llama和bloom的lora在训练结束后都会报这个错误
ERROR: Could not consume arg: --model_config_file
但训练结果是保存下来了的。

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 1 (pid: 37835) of binary: /home/xxx/miniconda3/envs/llama/bin/python3.10
Traceback (most recent call last):
………………

File "/home/xxx/miniconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetune.py FAILED
------------------------------------------------------------

**Comment by xnliang98** [comment]
可以把启动的代码部分 234行     fire.Fire(train) 换成 train(args) 在51-52行补一个参数
`def train(
        args,
        train_on_inputs: bool = False,  # if False, masks out inputs in loss
        group_by_length: bool = True,  # faster, but produces an odd training loss curve,
        resume_from_checkpoint: str = None,  # either training checkpoint or final adapter
):`

**Comment by mabaochang** [comment]
辛苦提供下运行硬件信息、软件环境以及执行命令脚本，我们这边先复现一下问题

**Comment by M1n9X** [comment]
我这边也遇到了类似的问题， 不过提示的是local_rank，把fire换成普通的argparse解析就可以了

**Comment by xianghuisun** [comment]
> llama和bloom的lora在训练结束后都会报这个错误 ERROR: Could not consume arg: --model_config_file 但训练结果是保存下来了的。
> 
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 1 (pid: 37835) of binary: /home/xxx/miniconda3/envs/llama/bin/python3.10 Traceback (most recent call last): ………………
> 
> # File "/home/xxx/miniconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## finetune.py FAILED

很抱歉给您带来这个问题。报错的原因是python-fire库是一个自动生成命令行接口的工具库，但是model_config_file这个参数并不在finetune.py中作为函数的参数，所以fire不能识别该参数。
最简单的解决办法是换成普通的argparse，该问题已修复，可再次参考finetune.py。

**Comment by xianghuisun** [comment]
> 我也是换成普通的argparse解决的但是发现好像模型的梯度累积参数设置了之后失效了 跑起来就变成1了。

我这里输出gradient_accumulation_steps的具体值是正常的，您可以在日志中打印gradient_accumulation_steps参数值。
finetune.py中这个参数值的定义如下
gradient_accumulation_steps = model_config['batch_size'] // model_config['per_device_train_batch_size'] if "gradient_accumulation_steps" not in model_config else model_config['gradient_accumulation_steps']
所以只要在配置文件中指定了具体值，不应该存在失效的问题。

**Comment by xnliang98** [comment]
> > 我也是换成普通的argparse解决的但是发现好像模型的梯度累积参数设置了之后失效了 跑起来就变成1了。
> 
> 我这里输出gradient_accumulation_steps的具体值是正常的，您可以在日志中打印gradient_accumulation_steps参数值。 finetune.py中这个参数值的定义如下 gradient_accumulation_steps = model_config['batch_size'] // model_config['per_device_train_batch_size'] if "gradient_accumulation_steps" not in model_config else model_config['gradient_accumulation_steps'] 所以只要在配置文件中指定了具体值，不应该存在失效的问题。

ok多谢我再试一下
