### ISSUE TITLE
Asking to pad but the tokenizer does not have a padding token.

### ISSUE THREAD

**Issue by ToSev7en** [LianjiaTech/BELLE#103]
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token 
e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

**Comment by xianghuisun** [comment]
BloomTokenizer and LlamaTokenizer definitely have a padding token.
