### ISSUE TITLE
train目录下，按照步骤训练完成，但是文本生成报错。bloom和Llama都是一样的报错，提示缺少配置文件。

### ISSUE THREAD

**Issue by mellivoraPKU** [LianjiaTech/BELLE#113]
采用LoRA训练的启动命令(Llama模型):
torchrun --nproc_per_node=8 finetune.py --model_config_file run_config/Llama_config.json --lora_hyperparams_file run_config/lora_hyperparams_llama.json  --use_lora

训练完毕后
trained_models/Llama# 
adapter_config.json
adapter_model.bin  
special_tokens_map.json  
tokenizer_config.json  
tokenizer.model

文本生成
python generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path trained_models/Llama/
报错：
OSError: trained_models/Llama does not appear to have a file named config.json. Checkout 'https://huggingface.co/trained_models/Llama/None' for available files

**Comment by barryhippo** [comment]
我也遇到同样的错误

**Comment by barryhippo** [comment]
可能readme文件里面的脚本有点误导，
python generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path 『trained_models/Llama/』这里应该是原始模型位置
得加上--lora_weights 『trained_models/lora-llama』这个是lora训练生成的位置

这样就可以成功生成了

**Comment by mellivoraPKU** [comment]
> lora-llama

谢谢回复。不过为什么我的trained_models里没有lora-llama文件夹呢？

**Comment by xianghuisun** [comment]
> 采用LoRA训练的启动命令(Llama模型): torchrun --nproc_per_node=8 finetune.py --model_config_file run_config/Llama_config.json --lora_hyperparams_file run_config/lora_hyperparams_llama.json --use_lora
> 
> 训练完毕后 trained_models/Llama# adapter_config.json adapter_model.bin special_tokens_map.json tokenizer_config.json tokenizer.model
> 
> 文本生成 python generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path trained_models/Llama/ 报错： OSError: trained_models/Llama does not appear to have a file named config.json. Checkout 'https://huggingface.co/trained_models/Llama/None' for available files

如果非LoRA训练，trained_models/model_name下保存的模型是原始语言模型更新参数后的state_dict，可以直接加载。
如果是LoRA训练，trained_models/model_name下保存的模型是LoRA的参数，并不保存原始语言模型的参数。所以此时model_name_or_path对应的是原始语言模型的路径，要额外指定lora_weights，它对应的就是trained_models/model_name，也就是LoRA参数的保存位置

**Comment by LittleHann** [comment]
我也遇到了同样的情况，
采用LoRA训练的启动命令(bloom模型):
CUDA_VISIBLE_DEVICES=0 python3 finetune.py --model_config_file run_config/Bloom_config.json --lora_hyperparams_file run_config/lora_hyperparams_bloom.json  --use_lora

训练完毕后
trained_models/Llama#
adapter_config.json
adapter_model.bin
special_tokens_map.json
tokenizer_config.json
tokenizer.model
<img width="748" alt="image" src="https://user-images.githubusercontent.com/4005113/232942944-2c9b2ebe-8d51-4b5b-95e6-4c9e4cdfd13a.png">


文本生成
python3 generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path trained_models/bloom/ --lora_weights trained_models/bloom/
报错：
OSError: trained_models/bloom/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/trained_models/bloom//None' for available files.
