### ISSUE TITLE
运行“BELLE模型在COLAB推理的示例”报错，Couldn't instantiate the backend tokenizer from one of:

### ISSUE THREAD

**Issue by weixiongdi** [LianjiaTech/BELLE#118]
tokenizer = AutoTokenizer.from_pretrained("BelleGroup/BELLE-LLAMA-7B-2M-gptq")

error:ValueError: Couldn't instantiate the backend tokenizer from one of: 
(1) a `tokenizers` library serialization file, 
(2) a slow tokenizer instance to convert or 
(3) an equivalent slow tokenizer class to instantiate and convert. 
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.

!pip install sentencepiece didn't slove the issue
![image](https://user-images.githubusercontent.com/32905378/230333732-6f0e26c1-66e0-414a-bc67-85b1267dc195.png)

**Comment by bestpredicts** [comment]
已经解决了，我更新到github了。应该是transformers版本导致的问题。你直接基于github上面最新的colab点击进去运行，应该不会出现这个问题了。
