### ISSUE TITLE
BOS token位置

### ISSUE THREAD

**Issue by JaheimLee** [LianjiaTech/BELLE#119]
https://github.com/LianjiaTech/BELLE/blob/fb4ebc37ac12e1b69d06b6d546661214c48003ac/train/finetune.py#L123
这里应该改成`input_text + tokenizer.bos_token`吧

**Comment by xianghuisun** [comment]
这是bos_token，不是结束字符eos_token，要加在输入文本前面的。
实际上起始字符bos_token是可选的，不是必须要加在输入文本前的。
eos_token必须加在input_text后。

**Comment by JaheimLee** [comment]
input不是用户输入的内容吗，target才是模型需要输出的内容，所以要加在input后target前才对吧，我没感觉理解错啊😂

**Comment by xianghuisun** [comment]
> 这是bos_token，不是结束字符eos_token，既可以选择加在输入文本前面，也可以选择加在target前。 实际上起始字符bos_token是可选的，不是必须要加在输入文本前或者target前。而 eos_token必须加在target最后。

**Comment by xianghuisun** [comment]
嗯，您理解的没错。
bos_token加在input前或者target前都是可以的，不加也没问题。
eos_token必须加在target最后一个位置。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月6日(星期四) 晚上11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [LianjiaTech/BELLE] BOS token位置 (Issue #119)





 
input不是用户输入的内容吗，target才是模型需要输出的内容，所以要加在input后target前才对吧，我没感觉理解错啊😂
