### ISSUE TITLE
IndexError: index out of range in self  & cuda error:device-side assert triggered

### ISSUE THREAD

**Issue by XY2323819551** [LianjiaTech/BELLE#123]
您好，我训练完llama模型之后，再进行generate的时候出现了以下错误，我该怎么消除这个错误？
![image](https://user-images.githubusercontent.com/40745058/230522561-62070a10-7dbc-481c-bd75-33f6472bcc38.png)

我的运行命令是：`python generate.py --dev_file law_data/dev.json --model_name_or_path ./trained_models/Llama_single --output_file law_data/predictions4.json`

上述情况是在cpu上运行的时候。但是同样的设置和环境再GPU上运行时，就会出现另一个问题：`cuda error:device-side assert triggered`

**Comment by xianghuisun** [comment]
我建议您单独加载训练好的模型，然后输入一个text，看看model.generate(tokenizer(text))是否会报错

**Comment by XY2323819551** [comment]
> 我建议您单独加载训练好的模型，然后输入一个text，看看model.generate(tokenizer(text))是否会报错

我试了一下，单独加载，然后再输入数据不会报错。所以这个问题是由于llama和bloom的结构有差异导致的吗？因为之前用的是同样的训练代码，推理代码和推理数据。

**Comment by xianghuisun** [comment]
> 

这个问题我没有复现出来。看您的报错信息是index out of range，您可以检查下tokenize后的句子id，是否超出embedding_size

**Comment by XY2323819551** [comment]
> > 
> 
> 这个问题我没有复现出来。看您的报错信息是index out of range，您可以检查下tokenize后的句子id，是否超出embedding_size

好的，感谢！
