### ISSUE TITLE
训练模型的时候几个epoch比较好？

### ISSUE THREAD

**Issue by XY2323819551** [LianjiaTech/BELLE#124]
你好，我还有一个问题。我基于您发布的belle-7b-2m和llama-7b-2m进行模型训练，训练数据有6000条，训练时"cutoff_len"设置为768，epoch设置为4，我在8卡40G的A100上训练，训练到70%左右的时候突然出现了cuda out of memory的问题。所以想问一下，训练进度到70%左右的时候应该在第三个epoch，为什么前面两个epoch都没有出现这个问题，这里突然出现了呢？

**Comment by xianghuisun** [comment]
您使用的是train/finetune.py嘛。
这个显然和设置几个epoch没有关系。

**Comment by XY2323819551** [comment]
对的，使用的命令是`deepspeed --num_gpus=8 finetune.py --model_config_file run_config/Bloom_config_single.json --deepspeed run_config/deepspeed_config.json`，配置文件中除了epoch、cutoff_len、model_name_or_path（我用的是BELLE-7B-2M）和数据不一样，其他都一样的。

**Comment by xianghuisun** [comment]
> 对的，使用的命令是`deepspeed --num_gpus=8 finetune.py --model_config_file run_config/Bloom_config_single.json --deepspeed run_config/deepspeed_config.json`，配置文件中除了epoch、cutoff_len、model_name_or_path（我用的是BELLE-7B-2M）和数据不一样，其他都一样的。

您好，有可能是在保存模型时出现显存不足，和epoch应该没有关系。
另外我们训练时"cutoff_len"设置为512

**Comment by XY2323819551** [comment]
> > 对的，使用的命令是`deepspeed --num_gpus=8 finetune.py --model_config_file run_config/Bloom_config_single.json --deepspeed run_config/deepspeed_config.json`，配置文件中除了epoch、cutoff_len、model_name_or_path（我用的是BELLE-7B-2M）和数据不一样，其他都一样的。
> 
> 您好，有可能是在保存模型时出现显存不足，和epoch应该没有关系。 另外我们训练时"cutoff_len"设置为512

好的，感谢
