### ISSUE TITLE
colab代码最后一步异常

### ISSUE THREAD

**Issue by lemonxiao0** [LianjiaTech/BELLE#128]
是哪个步骤我用错了？
提示quant cuda不存在

**Comment by bestpredicts** [comment]
有尝试过 restart-runall 重新运行嘛？

**Comment by bestpredicts** [comment]
colab如果中间多次运行加载模型的模块 在没有restart的情况下会存在问题。这个问题应该主要是colab导致的。

**Comment by hejinguang** [comment]
遇到同样的问题，restart过多次还是一样的报错

**Comment by TianZC-zju** [comment]
遇到同样的问题

**Comment by kzoacn** [comment]
`test_kernel.py` 中`import quant_cuda` 没有问题而最后一行却报错 `quant_cuda not found`，似乎说明quant_cuda无法进入colab的runtime但可以以命令行运行，把colab代码中最后几行整理到一个python文件中，比如`infer.py`,再 `!python infer.py` 可以调用，但问题是每次都要加载一次模型

**Comment by bestpredicts** [comment]
感谢各位的意见，问题已经解决，等明天代码merge以后即可。
