### ISSUE TITLE
why "tokenizer.padding_side = "left"" which is set as "right" in alpaca

### ISSUE THREAD

**Issue by deeplearningSprint** [LianjiaTech/BELLE#130]

**Comment by xianghuisun** [comment]
Both left and right are actually possible, it will not affect the result.

**Comment by akk-123** [comment]
@xianghuisun I think padding_side may affect result, model input = inputs_embeds + position_embeds, if set left padding, eg `[pad_1, pad_2, ..., text_1, text_2]`，this will cause the position index of text different, then the position_embeds and model input is different
