### ISSUE TITLE
使用lora微调后的模型进行生成时，报错Can't find config.json at trained_models/llama/checkpoint-***

### ISSUE THREAD

**Issue by EnghishYang** [LianjiaTech/BELLE#131]
如题，在使用代码lora微调模型后，checkpoint中存的应该是lora的weight，但是在生成时，--model_name_or_path设置的是原始模型路径，--lora_weights设置的是存在checkpoint的lora权重，但是在Peft加载的时候报错Can't find config.json at trained_models/llama/checkpoint-***  请问下是什么问题呢？

**Comment by xianghuisun** [comment]
我觉得这很可能还是因为model_name_or_path下，也就是原始模型路径下没有config.json文件
lora权重保存的内容如下，是没有config.json的
![image](https://user-images.githubusercontent.com/89245998/230747674-b7c8d027-fa31-4d28-bea0-b4e403c20d90.png)

**Comment by xianghuisun** [comment]
> 如题，在使用代码lora微调模型后，checkpoint中存的应该是lora的weight，但是在生成时，--model_name_or_path设置的是原始模型路径，--lora_weights设置的是存在checkpoint的lora权重，但是在Peft加载的时候报错Can't find config.json at trained_models/llama/checkpoint-*** 请问下是什么问题呢？

确保model_name_or_path路径下的文件是原始模型的权重（包括tokenizer,config.json等），如果还是报错，您可以把报错的信息截图给我看看。

**Comment by EnghishYang** [comment]
> > 如题，在使用代码lora微调模型后，checkpoint中存的应该是lora的weight，但是在生成时，--model_name_or_path设置的是原始模型路径，--lora_weights设置的是存在checkpoint的lora权重，但是在Peft加载的时候报错Can't find config.json at trained_models/llama/checkpoint-*** 请问下是什么问题呢？
> 
> 确保model_name_or_path路径下的文件是原始模型的权重（包括tokenizer,config.json等），如果还是报错，您可以把报错的信息截图给我看看。

原始模型文件中是包含tokenizer和config.json的，因为训练的时候没有出任何问题。如下图是lora训练完后的文件：
![image](https://user-images.githubusercontent.com/53075122/230752078-6d1c9565-629c-4e6e-a5c8-d4d766ddd206.png)
报错如下：
![image](https://user-images.githubusercontent.com/53075122/230752188-e8ee898f-37dc-42aa-99c4-7e74c521fce0.png)

**Comment by xianghuisun** [comment]
这有可能是peft版本的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月9日(周日) 中午11:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [LianjiaTech/BELLE] 使用lora微调后的模型进行生成时，报错Can't find config.json at trained_models/llama/checkpoint-*** (Issue #131)




   
如题，在使用代码lora微调模型后，checkpoint中存的应该是lora的weight，但是在生成时，--model_name_or_path设置的是原始模型路径，--lora_weights设置的是存在checkpoint的lora权重，但是在Peft加载的时候报错Can't find config.json at trained_models/llama/checkpoint-*** 请问下是什么问题呢？
  
确保model_name_or_path路径下的文件是原始模型的权重（包括tokenizer,config.json等），如果还是报错，您可以把报错的信息截图给我看看。
  
原始模型文件中是包含tokenizer和config.json的，因为训练的时候没有出任何问题。如下图是lora训练完后的文件：
 
 报错如下：

**Comment by EnHuiPug** [comment]
@EnghishYang 请问解决了么

**Comment by EnghishYang** [comment]
> Referenc

没有，重装了下peft，还是这样。

**Comment by EnHuiPug** [comment]
试试这个
--lora_weights  train/trained_models/llama/checkpoint-*****
把这个路径名加一层

**Comment by EnghishYang** [comment]
> 试试这个 --lora_weights train/trained_models/llama/checkpoint-***** 把这个路径名加一层

目前设置的是 --lora_weights train/trained_models/llama/checkpoint-***** 这样报的错，您说的在家一层是指到哪个呢

**Comment by EnghishYang** [comment]
> 之前设置的不是 --lora_weights trained_models/llama/checkpoint-***** 么

是这样的

**Comment by EnghishYang** [comment]
> 之前设置的不是 --lora_weights trained_models/llama/checkpoint-***** 么 我改成train/trained_models/llama/checkpoint-***** 就可以了

意思是把模型放到trian/下了吗？  我还是存在问题~

**Comment by EnHuiPug** [comment]
不是，不用改文件位置，就是把原本的`trained_models/llama/checkpoint-***** `这个路径名称加上当前文件夹的名称，变为你的`BELLE-main/trained_models/llama/checkpoint-***** `。
具体要看你在哪个目录下运行的，简单来说，使用相对地址的时候，不能使用`./trained_models`，必须使用`XXXX/trained_models`

**Comment by EnghishYang** [comment]
> 

我写的绝对位置  应该没有这个问题吧 您这边刚开始也是报这个错，然后通过您说的方式解决了吗？

**Comment by EnghishYang** [comment]
> 不是，不用改文件位置，就是把原本的`trained_models/llama/checkpoint-***** `这个路径名称加上当前文件夹的名称，变为你的`BELLE-main/trained_models/llama/checkpoint-***** `。 具体要看你在哪个目录下运行的，简单来说，使用相对地址的时候，不能使用`./trained_models`，必须使用`XXXX/trained_models`

我写的绝对位置 应该没有这个问题吧 您这边刚开始也是报这个错，然后通过您说的方式解决了吗？

**Comment by EnHuiPug** [comment]
我用绝对位置也报错了，改相对的才好的

**Comment by EnHuiPug** [comment]
解决了

**Comment by EnghishYang** [comment]
> 解决了

好的 我去试试  感谢感谢

**Comment by Tian14267** [comment]
@EnHuiPug @EnghishYang 
两位好，我想问下，我使用下面这个进行生成，可是还是报错：`weight is on the meta device, we need a `value` to put in on 0.`
我的代码是：
```
python generate.py \
            --dev_file data_dir/Belle_open_source_0.5M.dev.json \
            --model_name_or_path BELLE-main/train/trained_models/bloom/checkpoint-1000 \
            --lora_weights train/trained_models/bloom/checkpoint-1000
```
请问这是啥情况啊

**Comment by EnHuiPug** [comment]
@Tian14267  `--model_name_or_path train/trained_models/bloom/checkpoint-1000 ` 这里是错的，`--model_name_or_path` 这个参数后面要接原本的模型地址，要么是`bigscience/bloomz-7b1-mt`，要么是你下到本地后的模型地址

**Comment by LittleHann** [comment]
> @Tian14267 `--model_name_or_path train/trained_models/bloom/checkpoint-1000 ` 这里是错的，`--model_name_or_path` 这个参数后面要接原本的模型地址，要么是`bigscience/bloomz-7b1-mt`，要么是你下到本地后的模型地址

你好，感谢回复。
我用lora训练bloom后得到的目录文件如下:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/4005113/232986431-b12f367e-b15e-4c8c-9adc-1bc809729302.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/4005113/232986470-d0ef1a7c-6401-4b05-8800-05d61fbe3768.png">
然后我运行如下指令:
python3 generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path trained_models/bloom/checkpoint-11000 --lora_weights trained_models/bloom/checkpoint-11000

依然报如下错误:
OSError: trained_models/bloom/checkpoint-11000 does not appear to have a file named config.json. Checkout 'https://huggingface.co/trained_models/bloom/checkpoint-11000/None' for available files.

**Comment by EnHuiPug** [comment]
@LittleHann `--model_name_or_path` 这个参数后面接 bigscience/bloomz-7b1-mt

**Comment by LittleHann** [comment]
> @LittleHann `--model_name_or_path` 这个参数后面接 bigscience/bloomz-7b1-mt

你好，我修改了指令为：
python3 generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path decapoda-research/llama-7b-hf --lora_weights ./trained_models/Llama/  

遇到了新的报错：
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/opencv/lib')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.8/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 118
/usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
Traceback (most recent call last):
  File "generate.py", line 135, in <module>
    tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 699, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.


我猜测是因为没有明确指定本地的模型路径，所以导致找不到tokenize文件
我的llama模型文件如下：
<img width="742" alt="image" src="https://user-images.githubusercontent.com/4005113/233284257-068eb446-86b8-4db9-be3a-5ebd3be28317.png">

**Comment by muziyongshixin** [comment]
> 不是，不用改文件位置，就是把原本的`trained_models/llama/checkpoint-***** `这个路径名称加上当前文件夹的名称，变为你的`BELLE-main/trained_models/llama/checkpoint-***** `。 具体要看你在哪个目录下运行的，简单来说，使用相对地址的时候，不能使用`./trained_models`，必须使用`XXXX/trained_models`

我使用绝对路径的时候也遇到了这样的问题，请问怎么解决呀？
命令如下：python3 generate.py --dev_file=/mnt/bn/vgraph/biz_llm/biz_llm/stanford_alpaca/products_ad_prompts_benchmark.json --model_name_or_path=/mnt/bn/vgraph/biz_llm/biz_llm/pretrained_weights/models--decapoda-research--llama-30b-hf/snapshots/f991780f9362b2fcaefad066cd235058844562b7 --lora_weights=/mnt/bn/vgraph/biz_llm/biz_llm/arnold_output/Llama/30b_origin+sft_4M_bs16/checkpoint-32000/

我看lora_weights下面确实没有config.json 但是model_name_or_path这个路径下是有config.json的，是不能使用绝对路径吗？

**Comment by EnHuiPug** [comment]
> > 不是，不用改文件位置，就是把原本的`trained_models/llama/checkpoint-***** `这个路径名称加上当前文件夹的名称，变为你的`BELLE-main/trained_models/llama/checkpoint-***** `。 具体要看你在哪个目录下运行的，简单来说，使用相对地址的时候，不能使用`./trained_models`，必须使用`XXXX/trained_models`
> 
> 我使用绝对路径的时候也遇到了这样的问题，请问怎么解决呀？ 命令如下：python3 generate.py --dev_file=/mnt/bn/vgraph/biz_llm/biz_llm/stanford_alpaca/products_ad_prompts_benchmark.json --model_name_or_path=/mnt/bn/vgraph/biz_llm/biz_llm/pretrained_weights/models--decapoda-research--llama-30b-hf/snapshots/f991780f9362b2fcaefad066cd235058844562b7 --lora_weights=/mnt/bn/vgraph/biz_llm/biz_llm/arnold_output/Llama/30b_origin+sft_4M_bs16/checkpoint-32000/
> 
> 我看lora_weights下面确实没有config.json 但是model_name_or_path这个路径下是有config.json的，是不能使用绝对路径吗？

是的，不能使用绝对路径，要使用相对路径，且不能用./XXXX，要把当前的模样也加上 <cur_dir>/XXX

**Comment by EnHuiPug** [comment]
@LittleHann `--model_name_or_path` 这个参数后面接你本地的原模型的地址应该就可以了，包含config，权重等文件的那个目录

**Comment by hingkan** [comment]
为了避免这个问题，可以使用绝对路径。

**Comment by datalee** [comment]
扯犊子，肯定是文件路径的问题，没找到文件.json命名为啥不重要、0.2版本是写死的文件名
![image](https://github.com/LianjiaTech/BELLE/assets/13651873/30a7a85a-1ee1-4076-a592-eacab1ed106f)
