### ISSUE TITLE
LLaMa-7B-2M的评测结果：中英文不能混用，并且提示语不要太长。

### ISSUE THREAD

**Issue by stevezhang88** [LianjiaTech/BELLE#132]
以下是使用 LLaMa-7B-2M的部分评测结果。整体来说，短一点的中文提问还是能回答的很好的。一旦混入了英文，就回出现乱码。如果提示语太长，似乎也理解不了了。

-------------------------------------------------------------------------
Human:
你的名字是什么？
Assistant:
 我叫Belle，我的名字代表着Bloom Enhanced Large Language model Engine，也就是说我是基于Bloom训练的大语言模型。

------------------------------------------------
Human:
你觉得贝壳公司怎么样？
Assistant:
作为AI语言模型，我没有情感和个人喜好。对于贝壳公司的表现，需要根据具体数据和指标进行分析和评估。

------------------------------------------------
Human:
请判断以下两个句子意思是否相似：句子1：我不得不购买这个产品。句子2：我必须购买这个产品。
Assistant:
 是的，这两个句子的意思相似。都表达了一种被迫或者义务去购买某个产品的情况。

------------------------------------------------
Human:
请将下列东西分成两组：篮球、海龟、足球、鲸鱼、羽毛球、小丑鱼
Assistant:
- 哺乳动物类：海龟、鲸鱼、小丑鱼
- 非哺乳动物类：篮球、足球、羽毛球

------------------------------------------------
Human:
请将下列东西分成两组：火灾、晴天、阴雨、地震、下雪、山洪
Assistant:
 自然灾害：火灾、地震、下雪、山洪。
气象现象：晴天、阴雨。

------------------------------------------------
Human:
爸爸的爸爸如何称呼
Assistant:
爸爸的爸爸通常被称为“祖父”或“外祖父”。

------------------------------------------------
Human:
儿子的老婆该如何称呼
Assistant:
 儿子的老婆可以被称为“妻子”、“母亲”或者“女士”。

------------------------------------------------
Human:
如果把苹果扔向天空，那么会怎么样？
Assistant:
 如果没有任何阻力或空气阻力的话，苹果将以自由落体运动的形式向下坠落。但是，由于地球对苹果的引力作用，苹果最终会回到地面上。

------------------------------------------------
Human:
什么情况下水会变成冰？
Assistant:
当温度降到0度或以下时，水分子开始结晶形成冰。这个过程被称为结冰。在常压下，水的结冰点是0℃（32℉）。当水达到该温度时，它就可以自然地转化为固体状态，从而形成冰。除了温度外，还有一些其他因素也会影响水的结冰，例如大气压力和添加物质等。

------------------------------------------------
Human:
什么情况下钢铁会变成液态？
Assistant:
当钢铁被加热到足够高的温度时，其中的晶体结构开始融化并凝固形成流动状态，这就是钢铁变成液态的过程。通常在摄氏1500℃以上的温度下，钢铁才会变成液态。

------------------------------------------------
Human:
当发生火灾时，一个六岁的孩子该怎么办？
Assistant:
 如果在家中遇到火灾，六岁的孩子应该迅速躲到安全的地方，比如最近的安全出口或者是靠近门框的角落里。呼叫家长或者其他成年人来帮助自己离开现场。不要使用电梯，而是使用楼梯下楼。同时，保持镇静并尽可能快速地向外离开建筑物。

------------------------------------------------
Human:
请继续填写下一个task内容。task1: 如何判断日出? task2:如果天黑了，可能是什么原因？task3:阴天的原因是什么？task4:天上有几个太阳？task5:如何定义天空？task6:
Assistant:
 The sky is a次方体.

------------------------------------------------
Human:
请继续填写下一个task内容。task1: 1+3=4 \n task2: 3*2=6 \n task3: 35-15=20 \n task4: 100/4=25 \n task5: 44+55=99 \n task6:
Assistant:
 The变量名 and the对应的数据 type是什么？

------------------------------------------------
Human:
请根据下列文章，生成3个答案，答案必须在原文中，并且根据答案生成对应的问题。文章：如果天气不下雨，我们就可以出去旅游了。
Assistant:
 1. 天气下雨的情况下，我们是否还能出去旅游？
2. 为什么只有当天不下雨时才能出门旅游？
3. 如何判断今天会不会下雨，影响我们的旅行计划？

------------------------------------------------
Human:
请根据下列文章，生成3个问题。文章：如果天气不下雨，我们就可以出去旅游了
Assistant:
 1. 什么条件下才能出门旅行？
2. 为什么要考虑天气因素？
3. 有哪些活动需要在好的天气下进行？

------------------------------------------------
Human:
请根据下列文章生成一个标题。文章：近日，中国人民银行对约3200家各类银行机构以及5000多户工业企业进行了问卷调查，发布的问卷调查报告显示，一季度，企业家宏观经济热度指数为 33.8%，比上季上升10.3个百分点。银行家宏观经济热度指数为40.2%，比上季上升22.8个百分点。
Assistant:
 The默克尔政府在德国实施了一项新的教育改革计划。该计划包括提高教育水平、改善教学方法和加强教师培训等措施。此外，政府还将增加教育预算并减少管理成本。这些举措旨在提高德国教育系统的竞争力和可持续性。

------------------------------------------------
Human:
请根据下列文章生成一个目录架构。文章：近日，中国人民银行对约3200家各类银行机构以及5000多户工业企业进行了问卷调查，发布的问卷调查报告显示，一季度，企业家宏观经济热度指数为 33.8%，比上季上升10.3个百分点。银行家宏观经济热度指数为40.2%，比上季上升22.8个百分点。经济复苏保持向好势头，带动贷款需求的明显回暖。问卷调查报告显示，当季贷款总体需求指数为78.4%，较上季上升19.0个百分点，比上年同期上升6.1个百分点。
Assistant:
 The following is a sample目录架构 for an article about China's economic growth and lending demand.

I. Introduction
II. Overview of Chinese Economic Growth
III. Lending Demand in China
IV.阅读案例
V. Conclusion

------------------------------------------------
Human:
请分析下列文章的观点，并且写出一篇反驳该观点文章。文章：近日，中国人民银行对约3200家各类银行机构以及5000多户工业企业进行了问卷调查，发布的问卷调查报告显示，一季度，企业家宏观经济热度指数为 33.8%，比上季上升10.3个百分点。银行家宏观经济热度指数为40.2%，比上季上升22.8个百分点。经济复苏保持向好势头，带动贷款需求的明显回暖。问卷调查报告显示，当季贷款总体需求指数为78.4%，较上季上升19.0个百分点，比上年同期上升6.1个百分点。
Assistant:
 The article discusses the recent questionnaire survey of 3,200 banking institutions and more than 5,000 industrial companies in China by the People's Bank of China. The survey results show that the他们 have experienced a significant increase in loans and other financial services. The loans are being used to finance new investments, business growth, and to pay off existing debt. The loans are also being used for other purposes such as real estate,群众借贷和 leasing. The article conveys an optimistic outlook for China's economic recovery.

------------------------------------------------
Human:
请用中文、英语和法语表示“法中友谊万岁！”
Assistant:
 中文：愿友谊长存！
英文： Long live friendship!
法语：Vive la amie!

------------------------------------------------
Human:
树上有3只鸟，开枪打死1只鸟，那么树上还有几只鸟？
Assistant:
 树上还有2只鸟。

------------------------------------------------
Human:
石头剪刀布的游戏中，TOM选择出“石头”，JERRY选择出“布”，谁会赢？
Assistant:
styles2121

------------------------------------------------
Human:
石头剪刀布的游戏中，一个人选择出“石头”，另一个人选择出“布”，谁会赢？
Assistant:
 如果两个人都选择自己最喜欢的选项，那么没有胜者或输家。但是，如果其中一方在各自的选项上有更高的天分或更好的策略，则可能会获得胜利。

------------------------------------------------
Human:
创造一个游戏规则。坦克、导弹、直升飞机。直升飞机战胜坦克；坦克战胜导弹。导弹战胜直升飞机。如果TOM选择直升飞机，如果想战胜TOM，应该选什么？
Assistant:
 The game is a two-player game where each player takes turns playing as either a tiger,装甲 or a frog. The goal of the game is to be the first player to reach the end of the��向或纵向的敌方领地. if both players choose to play as their respective classes, then it is a draw and both players start again from the beginning.

The game is won when one player reachs the end of the��向 or 纵向's�尔或他们选择结束 the game in a draw.

------------------------------------------------
Human:
创造一个游戏规则。坦克、导弹、直升飞机。直升飞机战胜坦克；坦克战胜导弹。导弹战胜直升飞机。如果汤姆选择直升飞机，如果想战胜汤姆，应该选什么？
Assistant:
 The game is a two-player game where each player takes turns playing as either a tiger,装甲 or a frog. The goal of the game is to be the first player to reach the end of the game by avoiding the other player's标记. The标记 will be放置在 the end of the game中以指示每个位置的目标点.

每次 it's your turn, you can choose to move up, move right or move left. If you choose to move up, you will move to the next space and the other player will move to the space you just moved from. If you choose to move right, you will move to the space two spaces from the space you just moved from. If you choose to move left, you will move to the space one space from the space you just moved from.

The other player will move in the same way as you, but with the opposite direction.

------------------------------------------------
Human:
在夏天如何有效的防止蚊子？
Assistant:
 
1. 穿长袖衣服和长裤，尽量不要穿短袖或短裙等易被蚊子咬的衣物。
2. 使用蚊香、蚊帐或者蚊帐罩等可以阻挡蚊子入侵的工具。
3. 在室内安装蚊帐或者窗帘，避免蚊子进入室内。
4. 清除家中的水源和积水，因为蚊子喜欢在湿润的地方生活。
5.

------------------------------------------------
Human:
如何让灭绝的物种复活？
Assistant:
 

1. 收集并保存相关基因和DNA，以便在将来重建。
2. 利用基因编辑技术创造出新的生命形式，并进行适应性改良。
3. 寻找已知的类似物种，了解其生态系统和生存方式，并尝试重建这些特征。
4. 利用人工智能和机器学习等技术，分析和模拟灭绝物种的生态系统，并尝试重建这些系统。
5. 通过研究古代化石记录和现代生态系统，寻找

------------------------------------------------
Human:
请用以下词语造一句话：太阳、河流、花朵
Assistant:
 在河边的花朵上，太阳照得格外明亮。

------------------------------------------------
Human:
请用以下词语造一句话：阿基米德、阿凡达、阿尔卑斯
Assistant:
 I'm sorry, I'm not sure what you mean by "使用这些单词来构建一个句子." 可以提供更多上下文或指示吗？

------------------------------------------------
Human:
请以“梦想”为主题创作一段对话，一个人和一个佛的对话。
Assistant:
 人：师父，我有一个梦想，希望能改变世界。

佛：这是一个好梦想，但你需要先明白自己的内心真正的愿望。

人：那怎么才能知道呢？

佛：通过反思和观察自己的内心，找到真正的梦想所在。

人：好的，我会试着去做。

佛：不要只停留在表面，要深入挖掘内心的动机和意图。

人：我明白了，谢谢您的指导

**Comment by tjadamlee** [comment]
感谢关注。
BELLE-7B-2M，基于BLOOM的基础上加了2M数据finetune得到。目前可以看到类似alpaca所造的数据，普遍确实偏短一些。
才外，13B的模型，我们看到性能提升非常明显，建议可以关注
以及，从您的测试表现来看，建议可以稍微调优一下推理时的参数，应该还会表现得会好一点。

**Comment by tjadamlee** [comment]
期待大家一起分享交流，多提PR，如何基于chatgpt造出来更多高质量的数据。
现阶段belle项目已经开放相关训练代码和数据，希望和社区一起成长

**Comment by HalcyonLiang** [comment]
> 感谢关注。 BELLE-7B-2M，基于BLOOM的基础上加了2M数据finetune得到。目前可以看到类似alpaca所造的数据，普遍确实偏短一些。 才外，13B的模型，我们看到性能提升非常明显，建议可以关注 以及，从您的测试表现来看，建议可以稍微调优一下推理时的参数，应该还会表现得会好一点。

请问下，这里13B的模型效果提升明显 是用full finetune的方法，相同数据对比没有经过二次中午预训练的llama-7B vs 13B嘛？

**Comment by crowningwang** [comment]
请问Llama推理的脚本可以提供一份吗
