### ISSUE TITLE
报错：NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3 ncclSystemError: System call (socket, malloc, munmap, etc) failed.

### ISSUE THREAD

**Issue by zhangzai666** [LianjiaTech/BELLE#136]
报错：
NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3 ncclSystemError: System call (socket, malloc, munmap, etc) failed.
似乎是多卡训练NCCL通信的问题，哪位大神解答一下，十分感谢

**Comment by xianghuisun** [comment]
> 报错： NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3 ncclSystemError: System call (socket, malloc, munmap, etc) failed. 似乎是多卡训练NCCL通信的问题，哪位大神解答一下，十分感谢

您这是运行的哪个代码？

**Comment by zhangzai666** [comment]
> > 报错： NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3 ncclSystemError: System call (socket, malloc, munmap, etc) failed. 似乎是多卡训练NCCL通信的问题，哪位大神解答一下，十分感谢
> 
> 您这是运行的哪个代码？

感谢您的回答。
是非lora方式finetuning llama-7B的代码。我是在docker 中训练的，然后报了这个错误。看网上资料启动docker 时加了一个参数--ipc=host 。然后这个错误没有了，就直接报了显存不足的错误

**Comment by xianghuisun** [comment]
> > > 报错： NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3 ncclSystemError: System call (socket, malloc, munmap, etc) failed. 似乎是多卡训练NCCL通信的问题，哪位大神解答一下，十分感谢
> > 
> > 
> > 您这是运行的哪个代码？
> 
> 感谢您的回答。 是非lora方式finetuning llama-7B的代码。我是在docker 中训练的，然后报了这个错误。看网上资料启动docker 时加了一个参数--ipc=host 。然后这个错误没有了，就直接报了显存不足的错误


如果要训练7B的模型，建议最好是80G的A100。LlamaTokenizer后的句子长度普遍是比较长的，我们是设置在1024左右

**Comment by zhangzai666** [comment]
> > > > 报错： NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3 ncclSystemError: System call (socket, malloc, munmap, etc) failed. 似乎是多卡训练NCCL通信的问题，哪位大神解答一下，十分感谢
> > > 
> > > 
> > > 您这是运行的哪个代码？
> > 
> > 
> > 感谢您的回答。 是非lora方式finetuning llama-7B的代码。我是在docker 中训练的，然后报了这个错误。看网上资料启动docker 时加了一个参数--ipc=host 。然后这个错误没有了，就直接报了显存不足的错误
> 
> 如果要训练7B的模型，建议最好是80G的A100。LlamaTokenizer后的句子长度普遍是比较长的，我们是设置在1024左右

您好，请问您是用了几张A100  80G的卡呢，我这边是有4张40G的A100
