### ISSUE TITLE
测试了一下，感觉模型的常识还不够

### ISSUE THREAD

**Issue by Degfy** [LianjiaTech/BELLE#14]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/15191087/226837928-a60f0fe1-468d-4699-b68e-c70f1eb31f71.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/15191087/226837977-62677042-1416-4203-885b-b261849e4dc3.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/15191087/226838146-d0bee0f1-1e58-48d7-8c98-60e554735862.png">

**Comment by tjadamlee** [comment]
模型的常识很大程度还是需要依赖预训练阶段，BELLE基于BLOOM，且目前重点关注instruct阶段如何激发指令理解能力。我们也在探讨如何加强知识注入，将来有机会也会开源相关进展。

**Comment by Degfy** [comment]
> 常识很大程度还是需要依赖预训练阶段

我这里是用的 NVIDIA V100

**Comment by TestNLP** [comment]
模型进一步训练的化，需要多少卡？8张A100  42G显存够不够？

**Comment by ddzz0210** [comment]
大佬，怎么跑起来的呀，运行哪个文件呢
