### ISSUE TITLE
无法运行微调代码 launch.py sigkill_handler

### ISSUE THREAD

**Issue by lemuria-wchen** [LianjiaTech/BELLE#140]
8卡A800，一直报 launch.py sigkill_handler

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/44920140/230799183-88c374ad-29d7-49bb-9b5c-b10a335143ba.png">

运行 `python -u finetune.py --local_rank=0 --model_config_file run_config/Bloom_config.json --deepspeed run_config/deepspeed_config.json`

报错为
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/44920140/230799233-9d50f90f-161f-4668-b007-6d73d0a60711.png">

**Comment by lemuria-wchen** [comment]
Deepspeed 信息
<img width="924" alt="image" src="https://user-images.githubusercontent.com/44920140/230799272-c6fce695-5514-4ec3-b5c6-7c17231311dd.png">

**Comment by lemuria-wchen** [comment]
版本依赖完全按照仓库的来安装，这个错误怎么解决呀，拜托帮忙看看🙏

**Comment by xianghuisun** [comment]
> 8卡A800，一直报 launch.py sigkill_handler
> 
> <img alt="image" width="1429" src="https://user-images.githubusercontent.com/44920140/230799183-88c374ad-29d7-49bb-9b5c-b10a335143ba.png">
> 
> 运行 `python -u finetune.py --local_rank=0 --model_config_file run_config/Bloom_config.json --deepspeed run_config/deepspeed_config.json`
> 
> 报错为 <img alt="image" width="1436" src="https://user-images.githubusercontent.com/44920140/230799233-9d50f90f-161f-4668-b007-6d73d0a60711.png">

Failed at address这个错误我们这边很难复现出来，应该和您机器本身的环境有关

**Comment by lemuria-wchen** [comment]
我这边只要用deepspeed就会报这个sigkill_handler错，请问你们安装deepspeed就是简单地用 pip install deepspeed吗？
关于deepspeed的安装可以再详细说明一下吗？

**Comment by lemuria-wchen** [comment]
> > 8卡A800，一直报 launch.py sigkill_handler
> > <img alt="image" width="1429" src="https://user-images.githubusercontent.com/44920140/230799183-88c374ad-29d7-49bb-9b5c-b10a335143ba.png">
> > 运行 `python -u finetune.py --local_rank=0 --model_config_file run_config/Bloom_config.json --deepspeed run_config/deepspeed_config.json`
> > 报错为 <img alt="image" width="1436" src="https://user-images.githubusercontent.com/44920140/230799233-9d50f90f-161f-4668-b007-6d73d0a60711.png">
> 
> Failed at address这个错误我们这边很难复现出来，应该和您机器本身的环境有关

看样子好像是 fused_adam.so 的问题

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/44920140/230821246-a094c5e0-257f-43f4-96e4-582910492aba.png">

请问可以分享一下你们deepspeed的版本吗？以及你们如何编译这些库的？

**Comment by lemuria-wchen** [comment]
> > > 8卡A800，一直报 launch.py sigkill_handler
> > > <img alt="image" width="1429" src="https://user-images.githubusercontent.com/44920140/230799183-88c374ad-29d7-49bb-9b5c-b10a335143ba.png">
> > > 运行 `python -u finetune.py --local_rank=0 --model_config_file run_config/Bloom_config.json --deepspeed run_config/deepspeed_config.json`
> > > 报错为 <img alt="image" width="1436" src="https://user-images.githubusercontent.com/44920140/230799233-9d50f90f-161f-4668-b007-6d73d0a60711.png">
> > 
> > 
> > Failed at address这个错误我们这边很难复现出来，应该和您机器本身的环境有关
> 
> 看样子好像是 fused_adam.so 的问题
> 
> <img alt="image" width="1439" src="https://user-images.githubusercontent.com/44920140/230821246-a094c5e0-257f-43f4-96e4-582910492aba.png">
> 
> 请问可以分享一下你们deepspeed的版本吗？以及你们如何编译这些库的？

我自己解决了这个问题啦~
需要按照 https://github.com/bigscience-workshop/Megatron-DeepSpeed 里面的方式安装 deepspeed~
