### ISSUE TITLE
数据集咨询

### ISSUE THREAD

**Issue by cxfzzj** [LianjiaTech/BELLE#142]
你好，本人准备想站在巨人的肩膀上继续做一点统一对话大模型的finetune；
看到贵公司BELLE-LLAMA-13b-2M模型性能很有优异，想继续添砖加瓦；所以想咨询一下你们的2M数据和你们的10M和1.5M的数据的重合部分是？

**Comment by isunfloweryg** [comment]
这三份数据都没有重合的。

**Comment by cxfzzj** [comment]
好的，谢谢！

**Comment by yuyq96** [comment]
@isunfloweryg 请问2M的数据和之前训练BLOOM-7B-2M的数据是一样的吗？

**Comment by TestNLP** [comment]
> LLAMA-13b

LLAMA-13b这个原始的模型有吗？BELLE优化的，需要原始的模型才可以使用
