### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for BloomForCausalLM: 这个是内存不足还是torch版本不同

### ISSUE THREAD

**Issue by liukangjia666** [LianjiaTech/BELLE#145]

**Comment by xianghuisun** [comment]
应该和内存没有关系
请问您运行的是哪个代码？

**Comment by Tongjilibo** [comment]
推理的化可以试试看这个复刻版本[belle](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_belle.py)

**Comment by liukangjia666** [comment]
bloom_inference.py这个文件的我看给的列子就是bloom的但是我就只改了model，和load
