### ISSUE TITLE
复刻了一个推理的脚本，int8量化后单卡8g显存可跑

### ISSUE THREAD

**Issue by Tongjilibo** [LianjiaTech/BELLE#146]
复刻了最近出的几个大模型，int8量化后大概是8g左右显存，单卡可以跑起来，[belle](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_belle.py)，[chatglm](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_chatglm.py), [llama](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_llama.py)

**Comment by liukangjia666** [comment]
你这个是那个28g的自己量化的吗，他们的gptq的模型可以直接用吗

**Comment by Tongjilibo** [comment]
> 你这个是那个28g的自己量化的吗，他们的gptq的模型可以直接用吗

量化方式我是用的chatglm的，权重下载下来，用转换脚本转一下，然后就可以跑了，我在本机12g显存的机器上测下来是ok的

**Comment by linqingping** [comment]
转换脚本哪里可以找到？

**Comment by Tongjilibo** [comment]
> 转换脚本哪里可以找到？
现在无需要转换脚本，只是需要使用我提供的bert4torch_config.json即可，可以参考[脚本](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/llama/basic_language_model_llama_belle.py)，[config文件](https://github.com/Tongjilibo/bert4torch/tree/master/examples/basic/llama/belle-llama-7b-2m)
