### ISSUE TITLE
V100训练Llama模型提示 CUDA out of memory

### ISSUE THREAD

**Issue by Tian14267** [LianjiaTech/BELLE#153]
大神们好，我运行Llama模型，运行命令：
`deepspeed --num_gpus=6 finetune.py --model_config_file run_config/Llama_config.json  --deepspeed run_config/deepspeed_config.json `
我一共有 6张 V100 ，但是batch_size=1，但是还是提示` CUDA out of memory`
```
Traceback (most recent call last):
  File "finetune.py", line 236, in <module>
    train(args)
  File "finetune.py", line 214, in train
    trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 2699, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 2731, in compute_loss
    outputs = model(**inputs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 231, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/functional.py", line 1843, in softmax
    ret = input.softmax(dim, dtype=dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 1; 31.75 GiB total capacity; 30.50 GiB already allocated; 33.69 MiB free; 30.64 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

请问这是啥情况啊

**Comment by xianghuisun** [comment]
> 大神们好，我运行Llama模型，运行命令： `deepspeed --num_gpus=6 finetune.py --model_config_file run_config/Llama_config.json --deepspeed run_config/deepspeed_config.json ` 我一共有 6张 V100 ，但是batch_size=1，但是还是提示` CUDA out of memory`
> 
> ```
> Traceback (most recent call last):
>   File "finetune.py", line 236, in <module>
>     train(args)
>   File "finetune.py", line 214, in train
>     trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
>     return inner_training_loop(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
>     tr_loss_step = self.training_step(model, inputs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 2699, in training_step
>     loss = self.compute_loss(model, inputs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 2731, in compute_loss
>     outputs = model(**inputs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
>     loss = self.module(*inputs, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
>     outputs = self.model(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
>     layer_outputs = decoder_layer(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 231, in forward
>     attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/functional.py", line 1843, in softmax
>     ret = input.softmax(dim, dtype=dtype)
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 1; 31.75 GiB total capacity; 30.50 GiB already allocated; 33.69 MiB free; 30.64 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```
> 
> 请问这是啥情况啊

我们是在A100 40G上设置batch_size=1，勉强可以跑起来。所以您的显存确实不够，你可以尝试cpu offload配置，就是训练的比较慢。

**Comment by songxia928** [comment]
cpu offload  

> > 大神们好，我运行Llama模型，运行命令： `deepspeed --num_gpus=6 finetune.py --model_config_file run_config/Llama_config.json --deepspeed run_config/deepspeed_config.json ` 我一共有 6张 V100 ，但是batch_size=1，但是还是提示` CUDA out of memory`
> > ```
> > Traceback (most recent call last):
> >   File "finetune.py", line 236, in <module>
> >     train(args)
> >   File "finetune.py", line 214, in train
> >     trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
> >     return inner_training_loop(
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
> >     tr_loss_step = self.training_step(model, inputs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 2699, in training_step
> >     loss = self.compute_loss(model, inputs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 2731, in compute_loss
> >     outputs = model(**inputs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
> >     return forward_call(*input, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
> >     ret_val = func(*args, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
> >     loss = self.module(*inputs, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
> >     return forward_call(*input, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
> >     output = old_forward(*args, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
> >     outputs = self.model(
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
> >     return forward_call(*input, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
> >     output = old_forward(*args, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
> >     layer_outputs = decoder_layer(
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
> >     return forward_call(*input, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
> >     output = old_forward(*args, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
> >     hidden_states, self_attn_weights, present_key_value = self.self_attn(
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
> >     return forward_call(*input, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
> >     output = old_forward(*args, **kwargs)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 231, in forward
> >     attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
> >   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/torch/nn/functional.py", line 1843, in softmax
> >     ret = input.softmax(dim, dtype=dtype)
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 1; 31.75 GiB total capacity; 30.50 GiB already allocated; 33.69 MiB free; 30.64 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问这是啥情况啊
> 
> 我们是在A100 40G上设置batch_size=1，勉强可以跑起来。所以您的显存确实不够，你可以尝试cpu offload配置，就是训练的比较慢。

大佬，这个 cpu offload 是哪里设置啊。  还是用  CPUOffload 这个包，像下面这样

```
from hfai.nn import CPUOffload
import torchvision
 
model = torchvision.models.resnet50().cuda()
x = torch.randn(256, 3, 244, 224).cuda()
with CPUOffload(offload_ratio=0.1, tag='resnet'):
    out = model(x)
```
