### ISSUE TITLE
运行Bloom模型并修改fp16改为False之后报错

### ISSUE THREAD

**Issue by Tian14267** [LianjiaTech/BELLE#154]
大神们好。我运行Bloom模型，并修改fp16改为False，然后报以下错：
```
Traceback (most recent call last):
  File "finetune.py", line 236, in <module>
    train(args)
  File "finetune.py", line 214, in train
    trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 346, in deepspeed_init
    hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 221, in trainer_config_finalize
    raise ValueError(
ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
- ds fp16.enabled=True vs hf fp16|fp16_full_eval+fp16_backend(amp)=False
The easiest method is to set these DeepSpeed config values to 'auto'.
Traceback (most recent call last):
  File "finetune.py", line 236, in <module>
    train(args)
  File "finetune.py", line 214, in train
    trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 346, in deepspeed_init
    hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 221, in trainer_config_finalize
    raise ValueError(
ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
- ds fp16.enabled=True vs hf fp16|fp16_full_eval+fp16_backend(amp)=False
The easiest method is to set these DeepSpeed config values to 'auto'.
```

fp16 为 True，则会提示另一个问题（应该是显存问题）
```
CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

**Comment by xianghuisun** [comment]
这似乎是某些参数冲突了，可以考虑将deepspeed config中的fp16.enabled=设置为False

**Comment by xianghuisun** [comment]
> 大神们好。我运行Bloom模型，并修改fp16改为False，然后报以下错：
> 
> ```
> Traceback (most recent call last):
>   File "finetune.py", line 236, in <module>
>     train(args)
>   File "finetune.py", line 214, in train
>     trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
>     return inner_training_loop(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
>     deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 346, in deepspeed_init
>     hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 221, in trainer_config_finalize
>     raise ValueError(
> ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
> - ds fp16.enabled=True vs hf fp16|fp16_full_eval+fp16_backend(amp)=False
> The easiest method is to set these DeepSpeed config values to 'auto'.
> Traceback (most recent call last):
>   File "finetune.py", line 236, in <module>
>     train(args)
>   File "finetune.py", line 214, in train
>     trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
>     return inner_training_loop(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
>     deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 346, in deepspeed_init
>     hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)
>   File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/deepspeed.py", line 221, in trainer_config_finalize
>     raise ValueError(
> ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
> - ds fp16.enabled=True vs hf fp16|fp16_full_eval+fp16_backend(amp)=False
> The easiest method is to set these DeepSpeed config values to 'auto'.
> ```
> 
> fp16 为 True，则会提示另一个问题（应该是显存问题）
> 
> ```
> CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
> ```

我们已经更新了代码，目前新版本代码基于deepspeed-chat。可基于最新的代码进行实验
