### ISSUE TITLE
运行generate_instruction.py会报错

### ISSUE THREAD

**Issue by lihuicong** [LianjiaTech/BELLE#16]
KeyError                                  Traceback (most recent call last)
Cell In[4], line 73
     71 instruction_data = []
     72 for result in results:
---> 73     new_instructions = post_process_gpt3_response(num_prompt_instructions, result)
     74     instruction_data += new_instructions
     76 total = len(instruction_data)

直接运行generate_instruction.py文件会报错，显示key不存在，这是啥原因呢
运行命令：
python -m generate_instruction generate_instruction_following_data \
  --output_dir ./ \
  --num_instructions_to_generate 10 \
  --model_name="text-davinci-003" \

python环境：3.9

Cell In[1], line 52, in post_process_gpt3_response(num_prompt_instructions, response)
     50 if response is None:
     51     return []
---> 52 raw_instructions = response["message"]["content"]
     53 if '指令:' not in raw_instructions[0: 10] and '指令：' not in raw_instructions[0: 10]:
     54     raw_instructions = f"{num_prompt_instructions+1}. 指令:" + raw_instructions

KeyError: 'message'

**Comment by bestpredicts** [comment]
看readme里面，需要你导入openai apikey到你的环境变量里面。
```shell
export OPENAI_API_KEY=YOUR_API_KEY

```

**Comment by lihuicong** [comment]
> 看readme里面，需要你导入openai apikey到你的环境变量里面。
> 
> ```shell
> export OPENAI_API_KEY=YOUR_API_KEY
> ```


我没有将openai api_key导入环境变量，但是我是直接在代码里加上openai.api_key='xxxx'这样子的形式的，必须导入环境变量吗

**Comment by bestpredicts** [comment]
> > 看readme里面，需要你导入openai apikey到你的环境变量里面。
> > ```shell
> > export OPENAI_API_KEY=YOUR_API_KEY
> > ```
> 
> 我没有将openai api_key导入环境变量，但是我是直接在代码里加上openai.api_key='xxxx'这样子的形式的，必须导入环境变量吗

之前代码我们默认使用的是chatgpt的api,刚刚添加了对text-davinci-003的支持。你可以重新pull一下代码。
