### ISSUE TITLE
loss波动很大

### ISSUE THREAD

**Issue by ninisy** [LianjiaTech/BELLE#160]
你好，我继续finetune belle-7b-2m发现，loss波动很大。请问有遇到过类似的问题吗？ 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/20498668/231335669-9d1e032f-461e-4b92-a7ed-ba1d475a9399.png">
参数设置：
<img width="325" alt="image" src="https://user-images.githubusercontent.com/20498668/231335791-8823989b-1826-45b5-b43a-daeccbf6ba9a.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/20498668/231335857-5559f1fd-198f-4de2-8ba1-0a0fbd6b1226.png">

**Comment by xianghuisun** [comment]
看着参数配置没什么问题，请问训练后模型的效果如何
