### ISSUE TITLE
belle_7b模型多卡推理结果不对，单卡推理正常

### ISSUE THREAD

**Issue by Crystalxd** [LianjiaTech/BELLE#161]
![20230412-104934](https://user-images.githubusercontent.com/34636084/231335588-65936724-c3f0-4036-9d36-7c9769bb7959.jpeg)
8卡4090推理结果（双卡及以上都是这种乱码的形式）

![20230412-105054](https://user-images.githubusercontent.com/34636084/231335741-5eb8998b-de1b-4514-9177-9a89423be7a6.jpeg)
单卡4090推理结果

以上是使用CUDA_VISIBLE_DEVICES控制卡的数量

请问有可能是什么原因造成的呢？

**Comment by ChuangqHu** [comment]
推理代码是根据generate.py改的么

**Comment by Crystalxd** [comment]
是直接使用https://huggingface.co/BelleGroup/BELLE-7B-2M 里面的推理代码
AutoModelForCausalLM.from_pretrained(model_path)增加了device_map='auto'参数
