### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by tianbuwei** [LianjiaTech/BELLE#162]
执行 BELLE/train 文件夹里面的安装命令，一直报错，是否能够提供一个docker环境

conda env create -f environment.yml，就是这个命令，一直安装失败

**Comment by xianghuisun** [comment]
> 执行 BELLE/train 文件夹里面的安装命令，一直报错，是否能够提供一个docker环境
> 
> conda env create -f environment.yml，就是这个命令，一直安装失败

docker环境我们尽量在近期内提供，会及时通知您。
