### ISSUE TITLE
 I would like to ask you to create an additional Korean-based version.

### ISSUE THREAD

**Issue by EddyLab-AI** [LianjiaTech/BELLE#163]
Hello, I am Korean.

I tested using ELLE_INFER_COLAB.ipynb and confirmed that it works fine.

Thank you very much for your information sharing.

However, I am Korean, so it is very difficult to utilize chat GPT based on Chinese. Of course, I can ask questions in English, but it is not natural.

I think you have the technology to change the default language of LLMA-based.

Therefore, I would like to ask you to create an additional Korean-based version.

If it is difficult to make only Korean, can you develop it so that we can create an environment with Chinese, Korean, and Japanese as initial choices? (I personally recommend it.)

This is a difficult request.

We look forward to your consideration.

Thank you.

Translated with www.DeepL.com/Translator (free version)

**Comment by EddyLab-AI** [comment]
Thanks for the quick feedback :)

After receiving your answer, I searched for datasets for Korean language, 
I was able to find GPT-2 level datasets for Korean language.
https://github.com/ksjae/KoGPT

I'll take some more time to look for it :) 

I will apply the datasets for Korean language, which takes a lot of work, later,

In Korea, I'm using a "chatGPT auto-translator" called "Prompt Genie" a lot.
https://www.promptgenie.ai/

You can use it by installing a Chrome browser extension.
https://chrome.google.com/webstore/detail/%ED%94%84%EB%A1%AC%ED%94%84%ED%8A%B8-%EC%A7%80%EB%8B%88-chatgpt-%EC%9E%90%EB%8F%99-%EB%B2%88%EC%97%AD%EA%B8%B0/lhkgpdljnlplgbkonflbhifackjhjmdj?hl=ko

In the same way, how about supporting CJK charsets as a priority ?

Translated with www.DeepL.com/Translator (free version)

**Comment by tjadamlee** [comment]
we will discuss this point, thanks for your considering our project
