### ISSUE TITLE
问题：finetune的模型生成结果和预训练模型生成结果一模一样

### ISSUE THREAD

**Issue by Tian14267** [LianjiaTech/BELLE#165]
大神好，我再用LoRA进行finetuen训练Bloom模型，训练数据是我自己做的一批数据。
我在进行文本生成的时候发现，finetune的模型生成结果和预训练模型生成结果一模一样，所有问题的结果有一模一样。
我查看了下生成代码，在 `model_name_or_path` 里面给的是预训练的模型，在`lora_weights `里面给的是finetune的权重信息。是不是这里的原因？为啥`model_name_or_path`要给预训练的模型？

**Comment by xianghuisun** [comment]
代码里的逻辑就是先加载预训练模型，然后加载LoRA权重。
        model = AutoModelForCausalLM.from_pretrained(
            base_model,
            torch_dtype=torch.float16,
            device_map="auto",
        )
        if os.path.exists(args.lora_weights):
            model = PeftModel.from_pretrained(
                model,
                args.lora_weights,
                torch_dtype=torch.float16,
            )

**Comment by Tian14267** [comment]
> 先加载预训练模型，然后加载LoRA

大神好，先加载预训练模型，然后加载LoRA权重，这个我知道。并且也确定LoRA权重加载成功。但是生成出来的结果，和预训练模型生成的结果一样。并且输入文本就是finetune训练文本中的，按理说应该生成和训练数据结果类似的。

**Comment by xuguozhi** [comment]
我也遇到了

**Comment by Crystalxd** [comment]
遇到相同的问题，我是20条自定义反常理数据，训练300epochs，loss降低到0.8左右。

**Comment by TestNLP** [comment]
一样的，我也遇到了

**Comment by xuguozhi** [comment]
我基于https://github.com/Macielyoung/Bloom-Lora 训练成功了，
刚开始没有变化一直怀疑自己，后来增加了训练echo num 多次训练，终于让模型有变化了，而且是正常的训练数据的回复

**Comment by TestNLP** [comment]
> 怀疑

你训练了多少epoch？

**Comment by kovogo** [comment]
> 我基于https://github.com/Macielyoung/Bloom-Lora 训练成功了， 刚开始没有变化一直怀疑自己，后来增加了训练echo num 多次训练，终于让模型有变化了，而且是正常的训练数据的回复

大佬训练了多少epochs

**Comment by xuguozhi** [comment]
> > 我基于https://github.com/Macielyoung/Bloom-Lora 训练成功了， 刚开始没有变化一直怀疑自己，后来增加了训练echo num 多次训练，终于让模型有变化了，而且是正常的训练数据的回复
> 
> 大佬训练了多少epochs

我的数据量小，不到一千条，所以训练了500个echo

**Comment by kovogo** [comment]
> > > 我基于https://github.com/Macielyoung/Bloom-Lora 训练成功了， 刚开始没有变化一直怀疑自己，后来增加了训练echo num 多次训练，终于让模型有变化了，而且是正常的训练数据的回复
> > 
> > 
> > 大佬训练了多少epochs
> 
> 我的数据量小，不到一千条，所以训练了500个echo

我迭代了一千次，loss降到了0.4，有效果了但效果不是很好
