### ISSUE TITLE
关于train_on_inputs参数

### ISSUE THREAD

**Issue by cobraheleah** [LianjiaTech/BELLE#169]
想请问下，我看代码里面没有设置train_on_inputs参数，训练的时候是只计算target的loss。如果设置了train_on_inputs参数，就是计算input+target loss，这会有什么影响吗？

**Comment by xianghuisun** [comment]
我们的目标不做预训练，所以只计算target loss。
至于是否计算input loss，对最终效果有多大影响，这个我们没有实验对比过。

**Comment by xianghuisun** [comment]
>
