### ISSUE TITLE
generate_instruction.py生成的数据集与Belle.train.json的格式不一致么

### ISSUE THREAD

**Issue by lihuicong** [LianjiaTech/BELLE#17]
使用generate_instruction.py生成的regen.json文件的格式，与Belle.train.json的格式完全不一样，regen.json的字段更多，且包含了instruction、input、output字段，但是Belle.train.json文件中只有input与target字段。【Stanford Alpaca】做微调的数据格式与regen.json格式相似，Belle.train.json还得再重新调整下格式才能做模型微调吗

**Comment by bestpredicts** [comment]
最后开源出来的Belle.train.json格式是已经将insttruct和input拼接到一起的格式了。

**Comment by lihuicong** [comment]
> 最后开源出来的Belle.train.json格式是已经将insttruct和input拼接到一起的格式了。

那请问下如果想fine-tune BLOOMZ-7b模型的话，数据的形式应该是像Belle.train.json这种格式，还是像regen.json的格式呢
