### ISSUE TITLE
大佬，训练启动是不是过于慢了点

### ISSUE THREAD

**Issue by lemuria-wchen** [LianjiaTech/BELLE#170]
一共几百万的微调数据，加载、map用了接近1个半小时？
我看magtron-deepspeed它们先处理成了二进制，这样速度快很多呢~

**Comment by muziyongshixin** [comment]
我也是发现4M的数据mapping完成之后还会卡住很久没有反应，训练配置是8A100， llama-65b+lora

**Comment by xianghuisun** [comment]
> 一共几百万的微调数据，加载、map用了接近1个半小时？ 我看magtron-deepspeed它们先处理成了二进制，这样速度快很多呢~

我们会参考下，然后加速数据load和tokenized的过程，感谢。
