### ISSUE TITLE
关于LoRA训练出的模型与BELLE-7B-2M模型的格式问题

### ISSUE THREAD

**Issue by Tian14267** [LianjiaTech/BELLE#177]
大神们好，我有一个疑惑，我用LoRA方式训练出的模型，其模型文件结构类似这样：
![image](https://user-images.githubusercontent.com/27938135/231641379-49064844-80ae-43b3-8c96-b0c66a2e4938.png)

但是你们的模型如`BELLE-7B-2M`，其模型结构

![image](https://user-images.githubusercontent.com/27938135/231641486-09c648e6-a21e-45a8-a22c-03cc1d2e9a3f.png)
请问下，我训练出的模型，该如何制作成你们这样类型？是需要打包吗，还是如何处理？

**Comment by xianghuisun** [comment]
可参考https://github.com/tloen/alpaca-lora中export_xx_checkpoint.py
或者你加载了lora权重后，save模型的state_dict，格式与预训练的pytorch_model.bin保持一致
