### ISSUE TITLE
finetune报错

### ISSUE THREAD

**Issue by ChenBinfighting1** [LianjiaTech/BELLE#179]
执行命令：deepspeed --num_gpus=1 finetune.py --model_config_file run_config/Llama_config.json  --deepspeed run_config/deepspeed_config.json
报错：
NotImplementedError: Cannot copy out of meta tensor; no data!

有大佬帮解答吗，感谢

**Comment by xianghuisun** [comment]
麻烦提供下详细的报错日志

**Comment by xianghuisun** [comment]
> 执行命令：deepspeed --num_gpus=1 finetune.py --model_config_file run_config/Llama_config.json --deepspeed run_config/deepspeed_config.json 报错： NotImplementedError: Cannot copy out of meta tensor; no data!
> 
> 有大佬帮解答吗，感谢

我们已经更新了最新版代码，可参考新版代码。
同时提供了docker环境。
