### ISSUE TITLE
请问Bloomz的微调参数是什么呀？

### ISSUE THREAD

**Issue by lemuria-wchen** [LianjiaTech/BELLE#181]
这是我现在根据 hugging face 设置的参数

<img width="537" alt="image" src="https://user-images.githubusercontent.com/44920140/231679144-325488f0-466d-4c7b-b11c-dc56a17ba978.png">

请问你们当时 train 的时候这些参数是怎么设置的呀？

还有一个问题就是，训练 2M 个samples，3个epoch，你们花了多久呢（8卡A100 80G）？

**Comment by lemuria-wchen** [comment]
以及，在设置cut_off = 512，batch size = 64的情况下，我看显卡显存似乎难以占满。。80G 大部分只用了 50~60 G（：

**Comment by ZeyuTeng96** [comment]
> 以及，在设置cut_off = 512，batch size = 64的情况下，我看显卡显存似乎难以占满。。80G 大部分只用了 50~60 G（：

那为何不加大batch size呢？

**Comment by xianghuisun** [comment]
> 以及，在设置cut_off = 512，batch size = 64的情况下，我看显卡显存似乎难以占满。。80G 大部分只用了 50~60 G（：

建议增加cutoff_len至1024或者更大
