### ISSUE TITLE
ValueError: weight is on the meta device, we need a `value` to put in on 0.

### ISSUE THREAD

**Issue by phddamuge** [LianjiaTech/BELLE#183]
非LoRA 模式下保存模型后，在执行generate.py 的时候，加载模型出现如下错误是什么问题呢。 
ValueError: weight is on the meta device, we need a `value` to put in on 0.

**Comment by xianghuisun** [comment]
是不是load_in_8bit的问题。设置为False试下

**Comment by phddamuge** [comment]
> load_in_8bit

不是，好像保存的模型里Embedding层没有weight

**Comment by xianghuisun** [comment]
> > load_in_8bit
> 
> 不是，好像保存的模型里Embedding层没有weight

我们已更新代码，可参考最新代码

**Comment by wzko0** [comment]
你好，我遇到了相同的问题，是这么解决的呢？更新了代码的哪部分可以解释下吗？
