### ISSUE TITLE
generate.py generate the same sentence

### ISSUE THREAD

**Issue by yyl199655** [LianjiaTech/BELLE#187]
The answer generated by generate.py will be restored directly at the end. How to solve this situation? follows:

![image](https://user-images.githubusercontent.com/34408370/231937995-342ecbdb-02fe-477d-8e56-0ffcecfd0708.png)

**Comment by xianghuisun** [comment]
> The answer generated by generate.py will be restored directly at the end. How to solve this situation? follows:
> 
> ![image](https://user-images.githubusercontent.com/34408370/231937995-342ecbdb-02fe-477d-8e56-0ffcecfd0708.png)

The following parameters may yield better results.

model.generate(
            input_ids=input_ids,
            max_new_tokens=512,
            temperature=0.8,
            top_p=0.85,
            top_k=30,
            repetition_penalty=1.2,
            do_sample = True
        )
