### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by Geometryyy** [LianjiaTech/BELLE#197]
怎么解决。。。是在单机多卡跑

**Comment by Geometryyy** [comment]
![image](https://user-images.githubusercontent.com/62296837/232015292-5e4cbaa0-5e88-4898-8987-98b887cfc255.png)

**Comment by xianghuisun** [comment]
麻烦提供下详细的报错日志

**Comment by Geometryyy** [comment]
搞清楚了，是第一个参数传错了，两张卡应该是2

**Comment by kevinuserdd** [comment]
> 搞清楚了，是第一个参数传错了，两张卡应该是2

我也出现这个问题，什么情况
