### ISSUE TITLE
feature-request: publish half-precision models

### ISSUE THREAD

**Issue by peakji** [LianjiaTech/BELLE#2]
The original [bigscience/bloomz-7b1-mt](https://huggingface.co/bigscience/bloomz-7b1-mt) model was released in half-precision (`torch.HalfStorage`), so its weight file is only 14.1 GB in size. I noticed that the current Belle weights are released in`torch.FloatStorage`, so the file size is twice the size of the foundation model.

Is it possible to publish a variant of Belle in half-precision? It would make it easier for everyone to try it out.

**Comment by Life-0-1** [comment]
Actually you can train or infer with fp16 by simple settings, [this doc]( https://huggingface.co/docs/transformers/v4.13.0/en/performance#fp16) may help you. 
We are going to provide some mixed-precision training and inference demo code as well.
