### ISSUE TITLE
谁有量化后的版本？

### ISSUE THREAD

**Issue by pangguoqing** [LianjiaTech/BELLE#20]
https://github.com/cocktailpeanut/dalai，的Alpaca 7B 量化的版本在我的Mac OS M1上可以跑起来。

**Comment by mabaochang** [comment]
我们正在研发量化功能，将大大降低推理的硬件需求，预计本周发布

**Comment by ct1976** [comment]
非常期待，28G的模型下幸苦下了一晚，加载时各种OOM，白下了。

**Comment by yunho** [comment]
大佬太牛, 期待啊

**Comment by tjadamlee** [comment]
量化模型已经发布，见README.md

**Comment by pangguoqing** [comment]
> 量化模型已经发布，见README.md

威武

**Comment by pangguoqing** [comment]
https://developer.nvidia.com/cuda-downloads

**Comment by pangguoqing** [comment]
Mac OS M1没能把量化后的模型跑起来。根据https://github.com/LianjiaTech/BELLE/tree/main/gptq提到的安装过程，依赖 nvidia 提供的CUDA，但MacOS没有nvidia显卡，所以也就没有对应的工具。https://developer.nvidia.com/cuda-downloads

MacOS 是否还有其它方式跑量化后的模型？另外我有一台windows 10，有Nvidia显卡，但显卡比较初级，显存只有5G。但内存有32G。 是否有办法在内存中跑？
