### ISSUE TITLE
可以使用llama.cpp推理belle-model.bin模型吗

### ISSUE THREAD

**Issue by zxmlong** [LianjiaTech/BELLE#200]
如果belle-model.bin使用llama.cpp的int4量化，按理说也能使用llama.cpp进行推理，
./main -m belle-model.bin -n 128 这样执行会报错
error loading model: unknown (magic, version) combination: 9d9a939a, e67684db; is this really a GGML file?

恳求解答，不胜感激。

**Comment by tjadamlee** [comment]
由于模型结构的一些原因，我们选择了基于llama.cpp做了一些调整。一般的llama.cpp没法直接用，抱歉

**Comment by zxmlong** [comment]
你好！邮件已收到！
