### ISSUE TITLE
  关于deepspeed-zero3的LoRa微调

### ISSUE THREAD

**Issue by RealDuxy** [LianjiaTech/BELLE#202]
代码里显示再多卡分布式训练的情况下，我们采用的是ddp方式。模型似乎是fp32位（7b - 28g），然后load_in_8bits，trainer里设置fp16位训练。
我3090在BELLE-7B-2M上继续训练的情况下，长度1024，样本量40W，需要训练到330小时。
想请问一下是出于什么考虑，不采用deepspeed_zero3的模型并行的方式分布式训练Lora呢？这样貌似是会大大提升多卡情况下的训练效率的？

**Comment by xianghuisun** [comment]
采用deepspeed训练LoRA的逻辑，后续会支持。请问您是几张卡，为什么会这么慢。

**Comment by zhangyuanscall** [comment]
> 代码里显示再多卡分布式训练的情况下，我们采用的是ddp方式。模型似乎是fp32位（7b - 28g），然后load_in_8bits，trainer里设置fp16位训练。
> 我3090在BELLE-7B-2M上继续训练的情况下，长度1024，样本量40W，需要训练到330小时。
> 想请问一下是出于什么考虑，不采用deepspeed_zero3的模型并行的方式分布式训练Lora呢？这样貌似是会大大提升多卡情况下的训练效率的？



> 采用deepspeed训练LoRA的逻辑，后续会支持。请问您是几张卡，为什么会这么慢。

请问现在不支持deepspeed训练lora的原因是什么，是因为deepspeed本身和lora逻辑存在冲突么，还是只是该项目的脚本不支持，我理解lora逻辑应该和deepspeed原理是不冲突的，我自己写了LLAMA-13B（FP32）的训练脚本，使用deepspeed-zero3可以进行训练，但是不清楚lora是否真实生效（还没做过全量微调）

**Comment by xianghuisun** [comment]
可参考：https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/
支持deepspeed训练lora

**Comment by kevinuserdd** [comment]
> 

请问你怎么写的？ deepspeed+lora的话，是不是加载模型不支持int8量化，只能torch_dtype = float16

**Comment by xianghuisun** [comment]
> > 
> 
> 请问你怎么写的？ deepspeed+lora的话，是不是加载模型不支持int8量化，只能torch_dtype = float16

你好，原因是deepspeed-chat加载模型不支持int8量化，我们的代码是基于deepspeed-chat做了最小的改动。

**Comment by kevinuserdd** [comment]
> > > 
> > 
> > 
> > 请问你怎么写的？ deepspeed+lora的话，是不是加载模型不支持int8量化，只能torch_dtype = float16
> 
> 你好，原因是deepspeed-chat加载模型不支持int8量化，我们的代码是基于deepspeed-chat做了最小的改动。
谢谢，那就是如果按照如下写，load_in_8bit = True
        model = AutoModelForCausalLM.from_pretrained(
            model_name_or_path,
           load_in_8bit = True,
            device_map=device_map)
那么是可以用lora微调，但是不能deepspeed运行，就是你说的deepspeed不支持加载int8量化吗

**Comment by kevinuserdd** [comment]
> 采用deepspeed训练LoRA的逻辑，后续会支持。请问您是几张卡，为什么会这么慢。

啥时候可以支持？ 目前还没有看到deepspeed支持lora和int8

**Comment by xianghuisun** [comment]
> > 采用deepspeed训练LoRA的逻辑，后续会支持。请问您是几张卡，为什么会这么慢。
> 
> 啥时候可以支持？ 目前还没有看到deepspeed支持lora和int8

现在的代码可以运行deepspeed+lora的。
只是deepspeed不支持INT8训练，所以你想用deepspeed进行LoRA训练，就不要开8bit量化
详见：https://github.com/LianjiaTech/BELLE/blob/main/train/docs/FAQ.md

**Comment by jinminghu-1** [comment]
> > > 采用deepspeed训练LoRA的逻辑，后续会支持。请问您是几张卡，为什么会这么慢。
> > 
> > 
> > 啥时候可以支持？ 目前还没有看到deepspeed支持lora和int8
> 
> 现在的代码可以运行deepspeed+lora的。 只是deepspeed不支持INT8训练，所以你想用deepspeed进行LoRA训练，就不要开8bit量化 详见：https://github.com/LianjiaTech/BELLE/blob/main/train/docs/FAQ.md

您好，请问不开8b deepspeed对非chat模型可以使用lora吗，因为整个过程没有报错，但是训练出来结果有些奇怪

**Comment by jiangxinke** [comment]
good
