### ISSUE TITLE
finetune loss 下降到1.3左右就不再下降了

### ISSUE THREAD

**Issue by Trista0823** [LianjiaTech/BELLE#205]
用的bloom lora finetune，loss在一个epoch的时候下降到了1.3左右，之后直到3个epoch都不再下降了，是没有收敛需要重新训练吗？现在这个的推理效果也很差
`    {
        "input": "Human: 描述如何制作一份自制披萨。\n自制披萨\n\n\nAssistant: ",
        "predict": "制作自制披萨需要准备以下材料：\n食材：\n披萨酱：\n披萨饼：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼
：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食
材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱
：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨",
        "target": "1. 准备面团：将面粉、酵母、盐、水等搅拌揉成面团，醒发30分钟；\n2. 制作酱汁：将番茄酱、盐、橄榄油、大蒜等混合，搅拌均匀备用；\n3. 准备配料：切好菜肴和肉类，例如蘑菇、洋葱、红辣椒、香肠
、火腿等；\n4. 预热烤箱：将烤箱预热至200°C；\n5. 披萨制作：将面团揉好并擀成牛奶盒大小，加入酱汁，撒上配料，再加入芝士等；\n6. 烹饪时间：将制作好的披萨放入烤箱，大约烤15分钟至金黄色；\n7. 食用：从烤箱中>取出披萨，切片，供食用。"
    },
    {
        "input": "Human: 将下列句子翻译成英文。\n我们今天晚上去看电影吧！\n\n\nAssistant: ",
        "predict": "今晚我们去看电影吧！",
        "target": "Let's go watch a movie tonight!"
    }
]`

**Comment by xianghuisun** [comment]
建议您尝试训练LLaMA模型，Bloom lora训练有可能存在意想不到的问题

**Comment by xianghuisun** [comment]
> 用的bloom lora finetune，loss在一个epoch的时候下降到了1.3左右，之后直到3个epoch都不再下降了，是没有收敛需要重新训练吗？现在这个的推理效果也很差 ` { "input": "Human: 描述如何制作一份自制披萨。\n自制披萨\n\n\nAssistant: ", "predict": "制作自制披萨需要准备以下材料：\n食材：\n披萨酱：\n披萨饼：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼 ：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食 材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱 ：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨饼：\n食材：\n披萨酱：\n披萨", "target": "1. 准备面团：将面粉、酵母、盐、水等搅拌揉成面团，醒发30分钟；\n2. 制作酱汁：将番茄酱、盐、橄榄油、大蒜等混合，搅拌均匀备用；\n3. 准备配料：切好菜肴和肉类，例如蘑菇、洋葱、红辣椒、香肠 、火腿等；\n4. 预热烤箱：将烤箱预热至200°C；\n5. 披萨制作：将面团揉好并擀成牛奶盒大小，加入酱汁，撒上配料，再加入芝士等；\n6. 烹饪时间：将制作好的披萨放入烤箱，大约烤15分钟至金黄色；\n7. 食用：从烤箱中>取出披萨，切片，供食用。" }, { "input": "Human: 将下列句子翻译成英文。\n我们今天晚上去看电影吧！\n\n\nAssistant: ", "predict": "今晚我们去看电影吧！", "target": "Let's go watch a movie tonight!" } ]`

我们已经更新了新版代码，可参考最新版代码
