### ISSUE TITLE
BELLE 7B-2M的安全性评测

### ISSUE THREAD

**Issue by TissueC** [LianjiaTech/BELLE#21]
hi，感谢你们的开源工作！我们做了BELLE 7B-2M的安全评测，结果在http://115.182.62.166:18000/public
![image](https://user-images.githubusercontent.com/30566015/227100028-de44d38e-923b-47ae-8938-c950944dc7f6.png)

**Comment by mabaochang** [comment]
感谢评估，目前开源的模型还比较早期，后续我们也会在指令理解安全性上持续迭代，期待能release 更多更好的模型回馈社区

**Comment by TestNLP** [comment]
> 感谢评估，目前开源的模型还比较早期，后续我们也会在指令理解安全性上持续迭代，期待能release 更多更好的模型回馈社区

模型进一步训练的话，需要多少卡？能把你们训练的资源列出来吗？

**Comment by mabaochang** [comment]
> 

我们后续会把实验的更多细节列出来的
