### ISSUE TITLE
[2023/04/17]最新的表格似乎有一些错误，与论文不一致

### ISSUE THREAD

**Issue by AIchenkai** [LianjiaTech/BELLE#210]
另外，在_**Towards Better...**_ 文章中，zh(alpaca-3.5&4) 得分0.679，zh(alpaca-3.5&4) + sharegpt得分0.670，zh(alpaca-3.5&4) + sharegpt + belle-3.5得分0.762，是不是sharegpt的数据产生了干扰，用zh(alpaca-3.5&4)+ belle-3.5会不会有更好的表现？

**Comment by tjadamlee** [comment]
应该是笔误，尽快更新
