### ISSUE TITLE
请问有交流群吗？

### ISSUE THREAD

**Issue by iMountTai** [LianjiaTech/BELLE#212]
如上，希望大佬拉我一下，感激不尽！！！

**Comment by qianchen94** [comment]
+1

**Comment by tjadamlee** [comment]
https://github.com/LianjiaTech/BELLE/blob/main/assets/belle_wechat.jpg

**Comment by qingminghuang** [comment]
大佬，可以拉我一个,+1

**Comment by iMountTai** [comment]
@tjadamlee 群超了200进不去，微信id:lianxin_0629，辛苦加个好友拉我一下，谢谢！

**Comment by lhwcv** [comment]
@tjadamlee  同请求，群超了200进不去，微信id:  lhwcvf，辛苦加个好友拉我一下，感谢！

**Comment by Surbowl** [comment]
> @tjadamlee 同请求，群超了200进不去，微信id: lhwcvf，辛苦加个好友拉我一下，感谢！

链接里已经替换为二群的二维码了，可以进了
