### ISSUE TITLE
generate 出来的 “predict” 基本都是错的，谁遇到过吗 

### ISSUE THREAD

**Issue by songxia928** [LianjiaTech/BELLE#213]
![image](https://user-images.githubusercontent.com/25676023/232427213-afa3e5c1-df41-4ce4-9c77-a93955b66702.png)

```
python generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path  trained_models/models_Bloom
```
运行上面的命令，结果跑出来结果，文不对题，感觉完全是错的。谁遇到这个情况吗

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/25676023/232427213-afa3e5c1-df41-4ce4-9c77-a93955b66702.png)
> 
> ```
> python generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path  trained_models/models_Bloom
> ```
> 
> 运行上面的命令，结果跑出来结果，文不对题，感觉完全是错的。谁遇到这个情况吗

您可以尝试
model = AutoModelForCausalLM.from_pretrained(model_namr_or_path)
tokenizer = AutoTokenizer.from_pretrained(model_namr_or_path)
然后直接model.generate(tokenizer(input))
试试看这样生成的结果如何

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/25676023/232427213-afa3e5c1-df41-4ce4-9c77-a93955b66702.png)
> 
> ```
> python generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path  trained_models/models_Bloom
> ```
> 
> 运行上面的命令，结果跑出来结果，文不对题，感觉完全是错的。谁遇到这个情况吗

另外我们已更新了代码，可参考最新的代码
