### ISSUE TITLE
conda env create -f environment.yml 跑不起来

### ISSUE THREAD

**Issue by taofei-pro** [LianjiaTech/BELLE#214]
![image](https://user-images.githubusercontent.com/28079815/232431585-b9dc60ca-25b0-4afb-a283-a37dd51c8b24.png)

**Comment by taofei-pro** [comment]
是不是只能在Linux下跑呀，在mac和Windows都没跑起来

**Comment by xianghuisun** [comment]
有这个可能吧，我们实验都是在Linux系统上
