### ISSUE TITLE
如何加载特定step保存的模型？

### ISSUE THREAD

**Issue by Taoooo9** [LianjiaTech/BELLE#215]
请问是不是模型训练完才会生成adapter_config.json和adapter_model.bin文件？目前，模型还在训练，只得到了如下的文件：
![image](https://user-images.githubusercontent.com/41136544/232482375-43d2d825-a9db-4039-b611-abca29f8822a.png)
请问这些文件可以加载吗？和adapter_model.bin有什么区别？

**Comment by xianghuisun** [comment]
可以的，adapter_model.bin和pytorch_model.bin是一样的
如果您需要加载中间step保存的模型，可以把pytorch_model.bin命名为adapter_model.bin，同时提供adapter_config.json即可

**Comment by Taoooo9** [comment]
多谢
