### ISSUE TITLE
同级别参数量，模型大小差这么多？

### ISSUE THREAD

**Issue by FrankWhh** [LianjiaTech/BELLE#22]
小白问个问题，ChatGLM和BELLE都是6~7B参数量，怎么ChatGLM权重不到14G，BELLE需要28G之多？

**Comment by mabaochang** [comment]
BELLE模型用的是float32

**Comment by FrankWhh** [comment]
了解，感谢！这块也许可以优化下，huggingface、meta好像做了些FP16、BF16的训练工作
