### ISSUE TITLE
TypeError: torch.distributed.distributed_c10d.init_process_group() got multiple values for keyword argument 'backend'

### ISSUE THREAD

**Issue by Geometryyy** [LianjiaTech/BELLE#226]
![image](https://user-images.githubusercontent.com/62296837/232748516-9e4cf813-7319-4afb-888d-c4ba5de37083.png)
![image](https://user-images.githubusercontent.com/62296837/232748561-0d496a39-6c6f-41ca-82cd-533b46e95d5a.png)

**Comment by xianghuisun** [comment]
请问您的启动命令是什么，deepspeed还是torchrun

**Comment by Geometryyy** [comment]
torchrun，我就是把那个什么proc node设置成显卡数量就好了
&nbsp;


-JiHe-
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 晚上8:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LianjiaTech/BELLE] TypeError: torch.distributed.distributed_c10d.init_process_group() got multiple values for keyword argument &#39;backend&#39; (Issue #226)





 
请问您的启动命令是什么，deepspeed还是torchrun

**Comment by Geometryyy** [comment]
torchrun，这个报错怎么解决哇，有点急
&nbsp;


-JiHe-
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 晚上8:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LianjiaTech/BELLE] TypeError: torch.distributed.distributed_c10d.init_process_group() got multiple values for keyword argument 'backend' (Issue #226)





 
请问您的启动命令是什么，deepspeed还是torchrun

**Comment by foreveronehundred** [comment]
Degrade the transformers to 4.28.1
pip install transformers==4.28.1

**Comment by djaym7** [comment]
same error, downgrading worked

**Comment by Whrannnnn** [comment]
degrade ur transformers version
just pip install transformers==4.28.1

**Comment by Whrannnnn** [comment]
degrade ur transformers version
just pip install transformers==4.28.1
i m done with it

**Comment by jxmorris12** [comment]
if you don't want to downgrade, you can also fix this by upgrading accelerate 0.19.0: `pip install accelerate --upgrade`
