### ISSUE TITLE
多大的gpu 能跑起这个模型，4个12g的gpu能跑起这个模型么？

### ISSUE THREAD

**Issue by zhuchangjiang** [LianjiaTech/BELLE#23]

**Comment by mabaochang** [comment]
应该可以

**Comment by barius** [comment]
是什么硬件？是否支持p2p？我们没有在48g显存上测试过，你们可以试试看，可能需要些激进的优化策略，有啥结论欢迎分享

**Comment by 1667** [comment]
可以直接用CPU在64GB内存电脑上运行

**Comment by 1667** [comment]
2080TI上也能跑，占用差不多8G显存，推理很快

**Comment by MagicCube** [comment]
> 



> 可以直接用CPU在64GB内存电脑上运行

请问需要修改哪些参数呢？GPU 上已经跑通了，想在 64GB CPU 上试一下，但是到处都是跟 CUDA 绑死的代码

**Comment by rickywu** [comment]
> 可以直接用CPU在64GB内存电脑上运行

64G内存可以直接跑吗？

**Comment by 1667** [comment]
> > 
> 
> > 可以直接用CPU在64GB内存电脑上运行
> 
> 请问需要修改哪些参数呢？GPU 上已经跑通了，想在 64GB CPU 上试一下，但是到处都是跟 CUDA 绑死的代码

https://huggingface.co/BelleGroup/BELLE-LLAMA-7B-2M 用这里说明的方式能直接在CPU上跑

**Comment by 1667** [comment]
> > 可以直接用CPU在64GB内存电脑上运行
> 
> 64G内存可以直接跑吗？

可以，就是慢点
