### ISSUE TITLE
train目录下，按照步骤训练完成，但是文本生成报错。bloom和Llama都是一样的报错，提示缺少配置文件。

### ISSUE THREAD

**Issue by LittleHann** [LianjiaTech/BELLE#236]
采用LoRA训练的启动命令(bloom模型):
CUDA_VISIBLE_DEVICES=0 python3 finetune.py --model_config_file run_config/Bloom_config.json --lora_hyperparams_file run_config/lora_hyperparams_bloom.json --use_lora

训练完毕后
trained_models/Llama#
adapter_config.json
adapter_model.bin
special_tokens_map.json
tokenizer_config.json
tokenizer.model
![image](https://user-images.githubusercontent.com/4005113/232943395-6602fdf9-abec-441e-bcb8-36560e3a9d19.png)
文本生成
python3 generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path trained_models/bloom/ --lora_weights trained_models/bloom/
报错：
OSError: trained_models/bloom/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/trained_models/bloom//None' for available files.

**Comment by xianghuisun** [comment]
> 采用LoRA训练的启动命令(bloom模型): CUDA_VISIBLE_DEVICES=0 python3 finetune.py --model_config_file run_config/Bloom_config.json --lora_hyperparams_file run_config/lora_hyperparams_bloom.json --use_lora
> 
> 训练完毕后 trained_models/Llama# adapter_config.json adapter_model.bin special_tokens_map.json tokenizer_config.json tokenizer.model ![image](https://user-images.githubusercontent.com/4005113/232943395-6602fdf9-abec-441e-bcb8-36560e3a9d19.png) 文本生成 python3 generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path trained_models/bloom/ --lora_weights trained_models/bloom/ 报错： OSError: trained_models/bloom/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/trained_models/bloom//None' for available files.

可参考：https://github.com/LianjiaTech/BELLE/issues/131

**Comment by LittleHann** [comment]
你好，感谢回复。
我用lora训练bloom后得到的目录文件如下:
![image](https://user-images.githubusercontent.com/4005113/232986751-ae4e1f44-6e61-44bc-b6b4-ca77137cada3.png)
![image](https://user-images.githubusercontent.com/4005113/232986767-b7f964ee-5dab-4a8b-ab8c-252042992089.png)
然后我运行如下指令:
python3 generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json --model_name_or_path trained_models/bloom/checkpoint-11000 --lora_weights trained_models/bloom/checkpoint-11000

依然报如下错误:
OSError: trained_models/bloom/checkpoint-11000 does not appear to have a file named config.json. Checkout 'https://huggingface.co/trained_models/bloom/checkpoint-11000/None' for available files.
