### ISSUE TITLE
关于answer文本计算loss的问题

### ISSUE THREAD

**Issue by bittteerr** [LianjiaTech/BELLE#239]
文档中提到“在instruction文本部分加上-100作为mask”

但代码中对应的是直接用-100来替换instruction的token

chosen_token["labels"] = torch.LongTensor([-100] * user_prompt_len + chosen_token["input_ids"][user_prompt_len:])

这能实现屏蔽answer的loss的计算么？

**Comment by xianghuisun** [comment]
可参考：https://github.com/tloen/alpaca-lora/blob/main/finetune.py  以及pytorch的CrossEntropyLoss
-100位置是不计算loss的
