### ISSUE TITLE
assert tokenizer.eos_token_id == 2 

### ISSUE THREAD

**Issue by shaomai00** [LianjiaTech/BELLE#243]
在main.py中这里assert了 ，打印tokenizer.eos_token_id=0，这是什么原因呢？

**Comment by yssAI** [comment]
我也是 tokenizer.eos_token_id 和 tokenizer.eos_token_id 都是 0 然后报错卡在这里
![image](https://user-images.githubusercontent.com/43362551/233012568-4f321ae8-f235-4e1c-bf41-d2d3b72c37b3.png)

**Comment by shishijier** [comment]
遇到了同样的问题，请问你们解决了吗？

**Comment by xianghuisun** [comment]
> 我也是 tokenizer.eos_token_id 和 tokenizer.eos_token_id 都是 0 然后报错卡在这里 ![image](https://user-images.githubusercontent.com/43362551/233012568-4f321ae8-f235-4e1c-bf41-d2d3b72c37b3.png)

这个是在用LlamaTokenizer时，确保eos_token_id是2.
您这个是调用的别的Tokenizer，可自行更改

**Comment by xianghuisun** [comment]
> 我也是 tokenizer.eos_token_id 和 tokenizer.eos_token_id 都是 0 然后报错卡在这里 ![image](https://user-images.githubusercontent.com/43362551/233012568-4f321ae8-f235-4e1c-bf41-d2d3b72c37b3.png)

后续会更新这个问题

**Comment by shishijier** [comment]
> > 我也是 tokenizer.eos_token_id 和 tokenizer.eos_token_id 都是 0 然后报错卡在这里 ![image](https://user-images.githubusercontent.com/43362551/233012568-4f321ae8-f235-4e1c-bf41-d2d3b72c37b3.png)
> 
> 后续会更新这个问题

我在decapoda-research/llama-7b-hf的config文件看到eos_token_id=1，bos_token_id=0。这里为什么要确保eos_token_id是2呢？

**Comment by shaomai00** [comment]
您好：我是用的tokenizer来源于decapoda-research/llama-7b-hf，会报这个错
![image](https://user-images.githubusercontent.com/15543933/233031537-4dffcb36-eaaf-40aa-8a6e-84b30023d531.png)

**Comment by xianghuisun** [comment]
> 您好：我是用的tokenizer来源于decapoda-research/llama-7b-hf，会报这个错 ![image](https://user-images.githubusercontent.com/15543933/233031537-4dffcb36-eaaf-40aa-8a6e-84b30023d531.png)

请问您打印出来eos_token_id是几？
这是我的输出结果
![image](https://user-images.githubusercontent.com/89245998/233040680-1e6aa232-5235-4af6-8e98-b7fb2a79b636.png)

**Comment by shaomai00** [comment]
> > 您好：我是用的tokenizer来源于decapoda-research/llama-7b-hf，会报这个错 ![image](https://user-images.githubusercontent.com/15543933/233031537-4dffcb36-eaaf-40aa-8a6e-84b30023d531.png)
> 
> 请问您打印出来eos_token_id是几？ 这是我的输出结果 ![image](https://user-images.githubusercontent.com/89245998/233040680-1e6aa232-5235-4af6-8e98-b7fb2a79b636.png)

![image](https://user-images.githubusercontent.com/15543933/233043635-43b30460-71a8-4ab2-b21c-48c019b46160.png)
这的确很奇怪，我刚刚下载的

**Comment by xianghuisun** [comment]
> > > 您好：我是用的tokenizer来源于decapoda-research/llama-7b-hf，会报这个错 ![image](https://user-images.githubusercontent.com/15543933/233031537-4dffcb36-eaaf-40aa-8a6e-84b30023d531.png)
> > 
> > 
> > 请问您打印出来eos_token_id是几？ 这是我的输出结果 ![image](https://user-images.githubusercontent.com/89245998/233040680-1e6aa232-5235-4af6-8e98-b7fb2a79b636.png)
> 
> ![image](https://user-images.githubusercontent.com/15543933/233043635-43b30460-71a8-4ab2-b21c-48c019b46160.png) 这的确很奇怪，我刚刚下载的

![image](https://user-images.githubusercontent.com/89245998/233044094-5c94d5c9-f35d-4c5a-a79f-aca639a12ecd.png)

居然是transformers版本的问题

**Comment by xianghuisun** [comment]
我们后续会及时更新这个问题

**Comment by qianchen94** [comment]
我也遇到了这个问题... .....

**Comment by shaomai00** [comment]
> 我们后续会及时更新这个问题

感谢解答！我解决了，用新版本的transformer（4.28.1），通过weights转换脚本（https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py），自行转换一次原始的llama，得到的模型再load就正常了。

**Comment by shishijier** [comment]
> > > > 您好：我是用的tokenizer来源于decapoda-research/llama-7b-hf，会报这个错 ![image](https://user-images.githubusercontent.com/15543933/233031537-4dffcb36-eaaf-40aa-8a6e-84b30023d531.png)
> > > 
> > > 
> > > 请问您打印出来eos_token_id是几？ 这是我的输出结果 ![image](https://user-images.githubusercontent.com/89245998/233040680-1e6aa232-5235-4af6-8e98-b7fb2a79b636.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15543933/233043635-43b30460-71a8-4ab2-b21c-48c019b46160.png) 这的确很奇怪，我刚刚下载的
> 
> ![image](https://user-images.githubusercontent.com/89245998/233044094-5c94d5c9-f35d-4c5a-a79f-aca639a12ecd.png)
> 
> 居然是transformers版本的问题

我把transformers版本降到了4.28.0，还是会有这个问题

**Comment by autoexpect** [comment]
改成transformers==4.28.0解决了
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/6939585/236635176-0d991ac7-5630-47f5-912b-6782cd261cfa.png">
