### ISSUE TITLE
能够提供一个非docker的环境吗？

### ISSUE THREAD

**Issue by tomtang110** [LianjiaTech/BELLE#244]
在租的服务器上跑代码，它启动就是一个docker，用的之前你们的环境，发现无法run代码了？

**Comment by Lauorie** [comment]
其实很简单，你先clone一个原deepspeed库，然后pip -r requirements.txt，安装它的requirements，接下来再clone此库来运行即可。

**Comment by xianghuisun** [comment]
> 在租的服务器上跑代码，它启动就是一个docker，用的之前你们的环境，发现无法run代码了？

目前的代码对环境的依赖性较低，可以不用我们提供的docker
conda创建环境后，pip install即可。之前的环境也是可以运行当前版本代码的
