### ISSUE TITLE
无法运行bash training命令

### ISSUE THREAD

**Issue by tomtang110** [LianjiaTech/BELLE#245]
在训练的时候，运行bash training_scripts/single_gpu/run_FT.sh命令，直接什么错误都不报，但是，无法运行，显存看加载了一点，然后程序就死了。

运行bash training_scripts/single_gpu/run_LoRA.sh 的时候，
![image](https://user-images.githubusercontent.com/33299522/233084516-901bd09a-8fb1-491a-9ce0-37075dd2fd2d.png)
z在这个地方卡死不动了。
![image](https://user-images.githubusercontent.com/33299522/233084762-422ef59b-01b7-4166-a2f1-fd3d0cdeefcb.png)
最后这里报错了

**Comment by mabaochang** [comment]
第二张报错图片，像是上一次的任务没有kill干净

**Comment by tomtang110** [comment]
> 第二张报错图片，像是上一次的任务没有kill干净

难道是val set设置为0？

**Comment by tomtang110** [comment]
![image](https://user-images.githubusercontent.com/33299522/233127168-a97d8987-2bdd-4a2a-b605-abe174f4fdee.png)
这个代码确实有问题，一直卡在那里不动，cpu利用率5%，gpu占了700多mb，就卡死了，感觉是锁死了。
![image](https://user-images.githubusercontent.com/33299522/233127439-8e6cb9cb-8061-4ed4-92d8-c0da56df17c6.png)

![image](https://user-images.githubusercontent.com/33299522/233127501-53903d1c-3253-49e6-9add-d2ff7fd78e43.png)

**Comment by iMurphL** [comment]
遇到同样的问题，经排查：
第一个问题：升级deepspeed到0.9.0可以解决
第二个问题：内存不足，free -h查看应该可以内存占用基本满了，可以把数据集改小一点，5w条基本占满了16G

**Comment by iMurphL** [comment]
我弄反了，我这边是
第二个问题：升级deepspeed到0.9.0可以解决报错
第一个问题：阻塞是因为内存不足，free -h查看应该可以内存占用基本满了，我这边把数据集改小就OK了

**Comment by xianghuisun** [comment]
> 在训练的时候，运行bash training_scripts/single_gpu/run_FT.sh命令，直接什么错误都不报，但是，无法运行，显存看加载了一点，然后程序就死了。
> 
> 运行bash training_scripts/single_gpu/run_LoRA.sh 的时候， ![image](https://user-images.githubusercontent.com/33299522/233084516-901bd09a-8fb1-491a-9ce0-37075dd2fd2d.png) z在这个地方卡死不动了。 ![image](https://user-images.githubusercontent.com/33299522/233084762-422ef59b-01b7-4166-a2f1-fd3d0cdeefcb.png) 最后这里报错了

我们已更新了代码，可基于新版本代码试下。另外，建议您在我们提供的docker环境内运行
