### ISSUE TITLE
在单机单卡微调decapoda-research/llama-7b-hf遇到assert tokenizer.eos_token_id == 2

### ISSUE THREAD

**Issue by wjx-sudo** [LianjiaTech/BELLE#246]
![image](https://user-images.githubusercontent.com/78016820/233112416-9fce4895-387a-44b9-addf-5775b86600b7.png)

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/78016820/233112416-9fce4895-387a-44b9-addf-5775b86600b7.png)

可参考： https://github.com/LianjiaTech/BELLE/issues/243
