### ISSUE TITLE
之前的代码deepspeed运行出错

### ISSUE THREAD

**Issue by tomtang110** [LianjiaTech/BELLE#248]
deepspeed --num_gpus=1 finetune.py --model_config_file run_config/Bloom_config.json  --deepspeed run_config/deepspeed_config.json 
运行以上代码，直接用默认的deepspeed配置显卡会爆炸，所以我加了cpu offload
配置如下
![image](https://user-images.githubusercontent.com/33299522/233122371-379f3e22-0f7e-4891-b827-7f4cd576925c.png)
但是这样子最后还是报错，错误如下

![image](https://user-images.githubusercontent.com/33299522/233121798-b1e10ced-a75c-4189-b151-63689fc5b431.png)

**Comment by bestpredicts** [comment]
能提供一下运行的环境嘛？

**Comment by xianghuisun** [comment]
现在请参考我们最新的代码
