### ISSUE TITLE
处理数据到一半直接挂了

### ISSUE THREAD

**Issue by tomtang110** [LianjiaTech/BELLE#249]
![image](https://user-images.githubusercontent.com/33299522/233131541-8a60f3e0-cda0-4e50-8e56-94b00d277ea6.png)
运行命令
![image](https://user-images.githubusercontent.com/33299522/233131692-0840d1b9-63fb-4f3e-b855-a773a77e1ede.png)

**Comment by bestpredicts** [comment]
能否提供一下运行的环境？

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/33299522/233131541-8a60f3e0-cda0-4e50-8e56-94b00d277ea6.png) 运行命令 ![image](https://user-images.githubusercontent.com/33299522/233131692-0840d1b9-63fb-4f3e-b855-a773a77e1ede.png)

我们马上会更新代码，可基于最新代码实验。
