### ISSUE TITLE
新的结合了deepspeed-chat训练脚本中在末尾自动添加了end_of_conversation_token="<|endoftext|>"

### ISSUE THREAD

**Issue by shaomai00** [LianjiaTech/BELLE#253]
https://github.com/LianjiaTech/BELLE/blob/main/train/utils/data/data_utils.py#L269
这个有用吗？训练时没注意，训练完成后发现所有输出都带这个结尾，我测试BELLE-LLaMA-7B的效果是没加这个的

**Comment by shaomai00** [comment]
在最新的代码里似乎仍然有这个问题，https://github.com/LianjiaTech/BELLE/blob/0e9512b925ac07b28e57dc18892458d9ca632ba6/train/utils/data/data_utils.py#L274
烦请指教

**Comment by xianghuisun** [comment]
> BELLE/train/utils/data/data_utils.py

您可参考 create_dataset_split函数，我们并没有用到end_of_conversation_token. 而是在结尾加上tokenizer.eos_token_id

**Comment by shaomai00** [comment]
> 

好的，看到了，谢谢
