### ISSUE TITLE
训练过程中报错

### ISSUE THREAD

**Issue by kevinuserdd** [LianjiaTech/BELLE#257]
lora 原先训练了好几次都没有报错，环境也没变，新增了1000条数据后，就报错如下：
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.14 GiB (GPU 1; 39.41 GiB total capacity; 26.21 GiB already allocated; 5.86 GiB free; 31.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 620 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 621) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>

我的配置是40g*2 = 80g的显存，按道理不会报错oom。

Bloom_config的参数配置如下：
    "batch_size": 4,
    "per_device_train_batch_size": 1,
    "num_epochs": 3,
    "learning_rate": 1e-5,
    "cutoff_len": 2048,
    "val_set_size": 50,
    "val_set_rate": 0.1,
    "save_steps": 200,
    "eval_steps":410,
    "warmup_steps":10,
    "logging_steps":10,
    "gradient_accumulation_steps":8

请问应该如何修改

**Comment by xianghuisun** [comment]
我们现在已经更新了新版代码，基于deepspeed-chat。可参考：https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-chat/chinese
