### ISSUE TITLE
如何fintune呀

### ISSUE THREAD

**Issue by wheniseeyou** [LianjiaTech/BELLE#26]
有人知道如何fintune这个模型吗

**Comment by weberrr** [comment]
同问，希望能够提供finetune代码

**Comment by Awyshw** [comment]
> 有人知道如何fintune这个模型吗

参考[stanford_alpaca](https://github.com/tatsu-lab/stanford_alpaca)的训练

**Comment by raihan0824** [comment]
I have a problem using https://github.com/tatsu-lab/stanford_alpaca to finetune bloom, which I raised an issue in https://github.com/tatsu-lab/stanford_alpaca/issues/111 . Any help on this? I hope the finetuning script is released.

**Comment by mabaochang** [comment]
我们计划本周或下周给出finetune代码

**Comment by mabaochang** [comment]
The finetuning is done on a seperate repo we haven't released yet. Hopefully it will get released soon :)

**Comment by weberrr** [comment]
> > 有人知道如何fintune这个模型吗
> 
> 这里的代码比stanford alpaca更容易上手，且集成了多个数据集，集成了多个LLMs： https://github.com/PhoebusSi/Alpaca-CoT

感恩，这里的代码确实非常方便，我已经从这个git库迁移到使用你这个git库了
