### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Geometryyy** [LianjiaTech/BELLE#262]
![image](https://user-images.githubusercontent.com/62296837/233395420-2cd9bb04-54c0-4985-bbee-00de9d4249c7.png)

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/62296837/233395420-2cd9bb04-54c0-4985-bbee-00de9d4249c7.png)

请问是在docker环境中运行的嘛，运行的是哪个命令

**Comment by wjx-sudo** [comment]
我也遇到同样的问题
运行的是如下命令
export CUDA_VISIBLE_DEVICES=0
python prompt_eval.py \
    --model_name_or_path_baseline decapoda-research/llama-7b-hf \
    --model_name_or_path_finetune output-lora \
    --language Chinese

**Comment by wjx-sudo** [comment]
具体是
![image](https://user-images.githubusercontent.com/78016820/233529653-95013e42-2fc0-40e3-9dda-7c788377d7e8.png)

**Comment by xianghuisun** [comment]
> 具体是 ![image](https://user-images.githubusercontent.com/78016820/233529653-95013e42-2fc0-40e3-9dda-7c788377d7e8.png)

你应该用LlamaTokenizer来load，我发现我用AutoTokenizer也会出现RecursionError: maximum recursion depth exceeded的问题

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/62296837/233395420-2cd9bb04-54c0-4985-bbee-00de9d4249c7.png)

用LlamaTokenizer来load，我用AutoTokenizer也出现了RecursionError: maximum recursion depth exceeded的问题
