### ISSUE TITLE
Belle模型训飞了

### ISSUE THREAD

**Issue by lmxhappy** [LianjiaTech/BELLE#263]
![image](https://user-images.githubusercontent.com/14830063/233521729-82062c98-391d-4f2b-9904-a9c836e27a2d.png)
![image](https://user-images.githubusercontent.com/14830063/233521739-d951a62b-cbb5-4e4b-9716-36213821ada5.png)
搞的不知道什么时候停止了。这个表现就很不理想了。

**Comment by xianghuisun** [comment]
请问您是基于哪一版代码跑出的结果

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/14830063/233521729-82062c98-391d-4f2b-9904-a9c836e27a2d.png) ![image](https://user-images.githubusercontent.com/14830063/233521739-d951a62b-cbb5-4e4b-9716-36213821ada5.png) 搞的不知道什么时候停止了。这个表现就很不理想了。

请问model.generate()的配置参数是什么

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/14830063/233521729-82062c98-391d-4f2b-9904-a9c836e27a2d.png) ![image](https://user-images.githubusercontent.com/14830063/233521739-d951a62b-cbb5-4e4b-9716-36213821ada5.png) 搞的不知道什么时候停止了。这个表现就很不理想了。

您可参考最新的代码
