### ISSUE TITLE
微调的decapoda-research/llama-7b-hf 用的lora方式，微调后的模型生成是乱码

### ISSUE THREAD

**Issue by wjx-sudo** [LianjiaTech/BELLE#264]
![image](https://user-images.githubusercontent.com/78016820/233534185-e3d31e38-2685-40eb-9ddf-b7f576026b6f.png)

**Comment by wjx-sudo** [comment]
运行命令
export CUDA_VISIBLE_DEVICES=0
python prompt_eval.py \
    --model_name_or_path_baseline decapoda-research/llama-7b-hf \
    --model_name_or_path_finetune output-lora \
    --language Chinese

**Comment by wjx-sudo** [comment]
def generate(model,
             tokenizer,
             inputs,
             num_beams=1,
             num_beam_groups=1,
             do_sample=False,
             num_return_sequences=1,
             max_new_tokens=100):

    generate_ids = model.generate(inputs.input_ids,
                                  num_beams=num_beams,
                                  num_beam_groups=num_beam_groups,
                                  do_sample=do_sample,
                                  num_return_sequences=num_return_sequences,
                                  max_new_tokens=max_new_tokens)

    result = tokenizer.batch_decode(generate_ids,
                                    skip_special_tokens=True,
                                    clean_up_tokenization_spaces=False)
    return result

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/78016820/233534185-e3d31e38-2685-40eb-9ddf-b7f576026b6f.png)

1. 您可参考最新的代码
2. decapoda-research/llama-7b-hf并非facebook官方的LLaMA权重，这个模型的tokenizer与facebook的官方LLaMA模型有出入
