### ISSUE TITLE
关于generate_instruction.py：如果prompt里要求输出10，输入例子3的话经常超出max_token，生成效率极低，想问下你们生产模式下是和现有代码相同设置生成数据的吗？

### ISSUE THREAD

**Issue by LeopoldACC** [LianjiaTech/BELLE#27]
具体error
![image](https://user-images.githubusercontent.com/44536699/227432120-6928242b-e6a5-4666-bdd1-d48cec73772d.png)

**Comment by bestpredicts** [comment]
建议将max_len调小。多次运行的方法来反复生产。

**Comment by LeopoldACC** [comment]
想问下你们生成有效数据的qps大概是多少？我这边大概是2个/100s。
