### ISSUE TITLE
对LORA与全量微调对比实验的疑问？

### ISSUE THREAD

**Issue by zhangyuanscall** [LianjiaTech/BELLE#277]
[A Comparative Study between Full-Parameter and LoRA-based Fine-Tuning on Chinese Instruction Data for Instruction Following Large Language Model]
之前对PEFT比较熟悉，针对这篇文章，有两点质疑：
> lora关键参数alpha会对实验结果有很大的影响，然而在文章实验中并没有给出该参数，以及该参数对实验结果的影响

> PEFT一般达到收敛需要比全量化微调训练更多的epoch，这是PEFT本身存在的缺陷，然而LORA实验中给出的epoch是4，仅仅比FULL高一个epoch，如果是需要对比LORA与FULL的效果，实验对比存在严重不公平

以上关键点都会影响最终的实验结论，希望能够得到解答

**Comment by a2012456373** [comment]
对的，lora的效果也跟r值，以及target_module选择有关，这决定了lora的可训练参数量，然而实验中的可训练lora参数过小，并且也存在训练时长不足，单纯的否认lora微调是不可行的，实验对比存在严重不公平

**Comment by a2012456373** [comment]
![image](https://user-images.githubusercontent.com/76865636/233812346-950d6a38-96da-4d3a-b6ca-d666967d825f.png)

**Comment by xianghuisun** [comment]
> [A Comparative Study between Full-Parameter and LoRA-based Fine-Tuning on Chinese Instruction Data for Instruction Following Large Language Model] 之前对PEFT比较熟悉，针对这篇文章，有两点质疑：
> 
> > lora关键参数alpha会对实验结果有很大的影响，然而在文章实验中并没有给出该参数，以及该参数对实验结果的影响
> 
> > PEFT一般达到收敛需要比全量化微调训练更多的epoch，这是PEFT本身存在的缺陷，然而LORA实验中给出的epoch是4，仅仅比FULL高一个epoch，如果是需要对比LORA与FULL的效果，实验对比存在严重不公平
> 
> 以上关键点都会影响最终的实验结论，希望能够得到解答

您好，关于您的第一点疑问，alpha值设置为16。实验的Lora参数配置参考自：https://github.com/project-baize/baize-chatbot/blob/main/finetune.py
关于您的第二点疑问，训练多少epoch可能和训练数据量也有关系。我们实验对比了2个epoch和4个epoch的测试结果，发现4个epoch的效果仅比2个epoch高出0.3个点左右，并没有显著提升。

我们也会基于您的两点疑问再设计一组参数来看实验效果，希望能解答您的疑问。您如果有训练好的模型，也可以提供您训练的checkpoint。

**Comment by xianghuisun** [comment]
> 对的，lora的效果也跟r值，以及target_module选择有关，这决定了lora的可训练参数量，然而实验中的可训练lora参数过小，并且也存在训练时长不足，单纯的否认lora微调是不可行的，实验对比存在严重不公平

您好，我们绝对不是要否定LoRA算法，并不是说对LoRA的超参数进行仔细的调参，然后证明LoRA确实不如全量参数微调。实验的超参数参考自 https://github.com/project-baize/baize-chatbot/blob/main/finetune.py

关于训练时长不足的疑问，实验对比了2个epoch和4个epoch的测试结果，发现4个epoch的效果仅比2个epoch高出0.3个点左右，并没有显著提升，我们认为这和训练数据量也有关系。
鉴于您的疑问，我们会进一步做更多的epoch训练，看看最终效果是否能有显著提升

**Comment by xianghuisun** [comment]
> [A Comparative Study between Full-Parameter and LoRA-based Fine-Tuning on Chinese Instruction Data for Instruction Following Large Language Model] 之前对PEFT比较熟悉，针对这篇文章，有两点质疑：
> 
> > lora关键参数alpha会对实验结果有很大的影响，然而在文章实验中并没有给出该参数，以及该参数对实验结果的影响
> 
> > PEFT一般达到收敛需要比全量化微调训练更多的epoch，这是PEFT本身存在的缺陷，然而LORA实验中给出的epoch是4，仅仅比FULL高一个epoch，如果是需要对比LORA与FULL的效果，实验对比存在严重不公平
> 
> 以上关键点都会影响最终的实验结论，希望能够得到解答

另外值得一提的是，我们也对 https://github.com/ymcui/Chinese-LLaMA-Alpaca 发布的模型进行了测试
实验效果其实和论文中LLaMA-7B+LoRA(2M)的分数相当。而他们发布的权重 https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b/blob/main/adapter_config.json 的alpha值为32
