### ISSUE TITLE
brainstorming vs generation

### ISSUE THREAD

**Issue by makai281** [LianjiaTech/BELLE#280]
对给定测试集合中的brainstorming和generation的划分比较迷惑，请问一下，在划分这两个类别时候的主要依据是什么？

**Comment by xianghuisun** [comment]
> 对给定测试集合中的brainstorming和generation的划分比较迷惑，请问一下，在划分这两个类别时候的主要依据是什么？

我们是按照openAI提出的标准进行分类的
