### ISSUE TITLE
BLOOMZ-1.7B全量参数finetune，cuda out of memory

### ISSUE THREAD

**Issue by xdnjust** [LianjiaTech/BELLE#281]
大神你好，感谢开源工作，我现在尝试使用BLOOMZ-1.7B作为基础模型（bin文件3.44GB）来finetune一个对话模型，使用的是train_scripts/single_gpu/run_FT.sh，我的GPT是32GB配置的V100，请问还是不够训练吗？我看一直报错cuda out of memory。

![image](https://user-images.githubusercontent.com/38311101/233832566-fea8b70d-f94c-4d5a-b6ad-f9cb1f1b4793.png)

**Comment by xdnjust** [comment]
试了一下run_LORA.sh，发现也out of memory，是我哪里设置不对吗？

**Comment by listwebit** [comment]
+1

**Comment by xianghuisun** [comment]
> 大神你好，感谢开源工作，我现在尝试使用BLOOMZ-1.7B作为基础模型（bin文件3.44GB）来finetune一个对话模型，使用的是train_scripts/single_gpu/run_FT.sh，我的GPT是32GB配置的V100，请问还是不够训练吗？我看一直报错cuda out of memory。
> 
> ![image](https://user-images.githubusercontent.com/38311101/233832566-fea8b70d-f94c-4d5a-b6ad-f9cb1f1b4793.png)

是的，FAQ.md里面有提到，40G的A100才能训起来，还得把max_seq_len设置的很小才行

**Comment by xdnjust** [comment]
> > 大神你好，感谢开源工作，我现在尝试使用BLOOMZ-1.7B作为基础模型（bin文件3.44GB）来finetune一个对话模型，使用的是train_scripts/single_gpu/run_FT.sh，我的GPT是32GB配置的V100，请问还是不够训练吗？我看一直报错cuda out of memory。
> > ![image](https://user-images.githubusercontent.com/38311101/233832566-fea8b70d-f94c-4d5a-b6ad-f9cb1f1b4793.png)
> 
> 是的，FAQ.md里面有提到，40G的A100才能训起来，还得把max_seq_len设置的很小才行

run_LORA也是这样吗？这是为什么呢，LORA只训练增量参数啊
