### ISSUE TITLE
如何多机多卡训练？

### ISSUE THREAD

**Issue by muziyongshixin** [LianjiaTech/BELLE#282]
我这边发现deepspeed进行多机多卡训练需要配置一个hostfile和多机之间的免密ssh通信
请问大佬试过在k8s环境下如何启动多机多卡训练吗？
训练前无法知道具体的ip(因此不能提前写好hostfile)
同时也没有办法免密ssh通信

**Comment by xianghuisun** [comment]
> 我这边发现deepspeed进行多机多卡训练需要配置一个hostfile和多机之间的免密ssh通信 请问大佬试过在k8s环境下如何启动多机多卡训练吗？ 训练前无法知道具体的ip(因此不能提前写好hostfile) 同时也没有办法免密ssh通信

您好，多机多卡的训练还不支持。可参考deepspeed-chat项目。
