### ISSUE TITLE
怎么直接训练本地模型文件？

### ISSUE THREAD

**Issue by forestbat** [LianjiaTech/BELLE#283]
我有个ggml-model-q4_0.bin模型文件（从llama.cpp生成），如果直接对文件训练（如下）：
```
deepspeed main.py \
   --sft_only_data_path ./BELLE/train_2M_CN.json \
   --model_name_or_path ./……/llama/models/7B/ggml-model-q4_0.bin \
   ……
```
就会报错：
```
raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './……/llama/models/7B/ggml-model-q4_0.bin'. Use `repo_type` argument if needed.
```
跟[这个issue](https://github.com/tatsu-lab/stanford_alpaca/issues/233)应该是同一个原因。
如何解决？感激不尽！

**Comment by xianghuisun** [comment]
> 

model_name_or_path不能只是个.bin文件。而且必须是pytorch_model.bin，还要给出预训练的config

**Comment by forestbat** [comment]
> > 
> 
> model_name_or_path不能只是个.bin文件。而且必须是pytorch_model.bin，还要给出预训练的config

如何将ggml.bin或者pth文件转换成pytorch_model.bin？没有现成脚本的话，可以给个思路或者文档吗？
