### ISSUE TITLE
谁能帮忙解决呀，都是用的官方的docker;File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 133, in __init__     self.dtype = self.optimizer.param_groups[0]['params'][0].dtype

### ISSUE THREAD

**Issue by listwebit** [LianjiaTech/BELLE#285]
<img width="760" alt="35" src="https://user-images.githubusercontent.com/5664241/233838937-ad4a8150-7c36-4476-9ba5-b88aac8b808c.png">

**Comment by xianghuisun** [comment]
> <img alt="35" width="760" src="https://user-images.githubusercontent.com/5664241/233838937-ad4a8150-7c36-4476-9ba5-b88aac8b808c.png">

您运行的是哪个脚本

**Comment by xianghuisun** [comment]
> <img alt="35" width="760" src="https://user-images.githubusercontent.com/5664241/233838937-ad4a8150-7c36-4476-9ba5-b88aac8b808c.png">

如果把transformers版本降低为4.28.1试下呢

**Comment by bestpredicts** [comment]
确认了一下，可docker镜像没有关系。

**Comment by listwebit** [comment]
运行的是bash training_scripts/single_node/run_Loro.sh

**Comment by derrickcyt** [comment]
同问

**Comment by xianghuisun** [comment]
> <img alt="35" width="760" src="https://user-images.githubusercontent.com/5664241/233838937-ad4a8150-7c36-4476-9ba5-b88aac8b808c.png">

我们已经更新了LoRA训练的代码。
