### ISSUE TITLE
LLaMA-7B-EXT

### ISSUE THREAD

**Issue by qingswu** [LianjiaTech/BELLE#289]
请问公开的LLaMA-7B-EXT是扩展词表后二次与训练的base model吗？会公布基于下面数据集finetune之后的模型吗？

```
LLaMA-7B-EXT | zh(alpaca-3.5&4) + sharegpt + BELLE-0.5M-CLEAN | 0.762
```

**Comment by xianghuisun** [comment]
不，公开的LLaMA-7B-EXT就是LLaMA-7B-EXT + zh(alpaca-3.5&4) + sharegpt + BELLE-0.5M-CLEAN
