### ISSUE TITLE
基于BELLE-LLAMA-7B-2M，使用lora，zero_stage=2训练，预测时load pytorch_model.bin失败

### ISSUE THREAD

**Issue by shaomai00** [LianjiaTech/BELLE#292]
Traceback (most recent call last):
  File "python3.8/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "python3.8/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "python3.8/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.8/site-packages/transformers/modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prompt_eval.py", line 68, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "python3.8/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "python3.8/site-packages/transformers/modeling_utils.py", line 2477, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "python3.8/site-packages/transformers/modeling_utils.py", line 431, in load_state_dict
    raise OSError(
**OSError: Unable to load weights from pytorch checkpoint file for 'output-lora/pytorch_model.bin' at 'output-lora/pytorch_model.bin'.** If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

另外试了一下 set from_tf=True也会报错。

**Comment by xianghuisun** [comment]
> Traceback (most recent call last): File "python3.8/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict return torch.load(checkpoint_file, map_location="cpu") File "python3.8/site-packages/torch/serialization.py", line 777, in load with _open_zipfile_reader(opened_file) as opened_zipfile: File "python3.8/site-packages/torch/serialization.py", line 282, in **init** super(_open_zipfile_reader, self).**init**(torch._C.PyTorchFileReader(name_or_buffer)) RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "python3.8/site-packages/transformers/modeling_utils.py", line 419, in load_state_dict if f.read(7) == "version": File "python3.8/codecs.py", line 322, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "prompt_eval.py", line 68, in model = AutoModelForCausalLM.from_pretrained( File "python3.8/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained return model_class.from_pretrained( File "python3.8/site-packages/transformers/modeling_utils.py", line 2477, in from_pretrained state_dict = load_state_dict(resolved_archive_file) File "python3.8/site-packages/transformers/modeling_utils.py", line 431, in load_state_dict raise OSError( **OSError: Unable to load weights from pytorch checkpoint file for 'output-lora/pytorch_model.bin' at 'output-lora/pytorch_model.bin'.** If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
> 
> 另外试了一下 set from_tf=True也会报错。

这像是模型文件本身的问题

**Comment by shaomai00** [comment]
感谢回复，问题找到了。的确是没有正确保存好模型。

**Comment by shaomai00** [comment]
> 感谢回复，问题找到了。的确是没有正确保存好模型。

**Comment by YujiHuang** [comment]
请问怎么解决呀？
