### ISSUE TITLE
run docker:  RuntimeError: Unable to proceed, no GPU resources available

### ISSUE THREAD

**Issue by loveJasmine** [LianjiaTech/BELLE#294]
(base) ub2004@ub2004-B85M-A0:~/llm_dev/BELLE/train$ sudo docker run -it belle:v1.0 /bin/bash
[sudo] password for ub2004: 

=============
== PyTorch ==
=============

NVIDIA Release 22.08 (build 42105213)
PyTorch Version 1.13.0a0+d321be6

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2022 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...

root@61e995d5a182:/workspace# 

root@61e995d5a182:/workspace# git clone https://github.com/LianjiaTech/BELLE
Cloning into 'BELLE'...
fatal: unable to access 'https://github.com/LianjiaTech/BELLE/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
root@61e995d5a182:/workspace# git clone https://github.com/LianjiaTech/BELLE
Cloning into 'BELLE'...
remote: Enumerating objects: 1447, done.
remote: Counting objects: 100% (439/439), done.
remote: Compressing objects: 100% (240/240), done.
remote: Total 1447 (delta 362), reused 199 (delta 199), pack-reused 1008
Receiving objects: 100% (1447/1447), 10.90 MiB | 7.82 MiB/s, done.
Resolving deltas: 100% (810/810), done.
root@61e995d5a182:/workspace# 
root@61e995d5a182:/workspace# 
root@61e995d5a182:/workspace# cd BELLE/train/

root@61e995d5a182:/workspace/BELLE/train# bash training_scripts/single_gpu/run_FT.sh
./output
0
[2023-04-24 05:55:17,551] [WARNING] [runner.py:190:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Traceback (most recent call last):
  File "/opt/conda/bin/deepspeed", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/runner.py", line 406, in main
    raise RuntimeError("Unable to proceed, no GPU resources available")
RuntimeError: Unable to proceed, no GPU resources available
root@61e995d5a182:/workspace/BELLE/train#

**Comment by zhangfeiyu5610** [comment]
i have the same question. Do you solve it?

**Comment by loveJasmine** [comment]
(gh_BELLE) ub2004@ub2004-B85M-A0:~/llm_dev/BELLE/train$ sudo docker run -it -runtime=nvidia --shm-size="40g" belle:v1.0 /bin/bash
unknown shorthand flag: 'r' in -runtime=nvidia
See 'docker run --help'.
(gh_BELLE) ub2004@ub2004-B85M-A0:~/llm_dev/BELLE/train$

**Comment by loveJasmine** [comment]
what?
