### ISSUE TITLE
belle-7b-2M ft后vocab_size对不齐。size mismatch for transformer.word_embeddings.weight: copying a param with shape torch.Size([250680, 4096]) from checkpoint, the shape in current model is torch.Size([250880, 4096]).

### ISSUE THREAD

**Issue by AlexXx-Wu** [LianjiaTech/BELLE#296]
finetune 后eval报错
RuntimeError: Error(s) in loading state_dict for BloomForCausalLM:
        size mismatch for transformer.word_embeddings.weight: copying a param with shape torch.Size([250680, 4096]) from checkpoint, the shape in current model is torch.Size([250880, 4096]).

**Comment by xianghuisun** [comment]
> 

我们也发现了这个问题，但是训练LLaMA或者opt模型就不会出现这个问题。
Deepspeed-chat官方的issue中也有提到保存Bloom模型会出问题，参考：https://github.com/microsoft/DeepSpeedExamples/issues/407

这个问题我们会及时解决，如果您解决了，也可及时告知我们

**Comment by xianghuisun** [comment]
> finetune 后eval报错 RuntimeError: Error(s) in loading state_dict for BloomForCausalLM: size mismatch for transformer.word_embeddings.weight: copying a param with shape torch.Size([250680, 4096]) from checkpoint, the shape in current model is torch.Size([250880, 4096]).

我找到原因了
![image](https://user-images.githubusercontent.com/89245998/233967464-b296b9c4-d425-4130-a711-fe7b36504f10.png)

也就是在create_hf_model方法中resize_token_embeddings这里出的问题。
您可以尝试去掉resize_token_embeddings那几行代码。
我们后续及时更新我们的代码。

**Comment by Bob199511** [comment]
原始模型的词表再微调后加载出现不匹配的情况，也可以不直接加载原始模型，修改 tokenizer = AutoTokenizer.from_pretrained(微调后的模型文件)，这样就匹配了

**Comment by Bob199511** [comment]
对于没有保存微调后的tiokenizer的情况，可以尝试加载微调后的模型权重进行配置。
![image](https://user-images.githubusercontent.com/97025063/236763977-e91b219b-1dd0-41b9-8500-f3590740417f.png)
