### ISSUE TITLE
关于效果的疑问

### ISSUE THREAD

**Issue by a2012456373** [LianjiaTech/BELLE#304]
为什么vicuna13b只用了7万条指令数据就可以达到chatgpt的90%，而咱们这个项目用了指令数据都上百万条了 ，按理来说大模型的语言迁移能力应该很强啊，还是说vicuna的评测不够全面？

**Comment by FrankWhh** [comment]
vicuna13b 英文确实很强，中文受限于llama稍弱

**Comment by yaleimeng** [comment]
底座模型的中文太差。vicuna自己的评测也不是很全面

**Comment by a2012456373** [comment]
嗯，明白了，期待13b的中文模型。
