### ISSUE TITLE
Bloomz 使用 1.5M sft 数据 finetune 需要的内存？

### ISSUE THREAD

**Issue by SefaZeng** [LianjiaTech/BELLE#305]
我想从 Bloomz 的模型 finetune，复现一下你们的模型效果。我用两台 V100,290G 的内存，数据处理过程会 OOM，这个大概需要多大的内存？

**Comment by xianghuisun** [comment]
> 我想从 Bloomz 的模型 finetune，复现一下你们的模型效果。我用两台 V100,290G 的内存，数据处理过程会 OOM，这个大概需要多大的内存？

通过观察，2M的数据量，加载需要的内存大约是350G左右，加载时长在25分钟左右

**Comment by xianghuisun** [comment]
> 我想从 Bloomz 的模型 finetune，复现一下你们的模型效果。我用两台 V100,290G 的内存，数据处理过程会 OOM，这个大概需要多大的内存？

目前的代码还没有对加载数据这块做优化，消耗的内存还是比较高的。
