### ISSUE TITLE
全参微调时deepspeed.initialize加载问题

### ISSUE THREAD

**Issue by wqn1** [LianjiaTech/BELLE#311]
训练环境时2张A100 80G；
基于deepspeed的全参微调时，总是在deepspeed.initialize发生OOM的问题，zero_stage指定为3，batch也比较小，但是还会爆显存，请问这种问题有对应的解决措施吗？

**Comment by wqn1** [comment]
用微软的deepspeed-chat试了下，感觉他们的代码是类似的

**Comment by xianghuisun** [comment]
> 

您好，我们经过实验发现：全量参数微调bloomz-7b1模型，在4张40G A100上，出现了显存不足的问题
在6张40G A100上则可以运行成功

**Comment by xianghuisun** [comment]
> > 
> 
> 您好，我们经过实验发现：全量参数微调bloomz-7b1模型，在4张40G A100上，出现了显存不足的问题 在6张40G A100上则可以运行成功

train_batch=1, zero_stage=3, max_seq_len=512

**Comment by xianghuisun** [comment]
> 训练环境时2张A100 80G； 基于deepspeed的全参微调时，总是在deepspeed.initialize发生OOM的问题，zero_stage指定为3，batch也比较小，但是还会爆显存，请问这种问题有对应的解决措施吗？

如果全量参数微调LLaMA-7B模型，则可在4张40G A100上运行成功，不会出现显存不足的问题。
train_batch=1, zero_stage=3, max_seq_len=1024

所以，您2张A100 80G，应该可以全量参数微调LLaMA-7B模型

**Comment by xianghuisun** [comment]
> 用微软的deepspeed-chat试了下，感觉他们的代码是类似的

我们的代码完全基于deepspeed-chat

**Comment by wqn1** [comment]
好的，目前调参后基本能跑bloom和llama，但是过程中会出现如下异常，不知道对精度有没有影响
“1 pytorch allocator cache flushes since last step. this happens when there is high memory pressure and is detrimental to performance. if this is happening frequently consider adjusting settings to reduce memory consumption. If you are unable to make the cache flushes go away consider adding get_accelerator().empty_cache() calls in your training loop to ensure that all ranks flush their caches at the same time”
