### ISSUE TITLE
BELLE-LLaMA-EXT-7B 模型md5不一致

### ISSUE THREAD

**Issue by allenhung1025** [LianjiaTech/BELLE#314]
md5不一致
https://huggingface.co/BelleGroup/BELLE-LLaMA-EXT-7B
下载后pytorch_model-00001-of-00002.bin.3b0666c50d7fd55d5116e788ec51aa96a34ba6816e86ffbee1dbe983bf511b4b.enc的md5sum和官网上的不一致
想请问如何解决

<img width="1092" alt="Screen Shot 2023-04-26 at 3 06 41 PM" src="https://user-images.githubusercontent.com/22190213/234496589-fff7b538-7754-4a56-bc0b-d7f0b12a934f.png">
<img width="667" alt="Screen Shot 2023-04-26 at 3 07 18 PM" src="https://user-images.githubusercontent.com/22190213/234496743-db1fca7b-e470-44d8-bed0-03a03fc28157.png">

**Comment by hejujie** [comment]
你这个是还没有解码的文件吧？需要先解码再check md5。

**Comment by allenhung1025** [comment]
已經解決了，沒有下載完全的檔案

**Comment by wqn1** [comment]
基于2月底网传的llama权重文件解码后，md5是一样的，但是模型效果很糟糕，这个是因为llama原始权重的影响吗？

**Comment by hejujie** [comment]
> 基于2月底网传的llama权重文件解码后，md5是一样的，但是模型效果很糟糕，这个是因为llama原始权重的影响吗？

也可能跟你的prompt还有生成的参数有关，你可以对齐一下。

**Comment by lixiaoxiaobin** [comment]
> 已經解決了，沒有下載完全的檔案

这个是什么意思，没下载全解密文件还是模型文件？
