### ISSUE TITLE
deepspeed 使用问题

### ISSUE THREAD

**Issue by kevinuserdd** [LianjiaTech/BELLE#322]
deepspeed --num_gpus=2 finetune.py --model_config_file run_config/Bloom_config.json  --deepspeed run_config/deepspeed_config.json --lora_hyperparams_file run_config/lora_hyperparams_bloom.json --use_lora

使用deepspeed+lora的方法会报错，RuntimeError: expected scalar type Float but found Half 
请问是写法不对吗？

**Comment by xianghuisun** [comment]
> deepspeed --num_gpus=2 finetune.py --model_config_file run_config/Bloom_config.json --deepspeed run_config/deepspeed_config.json --lora_hyperparams_file run_config/lora_hyperparams_bloom.json --use_lora
> 
> 使用deepspeed+lora的方法会报错，RuntimeError: expected scalar type Float but found Half 请问是写法不对吗？

deepspeed与8bit量化训练是冲突的，如果您想使用deepspeed加速训练，那么就不能采用8bit量化
