### ISSUE TITLE
都搞了两周了，都搞崩溃了，用你们的docker环境，也试了,finetune版本的，推理没有一个正常的，都是瞎推理。。。。。

### ISSUE THREAD

**Issue by listwebit** [LianjiaTech/BELLE#324]
下载的docker环境，gpu用的3块V100,32G
训练用：bash training_scripts/single_node/run_LoRA.sh output-lora 2
模型用的：BELLE-7B-2M
结果是这样的，也不知道咋回事，也没有改代码
也实验历史版本：https://github.com/LianjiaTech/BELLE/tree/4f84c89372b435bae039b47f1f31078b1c6fc23e/train
结果推理的都是胡说八道。

{"instruction": "头痛头昏十几年前。吹风和晒太阳。吵闹都会头疼没有检查出来结果应该怎样治疗", "generate_text": "Human: 头痛头昏十几年前。
吹风和晒太阳。吵闹都会头疼没有检查出来结果应该怎样治疗\nAssistant: 敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲
敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲敲>敲敲敲敲敲敲敲敲6"}
{"instruction": "眼睛疲劳，老睁不开干涩", "generate_text": "Human: 眼睛疲劳，老睁不开干涩\nAssistant: 眼睛疲劳，老睁公斤干涩。"}
{"instruction": "女人的左胸下是什么地？那里痛是怎么回事", "generate_text": "Human: 女人的左胸下是什么地？那里痛是怎么回事\nAssistant: >题目中给出了小明、张三、李四、王五、钱六、周七、张二、张三、张四、张五、张六、张七、张二、张三、张四、张五、张六、张七、张二、张四、张>五、张六、张五、张六、张五、张六、张五、张六、张五、张六、张五、张六、张五、张五、张五、张五、张五、张五、张五、张五、张五,。"}
{"instruction": "女人的左胸下是什么地？那里痛是怎么回事", "generate_text": "Human: 女人的左胸下是什么地？那里痛是怎么回事\nAssistant: >题目中给出了小明、张三、李四、王五、钱六、周七、张二、张三、张四、张五、张六、张七、张二、张三、张四、张五、张六、张七、张二、张四、张>五、张六、张五、张六、张五、张六、张五、张六、张五、张六、张五、张六、张五、张六、张五、张五、张五、张五、张五、张五、张五、张五,。"}
{"instruction": "女人的左胸下是什么地？那里痛是怎么回事", "generate_text": "Human: 女人的左胸下是什么地？那里痛是怎么回事\nAssistant:

**Comment by listwebit** [comment]
chatGLM也支持V100，也不知道你们这是模型是咋回事呢

**Comment by Surbowl** [comment]
被一堆“敲”字逗乐了

**Comment by ljg-lixufeng** [comment]
v100能跑的动？我4块v100,40g的都跑不起来呀

**Comment by ljg-lixufeng** [comment]
确实服务复现

**Comment by hannlp** [comment]
可以看看lora参数是否正确保存了，一般都是10M+，要是几百字节的话就没有正确保存，推理的时候相当于直接用原始模型推理了

**Comment by zztMermory** [comment]
要崩溃+1，密密麻麻的重复要崩溃了
