### ISSUE TITLE
8卡 A100 40G，7B的FT，仍然CUDA oom，无法复现论文结果

### ISSUE THREAD

**Issue by crowningwang** [LianjiaTech/BELLE#329]
![image](https://user-images.githubusercontent.com/114406126/235091794-f52fb918-0061-4e16-b194-dd560566868f.png)

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/114406126/235091794-f52fb918-0061-4e16-b194-dd560566868f.png)

长度设置的多长
每张GPU上的batch是多少
麻烦提供下详细参数配置

对于Bloom模型，max_seq_len设置为512，每张显卡的batch_size设置为1，是可以跑起来的（8卡A100 40G ）

**Comment by crowningwang** [comment]
> 

您好，开zero3之后确实可以跑起来，但是每个epoch的速度会降低很多，而且对于2M的数据集，开zero3后mem1.8T也会溢出，根据论文的每个epoch的训练时间，应该没有开zero3，所以是因为max_seq_len的原因吗

**Comment by crowningwang** [comment]
> > ![图像](https://user-images.githubusercontent.com/114406126/235091794-f52fb918-0061-4e16-b194-dd560566868f.png)
> 
> 看您的参数配置，长度设置为1024 对Bloom模型，max_seq_len设置为512，每张显卡的batch_size设置为1，是可以跑起来的（8卡A100 40G） 另外如果显示存量不够，您应该把zero_stage设置为3个

您好，开zero3之后确实可以跑起来，但是每个epoch的速度会降低很多，而且对于2M的数据集，开zero3后mem1.8T也会溢出，根据论文的每个epoch的训练时间，应该没有开zero3，所以是因为max_seq_len的原因吗

**Comment by xianghuisun** [comment]
> > > ![图像](https://user-images.githubusercontent.com/114406126/235091794-f52fb918-0061-4e16-b194-dd560566868f.png)
> > 
> > 
> > 看您的参数配置，长度设置为1024 对Bloom模型，max_seq_len设置为512，每张显卡的batch_size设置为1，是可以跑起来的（8卡A100 40G） 另外如果显示存量不够，您应该把zero_stage设置为3个
> 
> 您好，开zero3之后确实可以跑起来，但是每个epoch的速度会降低很多，而且对于2M的数据集，开zero3后mem1.8T也会溢出，根据论文的每个epoch的训练时间，应该没有开zero3，所以是因为max_seq_len的原因吗

论文中的模型都是LLaMA啊

**Comment by Luoyingfeng8** [comment]
> > > > ![图像](https://user-images.githubusercontent.com/114406126/235091794-f52fb918-0061-4e16-b194-dd560566868f.png)
> > > 
> > > 
> > > 看您的参数配置，长度设置为1024 对Bloom模型，max_seq_len设置为512，每张显卡的batch_size设置为1，是可以跑起来的（8卡A100 40G） 另外如果显示存量不够，您应该把zero_stage设置为3个
> > 
> > 
> > 您好，开zero3之后确实可以跑起来，但是每个epoch的速度会降低很多，而且对于2M的数据集，开zero3后mem1.8T也会溢出，根据论文的每个epoch的训练时间，应该没有开zero3，所以是因为max_seq_len的原因吗
> 
> 论文中的模型都是LLaMA啊

同问，解决了吗
