### ISSUE TITLE
单机单卡用lora训练参数配置

### ISSUE THREAD

**Issue by nieallen** [LianjiaTech/BELLE#339]
单机单卡，如果选择only_optimize_lora，可以给一个run_LoRA.sh的参数配置吗？

**Comment by xianghuisun** [comment]
可参考：
https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning#%EF%B8%8F-some-arguments-explanation-and-the-largest-trainable-model

如果是Llama模型，对应的adapt参数可以是："q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj"
如果是Bloom模型，对应的adapt参数可以是：“query_key_value”

同时有：   
   --lora_dim 16 
   --lora_alpha 16 
   --lora_droppout 0.05

**Comment by nieallen** [comment]
> 可参考： https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning#%EF%B8%8F-some-arguments-explanation-and-the-largest-trainable-model
> 
> 如果是Llama模型，对应的adapt参数可以是："q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj" 如果是Bloom模型，对应的adapt参数可以是：“query_key_value”
> 
> 同时有： --lora_dim 16 --lora_alpha 16 --lora_droppout 0.05

谢谢，only_optimize_lora的话，好像无法调query_key_value参数。lora_dim高一些会不会更好？我试了128效果不错

**Comment by xianghuisun** [comment]
> > 可参考： https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning#%EF%B8%8F-some-arguments-explanation-and-the-largest-trainable-model
> > 如果是Llama模型，对应的adapt参数可以是："q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj" 如果是Bloom模型，对应的adapt参数可以是：“query_key_value”
> > 同时有： --lora_dim 16 --lora_alpha 16 --lora_droppout 0.05
> 
> 谢谢，only_optimize_lora的话，好像无法调query_key_value参数。lora_dim高一些会不会更好？我试了128效果不错

建议您用最新版v2版本代码，基于peft的
deepspeed-chat对参数高效微调这一块的可扩展性不高

**Comment by nieallen** [comment]
> > > 可参考： https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning#%EF%B8%8F-some-arguments-explanation-and-the-largest-trainable-model
> > > 如果是Llama模型，对应的adapt参数可以是："q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj" 如果是Bloom模型，对应的adapt参数可以是：“query_key_value”
> > > 同时有： --lora_dim 16 --lora_alpha 16 --lora_droppout 0.05
> > 
> > 
> > 谢谢，only_optimize_lora的话，好像无法调query_key_value参数。lora_dim高一些会不会更好？我试了128效果不错
> 
> 建议您用最新版v2版本代码，基于peft的 deepspeed-chat对参数高效微调这一块的可扩展性不高

谢谢，我试试
