### ISSUE TITLE
关于gradient_accumulation_steps 

### ISSUE THREAD

**Issue by nieallen** [LianjiaTech/BELLE#340]
请问，梯度累积设成1是为什么？可以大一些吗

**Comment by xianghuisun** [comment]
> 请问，梯度累积设成1是为什么？可以大一些吗

当然可以啊，但是也不需要太大。
加入你有8张卡，每张卡上的batch_size是2，那么相当于你总的batch_size是16
假如你想要batch_size是32，那么你的梯度累积就设置为2
