### ISSUE TITLE
使用大量数据做全量微调bloomz时，数据预处理阶段进程会突然被杀掉

### ISSUE THREAD

**Issue by scarydemon2** [LianjiaTech/BELLE#343]
![image](https://github.com/LianjiaTech/BELLE/assets/33051998/5f7a2dea-0978-4838-8810-37bf09172324)

8*V100，deepspeed zero3，跑小份数据可以正常跑起来，但是跑3M数据量时会出现这种情况，是否有哪些可能的原因，是否可能是内存小了

**Comment by scarydemon2** [comment]
是内存原因，跑2.7M数据量大概需要600G内存，才能跑起来

**Comment by LJL36** [comment]
@scarydemon2 大佬，您好，请问您用的是v1还是v2做训练？
