### ISSUE TITLE
想问下最新的代码支持多机多卡训练吗？

### ISSUE THREAD

**Issue by zhangyanbo2007** [LianjiaTech/BELLE#344]

**Comment by zhangyanbo2007** [comment]
torchrun --nproc_per_node 8 train.py \
    --model_name_or_path ${model_name_or_path} \
    --llama \
    --deepspeed configs/deepspeed_config.json \
    --train_file ${train_file} \
    --validation_file ${validation_file} \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --num_train_epochs 2 \
    --model_max_length ${cutoff_len} \
    --save_strategy "steps" \
    --save_total_limit 3 \
    --learning_rate 8e-6 \
    --weight_decay 0.00001 \
    --warmup_ratio 0.05 \
    --lr_scheduler_type "cosine" \
    --logging_steps 10 \
    --evaluation_strategy "steps" \
    --fp16 True \
    --seed 1234 \
    --gradient_checkpointing True \
    --cache_dir ${cache_dir} \
    --output_dir ${output_dir}

**Comment by zhangyanbo2007** [comment]
看着应该能支持

**Comment by xianghuisun** [comment]
多机训练的代码已提供

**Comment by etyhh** [comment]
多机训练报以下信息
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
然后一直没进度，cpu 占用 torchrun 只有 2%

最后报以下信息退出：
File "/home/xx/miniconda3/envs/belle/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 34, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout
