### ISSUE TITLE
请问如何基于BELLE-7B-0.2M使用自己的数据集进行微调啊？

### ISSUE THREAD

**Issue by Colapls** [LianjiaTech/BELLE#352]
mkdir /path/to_finetuned_model
for f in "/path/to_encrypted"/*; \
    do if [ -f "$f" ]; then \
       python3 decrypt.py "$f" "/path/to_original_llama_7B/consolidated.00.pth" "/path/to_finetuned_model/"; \
    fi; \
done

下载的llama_7B模型里也没有pth文件啊，只有33个bin文件，请问怎么进行模型合并呢？

**Comment by xianghuisun** [comment]
> mkdir /path/to_finetuned_model for f in "/path/to_encrypted"/*; do if [ -f "$f" ]; then python3 decrypt.py "$f" "/path/to_original_llama_7B/consolidated.00.pth" "/path/to_finetuned_model/"; fi; done
> 
> 下载的llama_7B模型里也没有pth文件啊，只有33个bin文件，请问怎么进行模型合并呢？

您从哪里下载的llama模型
