### ISSUE TITLE
语料生成相关

### ISSUE THREAD

**Issue by ZenXir** [LianjiaTech/BELLE#36]
有两点没明白，麻烦大佬老师帮解释下吧：
1、为什么需要种子任务 zh_seed_tasks.json？
种子任务的作用是什么？

2、生成数据时

　　pip install -r requirements.txt
	export OPENAI_API_KEY=YOUR_API_KEY
	python generate_instruction.py generate_instruction_following_data
最后的这个参数 generate_instruction_following_data 是什么大佬老师？ 是表示生成数据的存储文件吗？
非常感谢大佬老师

**Comment by bestpredicts** [comment]
种子的作用主要是利用in context learning的方法，让chatgpt生成更多的指令数据。generate_instruction_following_data是里面生产数据的函数。
