### ISSUE TITLE
请问 BLOOM 版的 BELLE 模型是否可用于商业用途？

### ISSUE THREAD

**Issue by PenutChen** [LianjiaTech/BELLE#362]
请问 [BELLE-7B-2M](https://huggingface.co/BelleGroup/BELLE-7B-2M) 等 BLOOM 系列的模型是否可商用？

[局限性、使用限制与免责声明](https://github.com/LianjiaTech/BELLE#%EF%B8%8F-%E5%B1%80%E9%99%90%E6%80%A7%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6%E4%B8%8E%E5%85%8D%E8%B4%A3%E5%A3%B0%E6%98%8E)章节的声明是否也适用于此项目释出的 BLOOM 权重？

因为 BELLE-7B-2M 挂的是 Apache 2.0 的授权，但项目底下又有不可用于商业用途的声明，所以想确认一下

**Comment by xianghuisun** [comment]
> 请问 [BELLE-7B-2M](https://huggingface.co/BelleGroup/BELLE-7B-2M) 等 BLOOM 系列的模型是否可商用？
> 
> [局限性、使用限制与免责声明](https://github.com/LianjiaTech/BELLE#%EF%B8%8F-%E5%B1%80%E9%99%90%E6%80%A7%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6%E4%B8%8E%E5%85%8D%E8%B4%A3%E5%A3%B0%E6%98%8E)章节的声明是否也适用于此项目释出的 BLOOM 权重？
> 
> 因为 BELLE-7B-2M 挂的是 Apache 2.0 的授权，但项目底下又有不可用于商业用途的声明，所以想确认一下

遵循bloom的协议即可
