### ISSUE TITLE
请问有多少人复现成功了,你们的环境都是什么?一起来说说啊,

### ISSUE THREAD

**Issue by chentiao** [LianjiaTech/BELLE#363]

**Comment by uuser0748** [comment]
就用他提供的容器，两块A100 80G。全量ft跑通，但是lora不行

**Comment by Kkkkkiradd** [comment]
> 就用他提供的容器，两块A100 80G。全量ft跑通，但是lora不行

请问您用的数据多大呀，大概跑了多久

**Comment by uuser0748** [comment]
> > 就用他提供的容器，两块A100 80G。全量ft跑通，但是lora不行
> 
> 请问您用的数据多大呀，大概跑了多久

数据不大，就300KB的对话文件。跑20个epoch我看loss就已经不错了，时间没注意看，可能有十几个小时。啊对了而且是单卡跑的，他的多卡代码有问题

**Comment by xianghuisun** [comment]
> 

请问多卡的代码哪里有问题，我们好解决。

**Comment by uuser0748** [comment]
> > 
> 
> 请问多卡的代码哪里有问题，我们好解决。

finetune多卡的时候，应该是world_size没有生效，会报一个dimension不匹配的问题

**Comment by xianghuisun** [comment]
> > > 
> > 
> > 
> > 请问多卡的代码哪里有问题，我们好解决。
> 
> finetune多卡的时候，应该是world_size没有生效，会报一个dimension不匹配的问题

transformers版本问题吧
