### ISSUE TITLE
13B模型转换

### ISSUE THREAD

**Issue by huangqingyi-code** [LianjiaTech/BELLE#368]
hi,
BelleGroup/BELLE-LLaMA-EXT-13B模型转换，我看huggingface上转换用的原始llama模型是用7B的模型"/path/to_original_llama_7B/consolidated.00.pth"？
不是应该用13B的么？但是13B的原始llama权重有两个文件consolidated.00.pth，consolidated.01.pth，要用哪一个，怎么用？。以上问题帮忙回复下

**Comment by aimetrics** [comment]
> hi, BelleGroup/BELLE-LLaMA-EXT-13B模型转换，我看huggingface上转换用的原始llama模型是用7B的模型"/path/to_original_llama_7B/consolidated.00.pth"？ 不是应该用13B的么？但是13B的原始llama权重有两个文件consolidated.00.pth，consolidated.01.pth，要用哪一个，怎么用？。以上问题帮忙回复下

我昨天也有此疑问，看了decrypt代码：
key_file文件的目的是用来和BelleGroup/BELLE-LLaMA-EXT-13B做XOR的。因为官方用/path/to_original_llama_7B/consolidated.00.pth来做XOR加密，那么解密时，也需要用同样的/path/to_original_llama_7B/consolidated.00.pth文件。
