### ISSUE TITLE
希望我们可以取得联系

### ISSUE THREAD

**Issue by Evani300** [LianjiaTech/BELLE#37]
我目前在一家早期创投任职，我在浏览GitHub开源社区了解到Belle特别希望能够有机会与您的团队取得联系！Belle是一个开源中文对话大模型可以用于创建定制的聊天机器人（chatbot，在有些场景要比开放式的语言生成模型或许会更加合适。因为完全开源的原因是可以去为企业提供一个自定义程度高于gpt的一个聊天机器人。您在项目中做出的贡献我们表示非常激动且想与您共同探讨任何潜在的商业化落地的可能性！这是我的微信：c13559870609

**Comment by tjadamlee** [comment]
感谢关注
