### ISSUE TITLE
用lora模式训练出的模型缺少adapter_model.bin和adapter_config.json

### ISSUE THREAD

**Issue by deeplearningSprint** [LianjiaTech/BELLE#370]
您好，我用scripts/run.sh中的lora部分，finetune出的模型缺少两个文件，输出的文件如下：

![image](https://github.com/LianjiaTech/BELLE/assets/13288654/539e54cb-d2d0-465b-87fa-a5c8abad5078)

请问该如何解决？

谢谢！

**Comment by nghuyong** [comment]
+1
另外readme中lora训练的学习率为8e-6是正常的吗？

**Comment by xianghuisun** [comment]
> 您好，我用scripts/run.sh中的lora部分，finetune出的模型缺少两个文件，输出的文件如下：
> 
> ![image](https://user-images.githubusercontent.com/13288654/239125462-539e54cb-d2d0-465b-87fa-a5c8abad5078.png)
> 
> 请问该如何解决？
> 
> 谢谢！

请问checkpoint-step下有adapter_config.json文件嘛

**Comment by nghuyong** [comment]
没有，checkpoint-step下面的文件如下：

```
total 92385
-rw-r--r-- 1 root root 62950085 May 18 11:46 optimizer.pt
-rw-r--r-- 1 root root 31479589 May 18 11:46 pytorch_model.bin
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_0.pth
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_1.pth
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_2.pth
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_3.pth
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_4.pth
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_5.pth
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_6.pth
-rw-r--r-- 1 root root    14583 May 18 11:46 rng_state_7.pth
-rw-r--r-- 1 root root      557 May 18 11:46 scaler.pt
-rw-r--r-- 1 root root      627 May 18 11:46 scheduler.pt
-rw-r--r-- 1 root root    46417 May 18 11:46 trainer_state.json
-rw-r--r-- 1 root root     3707 May 18 11:46 training_args.bin
```

**Comment by Kkkkkiradd** [comment]
> > 您好，我用scripts/run.sh中的lora部分，finetune出的模型缺少两个文件，输出的文件如下：
> > ![image](https://user-images.githubusercontent.com/13288654/239125462-539e54cb-d2d0-465b-87fa-a5c8abad5078.png)
> > 请问该如何解决？
> > 谢谢！
> 
> 请问checkpoint-step下有adapter_config.json文件嘛

我也遇到了相同的问题，缺少adapter_config.json，求解答

**Comment by mynewstart** [comment]
+1

**Comment by nieallen** [comment]
> > > 您好，我用scripts/run.sh中的lora部分，finetune出的模型缺少两个文件，输出的文件如下：
> > > ![image](https://user-images.githubusercontent.com/13288654/239125462-539e54cb-d2d0-465b-87fa-a5c8abad5078.png)
> > > 请问该如何解决？
> > > 谢谢！
> > 
> > 
> > 请问checkpoint-step下有adapter_config.json文件嘛
> 
> 我也遇到了相同的问题，缺少adapter_config.json，求解答

我也，解决了吗？

**Comment by xianghuisun** [comment]
> 您好，我用scripts/run.sh中的lora部分，finetune出的模型缺少两个文件，输出的文件如下：
> 
> ![image](https://user-images.githubusercontent.com/13288654/239125462-539e54cb-d2d0-465b-87fa-a5c8abad5078.png)
> 
> 请问该如何解决？
> 
> 谢谢！

训练结束后需要使用model.save_pretrained()方法才能保存 adapter_config和adapter_model
代码已修改。

**Comment by xianghuisun** [comment]
> 您好，我用scripts/run.sh中的lora部分，finetune出的模型缺少两个文件，输出的文件如下：
> 
> ![image](https://user-images.githubusercontent.com/13288654/239125462-539e54cb-d2d0-465b-87fa-a5c8abad5078.png)
> 
> 请问该如何解决？
> 
> 谢谢！

训练结束后需要使用model.save_pretrained()方法才能保存 adapter_config和adapter_model
代码已修改。
