### ISSUE TITLE
使用0.5M的指令数据进行微调时，总报OutOfMemory错误

### ISSUE THREAD

**Issue by xfg0913** [LianjiaTech/BELLE#375]
使用8块A100 40G进行微调，报如下错误：
 deepspeed --num_gpus=8 finetune.py --model_config_file run_config/Llama_config.json  --deepspeed run_config/deepspeed_config.json
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 39.45 GiB total capacity; 36.72 GiB already allocated; 10.31 MiB free; 37.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF。
哪位大佬能帮忙定位、分析下问题

**Comment by xianghuisun** [comment]
您使用的代码应该还是旧版本代码。
您应该基于仓库目前最新版的代码进行实验

**Comment by xfg0913** [comment]
> 您使用的代码应该还是旧版本代码。 您应该基于仓库目前最新版的代码进行实验

好的，非常谢谢。我试一下。
