### ISSUE TITLE
[BUG]运行的时候提示缺失mpi4py

### ISSUE THREAD

**Issue by woshicqy** [LianjiaTech/BELLE#378]
![image](https://github.com/LianjiaTech/BELLE/assets/38115801/584e951f-476c-47ae-8d04-79013d88def7)
如上图，想请问一下，作者用的是什么版本的python，我目前用的3.10.0，然后配置环境的packages都成功安装了。运行的train.py的时候会报上图错误。我的操作系统是wsl的ubuntu 20.0

**Comment by xianghuisun** [comment]
> ![image](https://user-images.githubusercontent.com/38115801/239655866-584e951f-476c-47ae-8d04-79013d88def7.png) 如上图，想请问一下，作者用的是什么版本的python，我目前用的3.10.0，然后配置环境的packages都成功安装了。运行的train.py的时候会报上图错误。我的操作系统是wsl的ubuntu 20.0

看样子应该是deepspeed运行出现的问题.
您可尝试pip install mpi4py， 如果不能安装，建议您使用我们提供的docker环境
