### ISSUE TITLE
Finetuning bloom with stanford_alpaca repo problem

### ISSUE THREAD

**Issue by raihan0824** [LianjiaTech/BELLE#38]
In the https://github.com/LianjiaTech/BELLE/issues/26 it said that the finetuning script is from the [stanford_alpaca](https://github.com/tatsu-lab/stanford_alpaca). I want to ask a simple question:
What is the `fsdp_transformer_layer_cls_to_wrap` for bloom?

When I tried to fine tune with bloomz-7b1, the training stuck on 0%. And it's most likely because I dont set the right `fsdp_transformer_layer_cls_to_wrap` . But I cant find it in the bloom config.

Kindly need a help on this.
Thank you

**Comment by barius** [comment]
The finetuning is done on a seperate repo we haven't released yet. Hopefully it will get released soon :)
