### ISSUE TITLE
采用BelleGroup/BELLE-LLaMA-EXT-13B模型，在A100 40G的GPU上推理，时长特别长，需要10几分钟

### ISSUE THREAD

**Issue by xfg0913** [LianjiaTech/BELLE#380]
在A100 40G的GPU上运行BELLE的示例代码，采用BELLE-LLaMA-EXT-13B模型，推理时长特别长，需要10几分钟。为什么？哪些参数需要优化？请大佬指点下。

from transformers import LlamaForCausalLM, AutoTokenizer
import torch

ckpt = '/path/to_finetuned_model/'
device = torch.device('cuda')
model = LlamaForCausalLM.from_pretrained(ckpt, device_map='auto', low_cpu_mem_usage=True)
tokenizer = AutoTokenizer.from_pretrained(ckpt)
prompt = "Human: 写一首中文歌曲，赞美大自然 \n\nBelle: "
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)
generate_ids = model.generate(input_ids, max_new_tokens=300, do_sample = True, top_k = 30, top_p = 0.85, temperature = 0.5，repetition_penalty=1.2, eos_token_id=2, bos_token_id=1, pad_token_id=0)
output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
response = output[len(prompt):]
print(response)

**Comment by peterzhang2029** [comment]
遇到同样的问题，蹲一下

**Comment by lucasjinreal** [comment]
你的格式可能不对，仔细看训练的时候template，BELLE现在的模板时这样的：

```
Human: \nxxxx\n\nAssistant: \n
```
模板不对会导致对话无法停下来。

**Comment by Jcorners** [comment]
主要是由于tokenizer = AutoTokenizer.from_pretrained(ckpt)造成的，默认是tokenizerFast；普通的tokenizer转成fast在我这需18分钟左右。
修改成tokenizer = LlamaTokenizer.from_pretrained(ckpt)就会很快了。

**Comment by xfg0913** [comment]
> 主要是由于tokenizer = AutoTokenizer.from_pretrained(ckpt)造成的，默认是tokenizerFast；普通的tokenizer转成fast在我这需18分钟左右。 修改成tokenizer = LlamaTokenizer.from_pretrained(ckpt)就会很快了。

用您说的方法解决了。非常感谢！

**Comment by xfg0913** [comment]
> 你的格式可能不对，仔细看训练的时候template，BELLE现在的模板时这样的：
> 
> ```
> Human: \nxxxx\n\nAssistant: \n
> ```
> 
> 模板不对会导致对话无法停下来。

非常感谢！
