### ISSUE TITLE
model.generate 特别慢

### ISSUE THREAD

**Issue by peterzhang2029** [LianjiaTech/BELLE#382]
belle 13B的model 例子中的 generate_ids = model.generate(input_ids, max_new_tokens=100)这一行跑的特别慢是咋回事呢？ 显卡利用率在50%左右，max_new_tokens如果设置为10可以秒出，设置为100就慢的不行不行的，像是永远出不来结果一样

**Comment by cocaer** [comment]
可以尝试合并lora
```python
base_model = AutoModelForCausalLM.from_pretrained(args.model_name_or_path, load_in_8bit=False, device_map="auto", torch_dtype=torch.float16)
        
model = PeftModel.from_pretrained(base_model, args.ckpt_path, torch_dtype=load_type)
model = model.merge_and_unload()
```
Refs：
https://github.com/huggingface/peft/issues/303

**Comment by xianghuisun** [comment]
> belle 13B的model 例子中的 generate_ids = model.generate(input_ids, max_new_tokens=100)这一行跑的特别慢是咋回事呢？ 显卡利用率在50%左右，max_new_tokens如果设置为10可以秒出，设置为100就慢的不行不行的，像是永远出不来结果一样

推理时不要用8bit量化去加载模型，速度会很慢

**Comment by xianghuisun** [comment]
> belle 13B的model 例子中的 generate_ids = model.generate(input_ids, max_new_tokens=100)这一行跑的特别慢是咋回事呢？ 显卡利用率在50%左右，max_new_tokens如果设置为10可以秒出，设置为100就慢的不行不行的，像是永远出不来结果一样

8bit量化加载后，显存占用小，但是利用率低，推理速度慢

**Comment by kevinuserdd** [comment]
> > belle 13B的model 例子中的 generate_ids = model.generate(input_ids, max_new_tokens=100)这一行跑的特别慢是咋回事呢？ 显卡利用率在50%左右，max_new_tokens如果设置为10可以秒出，设置为100就慢的不行不行的，像是永远出不来结果一样
> 
> 8bit量化加载后，显存占用小，但是利用率低，推理速度慢

推理不用8bit加载，但是65b的模型微调后推理单卡会oom。。。

**Comment by SunriseB** [comment]
我用微调后的phi2模型，在A100上推理，参数2B，max_new_token设置成1000得等30s左右，按理来说A100跑这么小的模型是不是不应该这么慢呢？

**Comment by SunriseB** [comment]
> 我用微调后的phi2模型，在A100上推理，参数2B，max_new_tokens设置成1000得等30s左右（同样是max_new_tokens越小时间越短），按理来说A100跑这么小的模型是不是不应该这么慢呢？

我想到一个解决方法不知道是否可行：因为实际上我根本不需要生成1000token这么多，能不能使模型自动停止输出，或者设置什么参数当模型response生成完毕后自动停止，而不是非要达到max_new_tokens后才停止输出呢？

**Comment by KevinViko** [comment]
> > 我用微调后的phi2模型，在A100上推理，参数2B，max_new_tokens设置成1000得等30s左右（同样是max_new_tokens越小时间越短），按理来说A100跑这么小的模型是不是不应该这么慢呢？
> 
> 我想到一个解决方法不知道是否可行：因为实际上我根本不需要生成1000token这么多，能不能使模型自动停止输出，或者设置什么参数当模型response生成完毕后自动停止，而不是非要达到max_new_tokens后才停止输出呢？

您好，请问您解决这个推理速度过慢的问题了吗？
