### ISSUE TITLE
RuntimeError: probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by Jingkustc** [LianjiaTech/BELLE#386]
### error
Traceback (most recent call last):
  File "BELLE/train/src/inference.py", line 68, in <module>
    generation_output = model.generate(
                        ^^^^^^^^^^^^^^^
  File "/home/.conda/envs/user/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/user/lib/python3.11/site-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/home/.conda/envs/user/lib/python3.11/site-packages/transformers/generation/utils.py", line 2648, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### cmd
inference.sh
```
#! /bin/bash

model_name_or_path=belle_ext_13b/

python BELLE/train/src/inference.py \
    --model_name_or_path ${model_name_or_path} \
    --ckpt_path ${model_name_or_path} \
    --llama \
```

### model weights
download the weight from https://huggingface.co/BelleGroup/BELLE-LLaMA-EXT-13B
convert the weight following the instructions from the above URL
check md5sum of the decrypted files, and ensure the complete recovery.

### environment
GPU: 1*A100
python==3.11.3
pytorch==2.0.1 (py3.11_cuda11.7_cudnn8.5.0_0)
transformers==4.29.1
cuda==11.7

**Comment by nieallen** [comment]
same error，how to solve it?

**Comment by xianghuisun** [comment]
> 

You can try other models. If there are no errors, it indicates an issue with weight conversion for the model.
Moreover, when loading the model, you may also try torch.float16 or torch.float32, as this error seems to be caused by numerical precision.

**Comment by Jingkustc** [comment]
> > 
> 
> You can try other models. If there are no errors, it indicates an issue with weight conversion for the model. Moreover, when loading the model, you may also try torch.float16 or torch.float32, as this error seems to be caused by numerical precision.

I run the script again without changing anything, and it runs well. Though the instability of the script may caused by some reason, I'm going to close this issue. Thanks a lot!

**Comment by swizzcheeze** [comment]
try running in 8-bit worked for me vs when trying in 4-bit got the same issues with mlabonne_phixtral-2x2_8....8-bit solved the nan, inf error
