### ISSUE TITLE
expected scalar type Half but found Float

### ISSUE THREAD

**Issue by zgu293** [LianjiaTech/BELLE#389]
@xianghuisun 您好，着急请教您一个问题。
我的GPU是p40 Tesla。我基于bloom, 运行命令如下：
# #LoRA
torchrun --nproc_per_node 2 src/train.py \
    --model_name_or_path ${model_name_or_path} \
    --use_lora True \
    --use_int8_training \
    --lora_config configs/lora_config_bloom.json \
    --train_file ${train_file} \
    --validation_file ${validation_file} \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --num_train_epochs 2 \
    --model_max_length ${cutoff_len} \
    --save_strategy "steps" \
    --save_total_limit 3 \
    --learning_rate 8e-6 \
    --weight_decay 0.00001 \
    --warmup_ratio 0.05 \
    --lr_scheduler_type "cosine" \
    --logging_steps 10 \
    --evaluation_strategy "steps" \
    --fp16 True \
    --seed 1234 \
    --gradient_checkpointing True \
    --cache_dir ${cache_dir} \
    --output_dir ${output_dir}

这样运行会出现“RuntimeError: expected scalar type Half but found Float”
我把fp16改为false之后，错误没有了，但是loss第二次打印就降为0了，麻烦您帮忙看一下如何解决，感激不尽
{'loss': 86.4136, 'learning_rate': 5.1746442432082797e-08, 'epoch': 0.0}                                                                     
{'loss': 0.0, 'learning_rate': 1.0349288486416559e-07, 'epoch': 0.0}                                                                         
{'loss': 0.0, 'learning_rate': 1.5523932729624837e-07, 'epoch': 0.0}                                                                         
{'loss': 0.0, 'learning_rate': 2.0698576972833119e-07, 'epoch': 0.0}                                                                         
{'loss': 0.0, 'learning_rate': 2.58732212160414e-07, 'epoch': 0.0}                                                                           
{'loss': 0.0, 'learning_rate': 3.1047865459249674e-07, 'epoch': 0.0}                                                                         
{'loss': 0.0, 'learning_rate': 3.6222509702457956e-07, 'epoch': 0.0}                                                                         
{'loss': 0.0, 'learning_rate': 4.1397153945666237e-07, 'epoch': 0.01}                                                                        
{'loss': 0.0, 'learning_rate': 4.6571798188874514e-07, 'epoch': 0.01}                                                                        
{'loss': 0.0, 'learning_rate': 5.17464424320828e-07, 'epoch': 0.01}                                                                          
{'loss': 0.0, 'learning_rate': 5.692108667529108e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 6.209573091849935e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 6.727037516170763e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 7.244501940491591e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 7.761966364812419e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 8.279430789133247e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 8.796895213454075e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 9.314359637774903e-07, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 9.83182406209573e-07, 'epoch': 0.01}                                                                          
{'loss': 0.0, 'learning_rate': 1.034928848641656e-06, 'epoch': 0.01}                                                                         
{'loss': 0.0, 'learning_rate': 1.0866752910737386e-06, 'epoch': 0.01}

**Comment by zgu293** [comment]
然后我换成v100，还是有这个问题

**Comment by xianghuisun** [comment]
> 然后我换成v100，还是有这个问题

您好，V100上8bit量化训练loss不正常的问题，可参考：

https://github.com/Facico/Chinese-Vicuna/issues/39
https://github.com/TimDettmers/bitsandbytes/issues/100
https://github.com/mymusise/ChatGLM-Tuning/issues/19
https://github.com/tloen/alpaca-lora/issues/170

**Comment by xianghuisun** [comment]
> > 然后我换成v100，还是有这个问题
> 
> 您好，V100上8bit量化训练loss不正常的问题，可参考：
> 
> [Facico/Chinese-Vicuna#39](https://github.com/Facico/Chinese-Vicuna/issues/39) [TimDettmers/bitsandbytes#100](https://github.com/TimDettmers/bitsandbytes/issues/100) [mymusise/ChatGLM-Tuning#19](https://github.com/mymusise/ChatGLM-Tuning/issues/19) [tloen/alpaca-lora#170](https://github.com/tloen/alpaca-lora/issues/170)

希望这些解决方案能帮到您

**Comment by zgu293** [comment]
> > 然后我换成v100，还是有这个问题
> 
> 您好，V100上8bit量化训练loss不正常的问题，可参考：
> 
> [Facico/Chinese-Vicuna#39](https://github.com/Facico/Chinese-Vicuna/issues/39) [TimDettmers/bitsandbytes#100](https://github.com/TimDettmers/bitsandbytes/issues/100) [mymusise/ChatGLM-Tuning#19](https://github.com/mymusise/ChatGLM-Tuning/issues/19) [tloen/alpaca-lora#170](https://github.com/tloen/alpaca-lora/issues/170)

您好，特别感谢您的耐心指导。问题已经解决
