### ISSUE TITLE
关于数据集描述的问题

### ISSUE THREAD

**Issue by BowieHsu** [LianjiaTech/BELLE#4]
您好，我下载了数据集之后看到json内容的描述是"input"和"target"，stanford中的是"instruction"/"input"/"output"，我想请教一下这里"input"送训练的时候会用//n来分成"instruction"和“input”吗，还是你们默认"input"就是“instruction”

**Comment by Life-0-1** [comment]
我们发布的数据可以直接用于训练模型，无需其他处理。
你的理解是对的，input就是instruction，target就是对应的模型response.

**Comment by BowieHsu** [comment]
@Life-0-1 好的，感谢您的解答。
