### ISSUE TITLE
请问如何加载呢

### ISSUE THREAD

**Issue by caopeng000** [LianjiaTech/BELLE#40]
https://github.com/cocktailpeanut/dalai 基于斯坦福的我运行起来了，windows环境。是通过npx dalai serve运行起来的。请问作者您这个是如何运行的呢，pip install -r requirements.txt
export OPENAI_API_KEY=YOUR_API_KEY
python generate_instruction.py generate_instruction_following_data都运行了。下一步不知道该如何操作了

**Comment by bestpredicts** [comment]
generate_instruction.py 是用来生产数据的。 如果模型推理的话，参考huggingface 里面模型推理的代码[Belle Group](https://huggingface.co/BelleGroup/BELLE-7B-2M)

**Comment by ddzz0210** [comment]
请问你运行起来了吗
