### ISSUE TITLE
loss曲线

### ISSUE THREAD

**Issue by ftgreat** [LianjiaTech/BELLE#400]
请问您sft训练时曲线形状是怎样的？训练多个epochs时，每个epoch的loss大概什么变化趋势，谢谢。

**Comment by xianghuisun** [comment]
> 请问您sft训练时曲线形状是怎样的？训练多个epochs时，每个epoch的loss大概什么变化趋势，谢谢。

您可基于开源代码实际训练下，tensorboard位置在模型保存路径的runs目录下
