### ISSUE TITLE
感觉BELLE-LLaMA-EXT-13B效果比之前13B的差

### ISSUE THREAD

**Issue by cxfzzj** [LianjiaTech/BELLE#408]
对比之前放出的13B模型，感觉扩大中文词典的BELLE-LLaMA-EXT-13B的效果更差，不知道是不是我测试的问题，想咨询一下专业人士

**Comment by a2012456373** [comment]
可能是 你的问题，我这里测试基本跟chatgpt差不多了

**Comment by cxfzzj** [comment]
我的基本参数设置为：max_new_tokens=2048,do_sample=True,top_k=50,top_p=0.9,temperature=0.2,repetition_penalty=1.3;
之前也换了其他的参数，但是感觉性能就是提不上来。你能分享一下你设置的参数吗
![9f7340cd13cf2efaa6a2c0d2f74890b](https://github.com/LianjiaTech/BELLE/assets/25788997/66388b90-338f-4438-b3c6-836daa693eea)

**Comment by cxfzzj** [comment]
> 可能是 你的问题，我这里测试基本跟chatgpt差不多了
我的基本参数设置为：max_new_tokens=2048,do_sample=True,top_k=50,top_p=0.9,temperature=0.2,repetition_penalty=1.3;
之前也换了其他的参数，但是感觉性能就是提不上来。你能分享一下你设置的参数吗

**Comment by cxfzzj** [comment]
你好，我在github的真问题上贴了我的参数设置，你能分享一下你的参数吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月30日(星期二) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LianjiaTech/BELLE] 感觉BELLE-LLaMA-EXT-13B效果比之前13B的差 (Issue #408)





 
可能是 你的问题，我这里测试基本跟chatgpt差不多了

**Comment by a2012456373** [comment]
num_beams=1,do_sample=True, top_p=0.9, temperature=0.95, repetition_penalty=1.05

**Comment by cxfzzj** [comment]
试了一下你给的参数，但是很不幸，我的模型还是在乱回答，是我解码的模型有问题吗？

**Comment by Malestudents** [comment]
大佬，官方的模型需要解密，但是依赖llama加密原版，这没申请下来，大家那有其他解密后的吗
