### ISSUE TITLE
执行报错！

### ISSUE THREAD

**Issue by StarRanger** [LianjiaTech/BELLE#41]
按照 
pip install -r requirements.txt
export OPENAI_API_KEY=xxxx
python generate_instruction.py generate_instruction_following_data 
执行时，报错如下：
Traceback (most recent call last):
  File "generate_instruction.py", line 22, in <module>
    import utils
  File "/Users/caizhongxiang/Research/llm/BELLE/utils.py", line 48, in <module>
    return_text=False,
TypeError: 'type' object is not subscriptable
操作系统是maxOS Catalina 10.15.7 
python安装版本是3.7 
requirements.txt 里面的均已安装成功。pycharm本身没有提示版本上的问题。
求助~

**Comment by bestpredicts** [comment]
> 按照 pip install -r requirements.txt export OPENAI_API_KEY=xxxx python generate_instruction.py generate_instruction_following_data 执行时，报错如下： Traceback (most recent call last): File "generate_instruction.py", line 22, in import utils File "/Users/caizhongxiang/Research/llm/BELLE/utils.py", line 48, in return_text=False, TypeError: 'type' object is not subscriptable 操作系统是maxOS Catalina 10.15.7 python安装版本是3.7 requirements.txt 里面的均已安装成功。pycharm本身没有提示版本上的问题。 求助~

相同的问题见 #11
