### ISSUE TITLE
prompt_eval.py进行推理时出现RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by Flywolfs** [LianjiaTech/BELLE#412]
如题，我使用BELLE/train/dschat_train_v1中的方法进行了全参数SFT，数据使用为belle-math-0.25M。
SFT过程很顺利，但是使用生成脚本：
CUDA_VISIBLE_DEVICES=0 python prompt_eval.py \
    --model_name_or_path model_name_or_path \
    --finetuned_model_name_or_path finetuned_model_name_or_path \
    --test_file test_file_name_or_path
之后，会在某些测试样例中报错：**RuntimeError: probability tensor contains either `inf`, `nan` or element < 0**。删除掉那个报错case以后，其他case也有可能报这个错误。测试样例即按照教程将belle-math-0.25M分出来1k个作为eval set。
刚开始怀疑是环境问题造成，但是我用官方的docker也会在同样的case出同样的问题，因此环境问题排除。
现在就不知道是什么原因导致的这个问题产生。还请大神们帮帮忙~

**Comment by Flywolfs** [comment]
> 如题，我使用BELLE/train/dschat_train_v1中的方法进行了全参数SFT，数据使用为belle-math-0.25M。 SFT过程很顺利，但是使用生成脚本： CUDA_VISIBLE_DEVICES=0 python prompt_eval.py --model_name_or_path model_name_or_path --finetuned_model_name_or_path finetuned_model_name_or_path --test_file test_file_name_or_path 之后，会在某些测试样例中报错：**RuntimeError: probability tensor contains either `inf`, `nan` or element < 0**。删除掉那个报错case以后，其他case也有可能报这个错误。测试样例即按照教程将belle-math-0.25M分出来1k个作为eval set。 刚开始怀疑是环境问题造成，但是我用官方的docker也会在同样的case出同样的问题，因此环境问题排除。 现在就不知道是什么原因导致的这个问题产生。还请大神们帮帮忙~

原因找到了，是因为prompt_eval.py在main函数下定义了load_type = torch.float16，查阅了一些资料说，float16有时会造成这样的问题。但是为什么float16就会有这样的问题呢？

**Comment by xianghuisun** [comment]
> > 如题，我使用BELLE/train/dschat_train_v1中的方法进行了全参数SFT，数据使用为belle-math-0.25M。 SFT过程很顺利，但是使用生成脚本： CUDA_VISIBLE_DEVICES=0 python prompt_eval.py --model_name_or_path model_name_or_path --finetuned_model_name_or_path finetuned_model_name_or_path --test_file test_file_name_or_path 之后，会在某些测试样例中报错：**RuntimeError: probability tensor contains either `inf`, `nan` or element < 0**。删除掉那个报错case以后，其他case也有可能报这个错误。测试样例即按照教程将belle-math-0.25M分出来1k个作为eval set。 刚开始怀疑是环境问题造成，但是我用官方的docker也会在同样的case出同样的问题，因此环境问题排除。 现在就不知道是什么原因导致的这个问题产生。还请大神们帮帮忙~
> 
> 原因找到了，是因为prompt_eval.py在main函数下定义了load_type = torch.float16，查阅了一些资料说，float16有时会造成这样的问题。但是为什么float16就会有这样的问题呢？

训练的模型是bloomz-560m嘛？
bloomz-560m确实会出现这样的问题

**Comment by smile-II** [comment]
> > 如题，我使用BELLE/train/dschat_train_v1中的方法进行了全参数SFT，数据使用为belle-math-0.25M。 SFT过程很顺利，但是使用生成脚本： CUDA_VISIBLE_DEVICES=0 python prompt_eval.py --model_name_or_path model_name_or_path --finetuned_model_name_or_path finetuned_model_name_or_path --test_file test_file_name_or_path 之后，会在某些测试样例中报错：**RuntimeError: probability tensor contains either `inf`, `nan` or element < 0**。删除掉那个报错case以后，其他case也有可能报这个错误。测试样例即按照教程将belle-math-0.25M分出来1k个作为eval set。 刚开始怀疑是环境问题造成，但是我用官方的docker也会在同样的case出同样的问题，因此环境问题排除。 现在就不知道是什么原因导致的这个问题产生。还请大神们帮帮忙~
> 
> 原因找到了，是因为prompt_eval.py在main函数下定义了load_type = torch.float16，查阅了一些资料说，float16有时会造成这样的问题。但是为什么float16就会有这样的问题呢？

请问最后怎么解决的，我定义用bf16加载，然后会报错 expected scalar type BFloat16 but found Float
