### ISSUE TITLE
deepspeed冲突的原因

### ISSUE THREAD

**Issue by kevinuserdd** [LianjiaTech/BELLE#422]
LoRA训练如果采用8bit量化，就不能使用deepspeed；如果使用deepspeed，就不能指定use_int8_training

请问使用8bit量化就不能使用deepspeed的原因是什么？ 有什么专业的解释吗

**Comment by xianghuisun** [comment]
> LoRA训练如果采用8bit量化，就不能使用deepspeed；如果使用deepspeed，就不能指定use_int8_training
> 
> 请问使用8bit量化就不能使用deepspeed的原因是什么？ 有什么专业的解释吗

实验发现，同时指定会出现如下error：
RuntimeError: expected scalar type Float but found Half
