### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wuguangshuo** [LianjiaTech/BELLE#428]
BelleGroup/BELLE-LLaMA-13B-2M-enc加载tokenizer时报错RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by xianghuisun** [comment]
> BelleGroup/BELLE-LLaMA-13B-2M-enc加载tokenizer时报错RecursionError: maximum recursion depth exceeded while calling a Python object

应该是tokenizers版本的问题，您可尝试用LlamaTokenizer加载

**Comment by wuguangshuo** [comment]
已解决，换成LlamaTokenizer就可以了&nbsp;


吴广硕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月8日(星期四) 中午11:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LianjiaTech/BELLE] 问题 (Issue #428)





  
BelleGroup/BELLE-LLaMA-13B-2M-enc加载tokenizer时报错RecursionError: maximum recursion depth exceeded while calling a Python object
  
应该是tokenizers版本的问题，您可尝试用LlamaTokenizer加载
