### ISSUE TITLE
BELLE-LLaMA-7B-2M-enc和BELLE-7B-0.2M有没有经过34亿token中文语料二次pre-train？

### ISSUE THREAD

**Issue by gulegeji** [LianjiaTech/BELLE#429]
如题，这两个模型是直接在llama上用2M和0.2M指令微调的？还是经过二次pre-train了

**Comment by jinzijian** [comment]
同问

**Comment by jinzijian** [comment]
Extending the vocabulary with additional 50K tokens specific for Chinese and further pretraining these word embeddings on Chinese corpus.
Full-parameter finetuning the model with 4M high-quality instruction-following examples. 应该是 both

**Comment by xianghuisun** [comment]
> 如题，这两个模型是直接在llama上用2M和0.2M指令微调的？还是经过二次pre-train了

BELLE-LLaMA-7B-2M-enc是经过预训练的
