### ISSUE TITLE
请问基于BLOOM和基于LLaMA的哪个效果好点？有做过测试吗？

### ISSUE THREAD

**Issue by ruidongtd** [LianjiaTech/BELLE#43]

**Comment by tjadamlee** [comment]
有过评测，我们也正在准备release一个测试集和相关测试方法

**Comment by lavaaa7** [comment]
> 有过评测，我们也正在准备release一个测试集和相关测试方法

能给个中文数据条件下的快速结论吗？

**Comment by 649453932** [comment]
> 有过评测，我们也正在准备release一个测试集和相关测试方法

可以直接给个大概的结论吗，bloom和llama，在中文上 哪个更好点

**Comment by scarydemon2** [comment]
请问各位llama在中文上使用需要对词表做额外操作吗？

**Comment by StarRanger** [comment]
中文应该Bloom更好
