### ISSUE TITLE
多机多卡训练失败

### ISSUE THREAD

**Issue by sunnysky29** [LianjiaTech/BELLE#434]
2.2.4 多机多卡训练时候报 RuntimeError: NCCL error
我是在容器里运行的，会是什么原因呢？

**Comment by barius** [comment]
请补充下您的软硬件配置，例如GPU型号、网卡型号、驱动、NCCL版本等。另外多机网络是否是通的？容器里是否可以走RDMA？

**Comment by sunnysky29** [comment]
给的多机运行脚本如下：
node_rank=$1
echo ${node_rank}
master_addr="10.111.112.223"

# #Multi-node
torchrun --nproc_per_node 8 --nnodes 2 --master_addr ${master_addr} --master_port 14545 --node_rank ${node_rank} src/train.py 
----------------------------------------
多机训练失败报错：
RuntimeError: NCCL error in: /opt/apps/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.1.4
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
容器构建时候使用了 -host，且多机之间在同一局域网内
V100 GPU +pytorch1.10 + deepspeed0.9.2 
另外运行时候还在多机上做了同样的设置：
export NCCL_SOCKET_IFNAME=ens5f1
export NCCL_IB_DISABLE=1

有几个疑问：
1）每台机器上运行的master_addr 和 master_port 都是一样的么
2）要求每台机器的卡数必须一样，也就是nproc_per_node这个值？因为可能不同机器上卡数会不一样
3）之前给的例子都是全量微调或lora单独的， 可以deepspeed + lora 同时使用么？
4）容器能否走RDMA 这个怎么测呢？因为我看多机运行脚本并未说什么设置问题
5）多机之间走IB 还是TCP，多机运行脚本需要改动么？

**Comment by wduo** [comment]
@barius 同问，求解答

**Comment by Dagoli** [comment]
1) 每台机器的master_addr 和 master_port
2）我感觉非必须
3）可以使用
4）不知道，我跑的都是用容器
5）IB跑通过，TCP不知道
