### ISSUE TITLE
关于train.py里的一点问题

### ISSUE THREAD

**Issue by wtmlon** [LianjiaTech/BELLE#443]
请问这里的labels定义是否是有问题的，如果是自回归训练的话，input_ids是[0:max_len-1]那labels不应该是[1:max_len]吗？
<img width="944" alt="image" src="https://github.com/LianjiaTech/BELLE/assets/37530985/bf736d07-790d-4351-ae59-455528617bab">

**Comment by frankang** [comment]
这个还不是最终步，在transformers里模型的定义部分是有处理的

https://github.com/huggingface/transformers/blob/a4de24f691fa9a2757b726ee53a27058587f7b04/src/transformers/models/llama/modeling_llama.py#L708-L711

**Comment by xianghuisun** [comment]
> 请问这里的labels定义是否是有问题的，如果是自回归训练的话，input_ids是[0:max_len-1]那labels不应该是[1:max_len]吗？ <img alt="image" width="944" src="https://user-images.githubusercontent.com/37530985/246782492-bf736d07-790d-4351-ae59-455528617bab.png">

可参考楼上给出的代码：https://github.com/huggingface/transformers/blob/a4de24f691fa9a2757b726ee53a27058587f7b04/src/transformers/models/llama/modeling_llama.py#L708-L711
