### ISSUE TITLE
使用stage3，全量微调保存的结构和readme示例不一样，使用inference.py会报错，怎么处理

### ISSUE THREAD

**Issue by tc-yue** [LianjiaTech/BELLE#446]
![image](https://github.com/LianjiaTech/BELLE/assets/19323649/bf445655-c48b-4759-b91b-b5922887f520)

![image](https://github.com/LianjiaTech/BELLE/assets/19323649/940f5a13-22fd-43f2-9ed5-83d0190e9377)

**Comment by majinmin** [comment]
运行zero_to进行整合
