### ISSUE TITLE
使用BELLE代码继续sft，保存的模型占用磁盘的空间（13B的占用75G）比你们开源出来的（13B的一共占用25G）大很多？

### ISSUE THREAD

**Issue by TestNLP** [LianjiaTech/BELLE#448]

**Comment by TestNLP** [comment]
自己sft以后的：
<img width="923" alt="image" src="https://github.com/LianjiaTech/BELLE/assets/23632648/916a8d7d-67cc-4e17-8b2d-bed10f479905">


你们开源的：
<img width="1231" alt="image" src="https://github.com/LianjiaTech/BELLE/assets/23632648/df607bd8-99d7-434b-ba81-2a521b723312">

**Comment by TestNLP** [comment]
这个是什么原因导致的呢？

**Comment by Luoyingfeng8** [comment]
可能保存的是fp32
