### ISSUE TITLE
Language modeling loss

### ISSUE THREAD

**Issue by ZiboZ** [LianjiaTech/BELLE#450]
您好为什么SFT训练代码采用language modeling loss 不采用conditioning LM loss呀？把human input加入loss的计算有什么好处嘛

**Comment by hnczlsr** [comment]
https://github.com/LianjiaTech/BELLE/blob/dbb2780677f447a40b0222de676984a84afeefd6/train/src/sample_generator.py#L23-L27

看代码现在的loss只针对output计算, 确实不知道这么做与对所有token计算loss有什么不同, 会带来什么差异?

**Comment by ZiboZ** [comment]
喔喔抱歉我之前看错了，BELLE代码库v1，v2均只计算output losses，但是deepspeed-chat 和 复旦moss确是将human losses也加入了计算，我不是很明白。直觉上instruction和human应该都不计算loss。

**Comment by hnczlsr** [comment]
目前大部分做法都是只针对output计算loss, 但也有部分是对input也做的, 不知道实际会有什么影响
