### ISSUE TITLE
求助，bloom+lora，inference推理失败报错

### ISSUE THREAD

**Issue by gumanchang** [LianjiaTech/BELLE#452]
**求助，V100卡，bloomz-7b1-mt，lora without 8bit，推理时候报错，fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False  。 RuntimeError: Expected 4-dimensional input for 4-dimensional weight [8192, 16, 1, 1], but got 3-dimensional input of size [1, 32, 4096] instead**

训练命令
-- LoRA without 8bit configs/deepspeed_config_stage3.json
torchrun --nproc_per_node 2 /data/lsw/BELLE/train/src/entry_point/train.py \
    --ddp_timeout 36000 \
    --model_name_or_path ${model_name_or_path} \
    --use_lora \
    --deepspeed configs/deepspeed_config.json \  #stage2
    --lora_config configs/lora_config_bloom.json \
    --train_file ${train_file} \
    --validation_file ${validation_file} \
    --per_device_train_batch_size 1 \ 
    --per_device_eval_batch_size 1 \ 
    --gradient_accumulation_steps 1 \ 
    --num_train_epochs 2 \ 
    --model_max_length ${cutoff_len} \
    --save_strategy "steps" \
    --save_total_limit 3 \ 
    --learning_rate 3e-4 \
    --weight_decay 0.00001 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 10 \
    --evaluation_strategy "steps" \
    --fp16 \
    --seed 1234 \
    --gradient_checkpointing \
    --cache_dir ${cache_dir} \
    --output_dir ${output_dir} \
   
  
  
  模型保存的目录结构
 adapter_config.json
 adapter_model.bin
 global_step247480
 latest
 pytorch_model.bin
 rng_state_0.pth
 rng_state_1.pth
 trainer_state.json
 training_args.bin
 zero_to_fp32.py
  
  
  
  adapter_config.json
  {
  2   "base_model_name_or_path": "/data/lsw/BELLE/bloomz-7b1-mt",
  3   "bias": "none",
  4   "enable_lora": [
  5     true,
  6     false,
  7     true
  8   ],
  9   "fan_in_fan_out": true,#这个生成就是true
 10   "inference_mode": true,
 11   "lora_alpha": 32,
 12   "lora_dropout": 0.05,
 13   "merge_weights": false,
 14   "modules_to_save": null,
 15   "peft_type": "LORA",
 16   "r": 16,
 17   "target_modules": [
 18     "query_key_value"
 19   ],
 20   "task_type": "CAUSAL_LM"
 21 }

推理报错，日志如下，fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.

(belle) [lsw@wp-aigpu-ns-prod-172-22-0-7 train]$ CUDA_VISIBLE_DEVICES=0 python src/entry_point/inference.py --model_name_or_path  /data/lsw/BELLE/bloomz-7b1-mt --ckpt_path  /data/lsw/BELLE/train/saved_models/math_test_001/checkpoint-197984 --use_lora
[2023-06-28 14:31:55,343] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)

/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /data/lsw/anaconda3/envs/belle did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 111
/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so...
/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/peft/tuners/lora.py:173: UserWarning: fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.
  warnings.warn(
Traceback (most recent call last):
  File "src/entry_point/inference.py", line 63, in <module>
    
  File "/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2307, in eval
    return self.train(False)
  File "/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2288, in train
    module.train(mode)
  File "/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2288, in train
    module.train(mode)
  File "/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2288, in train
    module.train(mode)
  [Previous line repeated 4 more times]
  File "/data/lsw/anaconda3/envs/belle/lib/python3.8/site-packages/peft/tuners/lora.py", line 417, in train
    delta_w = F.conv1d(
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [8192, 16, 1, 1], but got 3-dimensional input of size [1, 32, 4096] instead

**Comment by majinmin** [comment]
同样的问题

**Comment by blackfluence** [comment]
我也遇到了同样的问题，最后发现原因是我在训练的过程中改了一些超参(bs, max_seqlen, lora_r 等)，导致有些配置不太一致。
我删了整个saved_models目录，重新训练就解决了。

PS：感觉这个方法并不能解决问题 https://github.com/liucongg/ChatGLM-Finetuning/issues/39
