### ISSUE TITLE
请问0.5M和1M数据的prompt来源是什么？0.5M数据是做了什么样的数据质量控制吗？ 

### ISSUE THREAD

**Issue by hadoopmore** [LianjiaTech/BELLE#46]

**Comment by barius** [comment]
我们沿用Alpaca的方式来获取数据：https://github.com/LianjiaTech/BELLE#%E6%95%B0%E6%8D%AE%E7%94%9F%E6%88%90
0.5M和1M的种子prompt是相同的，在https://github.com/LianjiaTech/BELLE/blob/main/prompt_cn.txt

0.5M数据是较早期发布的，没有加清洗；1M数据是新生成的并且加了清洗https://huggingface.co/datasets/BelleGroup/generated_train_1M_CN/blob/main/README.md#%E5%86%85%E5%AE%B9
