### ISSUE TITLE
BELLE-3.5数据集问题

### ISSUE THREAD

**Issue by caihaunqai** [LianjiaTech/BELLE#468]
您好，感谢您的工作。看了您的论文，有一些疑问，希望可以解答，谢谢：
1、看到表格里的数据，想知道为什么最好的实验结果训练集加入了zh(alpaca-3.5)，从实验结果来看，4比3.5+4好呀？
<img width="815" alt="image" src="https://github.com/LianjiaTech/BELLE/assets/56779804/c973ead6-a664-4963-9f8a-59c5f397a503">
2、想请问目前开源的1M、0.5M、3.5M等数据集里的3.5M是原文的数据集吗？如果不是，他们有什么区别？另外1M、0.5M、3.5M有什么区别呢？
谢谢！

**Comment by xianghuisun** [comment]
> 您好，感谢您的工作。看了您的论文，有一些疑问，希望可以解答，谢谢： 1、看到表格里的数据，想知道为什么最好的实验结果训练集加入了zh(alpaca-3.5)，从实验结果来看，4比3.5+4好呀？ <img alt="image" width="815" src="https://user-images.githubusercontent.com/56779804/256184954-c973ead6-a664-4963-9f8a-59c5f397a503.png"> 2、想请问目前开源的1M、0.5M、3.5M等数据集里的3.5M是原文的数据集吗？如果不是，他们有什么区别？另外1M、0.5M、3.5M有什么区别呢？ 谢谢！


1. 从实验效果上看，4就是比4+3.5更好，这也说明了训练数据不是越多越好
2. 论文中belle-3.5就是开源的3.5m。
3. 0.5m 1m 3.5m是三批不同的数据，理论上不存在重叠
