### ISSUE TITLE
增量预训练和微调的工作

### ISSUE THREAD

**Issue by X-jun-0130** [LianjiaTech/BELLE#474]
您好,在你们最新的工作ChatHome中,使用多任务指令结合预训练的方式,取得了最优的结果.
想咨询下,
1.对于指令这部分数据添加进预训练时,有没有做特殊的处理,比如:对指令的输入部分的label归为-100
2.做了多任务指令预训练之后,是否还需要进行下一步微调这个步骤.
对这部分工作特别的感兴趣,希望能得到回复.

**Comment by xianghuisun** [comment]
> 您好,在你们最新的工作ChatHome中,使用多任务指令结合预训练的方式,取得了最优的结果. 想咨询下, 1.对于指令这部分数据添加进预训练时,有没有做特殊的处理,比如:对指令的输入部分的label归为-100 2.做了多任务指令预训练之后,是否还需要进行下一步微调这个步骤. 对这部分工作特别的感兴趣,希望能得到回复.

您好
第一个问题：您说的是对的，对输入部分instruction是要归为-100从而mask掉，只计算response的损失
第二个问题：多任务指令预训练之后，不会再微调。

**Comment by X-jun-0130** [comment]
您好,非常感谢回复.
还有个问题想请教一下, 预训练时,对于书籍数据,长度超长的文本,在处理时直接进行截断还是做了诸如滑动窗口之类的处理.

**Comment by xianghuisun** [comment]
> 您好,非常感谢回复. 还有个问题想请教一下, 预训练时,对于书籍数据,长度超长的文本,在处理时直接进行截断还是做了诸如滑动窗口之类的处理.

可参考代码：
https://github.com/LianjiaTech/BELLE/blob/main/train/src/sample_generator.py#L83C37-L83C37

直接进行截断，不考虑重叠片段这种滑动窗口的方式

**Comment by X-jun-0130** [comment]
好的  感谢

**Comment by songkq** [comment]
@xianghuisun Hi, 请问多任务指令训练数据在pretrain阶段中是否需要按"<reserved_102>{query}<reserved_103>"组织输入部分instruction query?

**Comment by xianghuisun** [comment]
> @xianghuisun Hi, 请问多任务指令训练数据在pretrain阶段中是否需要按"<reserved_102>{query}<reserved_103>"组织输入部分instruction query?

不需要
需要注意的是每一个response后要加上eos_token_id

**Comment by xianghuisun** [comment]
> @xianghuisun Hi, 请问多任务指令训练数据在pretrain阶段中是否需要按"<reserved_102>{query}<reserved_103>"组织输入部分instruction query?

您好，我再详细说明下。对于指令数据，
格式是 Human: \n instruction \n\nAssistant: \nresponse
不是按照百川的格式

我这里贴下截取的代码：

for sentence in source:
    sentence_from = sentence["from"].lower()
    sentence_value = sentence["value"]
    sentence_value = 'Human: \n' + sentence_value + '\n\nAssistant: \n' #if sentence_from == 'human' else sentence["value"]
    sentence_ids = tokenizer.encode(sentence_value, add_special_tokens=False)

    if sentence_from == 'human':
        label = [IGNORE_INDEX] * len(sentence_ids)
    else:
        label = copy.deepcopy(sentence_ids)

    cur_input_ids += sentence_ids
    cur_labels += label
    # add eos at every end of assistant sentence
    if sentence_from != 'human':
        cur_input_ids += [tokenizer.eos_token_id]#make sure eos_token_id is correct
        cur_labels += [tokenizer.eos_token_id]

**Comment by songkq** [comment]
> > @xianghuisun Hi, 请问多任务指令训练数据在pretrain阶段中是否需要按"<reserved_102>{query}<reserved_103>"组织输入部分instruction query?
> 
> 您好，我再详细说明下。对于指令数据， 格式是 Human: \n instruction \n\nAssistant: \nresponse 不是按照百川的格式
> 
> 我这里贴下截取的代码：
> 
> for sentence in source:
> 
> ```
> sentence_from = sentence["from"].lower()
> sentence_value = sentence["value"]
> sentence_value = 'Human: \n' + sentence_value + '\n\nAssistant: \n' #if sentence_from == 'human' else sentence["value"]
> sentence_ids = tokenizer.encode(sentence_value, add_special_tokens=False)
> if sentence_from == 'human':
>     label = [IGNORE_INDEX] * len(sentence_ids)
> else:
>     label = copy.deepcopy(sentence_ids)
> 
> cur_input_ids += sentence_ids
> cur_labels += label
> # add eos at every end of assistant sentence
> if sentence_from != 'human':
>     cur_input_ids += [tokenizer.eos_token_id]#make sure eos_token_id is correct
>     cur_labels += [tokenizer.eos_token_id]
> ```

@xianghuisun 好的，感谢～ 请问在推理阶段需要遵循Baichuan-13B-Chat的模版吗？

**Comment by xianghuisun** [comment]
> > > @xianghuisun Hi, 请问多任务指令训练数据在pretrain阶段中是否需要按"<reserved_102>{query}<reserved_103>"组织输入部分instruction query?
> > 
> > 
> > 您好，我再详细说明下。对于指令数据， 格式是 Human: \n instruction \n\nAssistant: \nresponse 不是按照百川的格式
> > 我这里贴下截取的代码：
> > for sentence in source:
> > ```
> > sentence_from = sentence["from"].lower()
> > sentence_value = sentence["value"]
> > sentence_value = 'Human: \n' + sentence_value + '\n\nAssistant: \n' #if sentence_from == 'human' else sentence["value"]
> > sentence_ids = tokenizer.encode(sentence_value, add_special_tokens=False)
> > if sentence_from == 'human':
> >     label = [IGNORE_INDEX] * len(sentence_ids)
> > else:
> >     label = copy.deepcopy(sentence_ids)
> > 
> > cur_input_ids += sentence_ids
> > cur_labels += label
> > # add eos at every end of assistant sentence
> > if sentence_from != 'human':
> >     cur_input_ids += [tokenizer.eos_token_id]#make sure eos_token_id is correct
> >     cur_labels += [tokenizer.eos_token_id]
> > ```
> 
> @xianghuisun 好的，感谢～ 请问在推理阶段需要遵循Baichuan-13B-Chat的模版吗？

当然不可以啊，要按照训练时的格式来

instruction = 'Human: \n' + instruction + '\n\nAssistant: \n'
inputs = tokenizer(instruction,return_tensors="pt")
input_ids = inputs["input_ids"]

generation_output = model.generate(
    input_ids = input_ids.to(device), 
    **generation_config
)[0]
