### ISSUE TITLE
请问无法运行镜像该怎么解决？

### ISSUE THREAD

**Issue by tomhas-hub** [LianjiaTech/BELLE#481]
我已经pull镜像，并且安装container-toolkit和创建密钥，当我按下面指令运行容器时 “sudo bash docker_run.sh”, 就会出现以下错误:
docker: invalid reference format.
---------------------------------------------------------
docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
    --network host \
    --env https_proxy=$https_proxy \
    --env http_proxy=$http_proxy \
    --env all_proxy=$all_proxy \
    --env HF_HOME=$hf_home \
    -d --rm \
    --name belle \
    -v $belle_path:$belle_path \
    -v $hf_home:$hf_home \
    -v $ssh_pub_key:/root/.ssh/authorized_keys \
    -w $workdir \
    $docker_user/belle:$tag \
    --sshd_port 2201 --cmd "echo 'export https_proxy=$https_proxy' >> /root/.bashrc && \
                            echo 'export http_proxy=$http_proxy' >> /root/.bashrc && \
                            echo 'export all_proxy=$all_proxy' >> /root/.bashrc && \
                            echo 'export HF_HOME=$hf_home' >> /root/.bashrc && \
                            sleep infinity"
----------------------------------------------------------------------------------------------------------
求问该怎么改正格式

**Comment by tothemoon96** [comment]
需要正确指定下面变量
export https_proxy=...
export http_proxy=...
export all_proxy=...

belle_path=...
docker_user=...
tag=...
hf_home="/.../.cache/huggingface"
ssh_pub_key="/home/.../.ssh/id_rsa.pub"
workdir="$belle_path/train"
chown root:root $ssh_pub_key
