### ISSUE TITLE
MIP阶段垂直领域预训练数据需要多少

### ISSUE THREAD

**Issue by MingJiaAn** [LianjiaTech/BELLE#486]
您好，你们前几天发表的技术报告里提到，MIP阶段完全采用垂直领域数据效果更佳，这部分垂直领域数据量级大概是多少呢？epoch设置多少效果比较好？

**Comment by xianghuisun** [comment]
26.6M tokens

**Comment by xianghuisun** [comment]
> 您好，你们前几天发表的技术报告里提到，MIP阶段完全采用垂直领域数据效果更佳，这部分垂直领域数据量级大概是多少呢？epoch设置多少效果比较好？

您好，MIP阶段的训练数据是领域预训练数据+领域指令数据
其中领域预训练数据的token数量是26.6M，领域指令数据的条数是25k。

需要注意的是，不同模型，tokenizer不同，最终切词的数量也是不同的。

**Comment by MingJiaAn** [comment]
> > 您好，你们前几天发表的技术报告里提到，MIP阶段完全采用垂直领域数据效果更佳，这部分垂直领域数据量级大概是多少呢？epoch设置多少效果比较好？
> 
> 您好，MIP阶段的训练数据是领域预训练数据+领域指令数据 其中领域预训练数据的token数量是26.6M，领域指令数据的条数是25k。
> 
> 需要注意的是，不同模型，tokenizer不同，最终切词的数量也是不同的。

是用的lora还是全参微调呢？谢谢

**Comment by wen2cheng** [comment]
#489

**Comment by jeejeeli** [comment]
@xianghuisun 非常感谢您们提供的技术报告，想问下使用了MIP，是不是只做DAPT就行了，还需要再做SFT吗
