### ISSUE TITLE
请问如何进行单机多卡训练？请问我该如何调整？

### ISSUE THREAD

**Issue by tomhas-hub** [LianjiaTech/BELLE#487]
我这台机子有两张卡，所以我想进行一个多卡训练，我将nproc_per_node参数设为2，但无法训练，一直卡在下面这个地方：
![image](https://github.com/LianjiaTech/BELLE/assets/54656571/96984e4e-714a-49ac-b8fc-d874d8423339)
这是我的参数：
![image](https://github.com/LianjiaTech/BELLE/assets/54656571/50675750-8cf2-4879-88a4-8b111c7550ca)

**Comment by sun1092469590** [comment]
可以试试直接deepspeed启动训练
