### ISSUE TITLE
ChatHome中，使用多任务指令结合预训练的方式相关疑问

### ISSUE THREAD

**Issue by sun1092469590** [LianjiaTech/BELLE#494]
您好，在ChatHome中，您使用了文本数据和指令数据混合来进行训练，我想问一下，混合数据的大概格式：

（1）那在做训练数据时，文本数据和指令数据需要怎么准备，如果使用您的项目来跑，
文本数据的格式如下：{"text": xxx} ，
指令数据的格式如下：scripts/convert_to_conv_data.py进行转换变成
{"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]} ，
因为两者现在均是json格式，混合训练时直接就放一起作为训练集，是吗？比如：
{"text": xxx} ,
{"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]} 

（2）您在 #474 中提到的指令格式 Human: \n instruction \n\nAssistant: \nresponse，应该是在执行预训练脚本时会调用相关脚本进行处理格式再训练，是吗？

（3）这个项目能跑baichuan-13b、xverse-13b、llama2这些模型吗？

**Comment by xianghuisun** [comment]
> 您好，在ChatHome中，您使用了文本数据和指令数据混合来进行训练，我想问一下，混合数据的大概格式：
> 
> （1）那在做训练数据时，文本数据和指令数据需要怎么准备，如果使用您的项目来跑， 文本数据的格式如下：{"text": xxx} ， 指令数据的格式如下：scripts/convert_to_conv_data.py进行转换变成 {"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]} ， 因为两者现在均是json格式，混合训练时直接就放一起作为训练集，是吗？比如： {"text": xxx} , {"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]}
> 
> （2）您在 #474 中提到的指令格式 Human: \n instruction \n\nAssistant: \nresponse，应该是在执行预训练脚本时会调用相关脚本进行处理格式再训练，是吗？
> 
> （3）这个项目能跑baichuan-13b、xverse-13b、llama2这些模型吗？

您好，具体来说，指令数据和纯文本数据是不能放在一个文件中，比如我有：
a.json. b.json. c.json. d.json
其中b.json是指令数据，其它三个是纯文本数据

代码中的处理逻辑是：
1. 如果当前文件是指令数据格式，就调用处理指令数据的函数，函数内部会加上Human: \n instruction \n\nAssistant: \nresponse. 同时注意对instruction部分对应的label位置做mask，也就是不计算instruction部分的loss
2. 如果当前文件是纯文本格式，就调用output = tokenizer(examples["text"]) 

baichuan. llama2都是可以跑的

**Comment by xianghuisun** [comment]
> > 您好，在ChatHome中，您使用了文本数据和指令数据混合来进行训练，我想问一下，混合数据的大概格式：
> > （1）那在做训练数据时，文本数据和指令数据需要怎么准备，如果使用您的项目来跑， 文本数据的格式如下：{"text": xxx} ， 指令数据的格式如下：scripts/convert_to_conv_data.py进行转换变成 {"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]} ， 因为两者现在均是json格式，混合训练时直接就放一起作为训练集，是吗？比如： {"text": xxx} , {"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]}
> > （2）您在 #474 中提到的指令格式 Human: \n instruction \n\nAssistant: \nresponse，应该是在执行预训练脚本时会调用相关脚本进行处理格式再训练，是吗？
> > （3）这个项目能跑baichuan-13b、xverse-13b、llama2这些模型吗？
> 
> 您好，具体来说，指令数据和纯文本数据是不能合并在一个文件中的，比如我有： a.json. b.json. c.json. d.json 其中b.json是指令数据，其它三个是纯文本数据
> 
> 代码中的处理逻辑是：
> 
> 1. 如果当前文件是指令数据格式，就调用处理指令数据的函数，函数内部会加上Human: \n instruction \n\nAssistant: \nresponse. 同时注意对instruction部分对应的label位置做mask，也就是不计算instruction部分的loss
> 2. 如果当前文件是纯文本格式，就调用output = tokenizer(examples["text"])
> 
> baichuan. llama2都是可以跑的

**Comment by sun1092469590** [comment]
哦哦，理解了。  那您在ChatHome中，使用的文本数据和指令数据混合来训练时什么意思呢？a.json. b.json. c.json. d.json
其中b.json是指令数据，其它三个是纯文本数据，如果我想要用这4个数据集来混合训练模型，这4个数据集要怎么一起训呢？

**Comment by sth0114** [comment]
> 我这边直接跑run_[pt.sh](http://pt.sh)一堆问题。。。单拿出来跑在train目录下跑 src/entry_point/pt_[train.py](http://train.py)，说是 No models named 'src'。。。该有的包都有装
把src目录加入~/.bashrc 全局变量
export PYTHONPATH=$PYTHONPATH:/path/BELLE/train/src

**Comment by sun1092469590** [comment]
> > 我这边直接跑run_[pt.sh](http://pt.sh)一堆问题。。。单拿出来跑在train目录下跑 src/entry_point/pt_[train.py](http://train.py)，说是 No models named 'src'。。。该有的包都有装
> > 把src目录加入~/.bashrc 全局变量
> > export PYTHONPATH=$PYTHONPATH:/path/BELLE/train/src

我再试试，谢谢哈

**Comment by sun1092469590** [comment]
全量参数预训练耗费时间看着好长啊，我只有34M的文本，训练时担心内存溢出，设置的batch_size=1，4epoch ,看着得470+小时。。我这边单机多卡训练，查看占用的GPU显存，几张卡总共才占18G。

如果用lora方式pt训练baichuan-13b-base，lora_config这样设置可以吗？
{
“lora_r”:16,
"lora_alpha":32,
"lora_dropout":0.05,
"lora_target_modules":[
  "W_pack"
]
}

我想试您ChatHome中的混合训练方式，是不是这样的：先用文本数据训练（跑pt_train.py）,得到训练后的模型A，然后继续用指令数据继续训练模型A（跑pt_train.py），得到模型B，B不用再sft微调了，流程是这样吗？

**Comment by zyzyyy123** [comment]
> > 您好，在ChatHome中，您使用了文本数据和指令数据混合来进行训练，我想问一下，混合数据的大概格式：
> > （1）那在做训练数据时，文本数据和指令数据需要怎么准备，如果使用您的项目来跑， 文本数据的格式如下：{"text": xxx} ， 指令数据的格式如下：scripts/convert_to_conv_data.py进行转换变成 {"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]} ， 因为两者现在均是json格式，混合训练时直接就放一起作为训练集，是吗？比如： {"text": xxx} , {"id": "bellemath42", "conversations": [{"from": "human", "value": " 一箱鸡蛋有25个，小明爸爸每天给他9个鸡蛋吃，那么一箱鸡蛋能够供小明吃几天？"}, {"from": "assistant", "value": "\n一箱鸡蛋有25个，小明每天吃9个鸡蛋，用除法计算一下即可：\n25 ÷ 9 = 2余7\n也就是说，小明第1天到第2天共吃2个鸡蛋，第3天吃剩下的7个鸡蛋。\n因此，一箱鸡蛋能够供小明吃2天。"}]}
> > （2）您在 #474 中提到的指令格式 Human: \n instruction \n\nAssistant: \nresponse，应该是在执行预训练脚本时会调用相关脚本进行处理格式再训练，是吗？
> > （3）这个项目能跑baichuan-13b、xverse-13b、llama2这些模型吗？
> 
> 您好，具体来说，指令数据和纯文本数据是不能放在一个文件中，比如我有： a.json. b.json. c.json. d.json 其中b.json是指令数据，其它三个是纯文本数据
> 
> 代码中的处理逻辑是：
> 
> 1. 如果当前文件是指令数据格式，就调用处理指令数据的函数，函数内部会加上Human: \n instruction \n\nAssistant: \nresponse. 同时注意对instruction部分对应的label位置做mask，也就是不计算instruction部分的loss
> 2. 如果当前文件是纯文本格式，就调用output = tokenizer(examples["text"]) ，labels就是input_ids
> 
> baichuan. llama2都是可以跑的

@xianghuisun 您好，请问这部分的代码具体是在哪里呢？
