### ISSUE TITLE
MIP时除领域指令外加入通用指令的效果有测试过吗？

### ISSUE THREAD

**Issue by xyfZzz** [LianjiaTech/BELLE#497]
看到论文中MIP的实验中，只加入了领域指令，请问有测试过同时加入通用指令效果如何吗？

**Comment by sun1092469590** [comment]
> 看到论文中MIP的实验中，只加入了领域指令，请问有测试过同时加入通用指令效果如何吗？

你MIT指令数据有试过吗？这个要怎么用呢？

**Comment by xyfZzz** [comment]
> > 看到论文中MIP的实验中，只加入了领域指令，请问有测试过同时加入通用指令效果如何吗？
> 
> 你MIT指令数据有试过吗？这个要怎么用呢？

使用方式你可以看下这个issuer里的内容：https://github.com/LianjiaTech/BELLE/issues/494

**Comment by sun1092469590** [comment]
# 494  中作者讲了指令数据和文本数据的代码中的处理逻辑：
如果当前文件是指令数据格式，就调用处理指令数据的函数，函数内部会加上Human: \n instruction \n\nAssistant: \nresponse. 同时注意对instruction部分对应的label位置做mask，也就是不计算instruction部分的loss
如果当前文件是纯文本格式，就调用output = tokenizer(examples["text"]) ，labels就是input_ids

但是该项目中，MIP指令数据要训练的话，调用pt_train.py不对，它只处理训练文本数据， 那只能调用sft_train.py吗？

**Comment by codemaster17611** [comment]
老哥，MIP的训练代码有写通吗，想求教

**Comment by sun1092469590** [comment]
可以跑通，先用pt_train.py跑文本数据，再用sft_train.py跑指令数据，数据格式都要先按read中写的格式处理一下

**Comment by codemaster17611** [comment]
> 可以跑通，先用pt_train.py跑文本数据，再用sft_train.py跑指令数据，数据格式都要先按read中写的格式处理一下

兄得，我这样搞定了
from datasets import load_dataset, concatenate_datasets

# train_data1 PT
# train_data2 SFT
concatenate_datasets([train_data1, train_data2])

**Comment by sun1092469590** [comment]
> > 可以跑通，先用pt_train.py跑文本数据，再用sft_train.py跑指令数据，数据格式都要先按read中写的格式处理一下
> 
> 兄得，我这样搞定了
> 
> ```python
> from datasets import load_dataset, concatenate_datasets
> 
> # train_data1 PT
> # train_data2 SFT
> concatenate_datasets([train_data1, train_data2])
> ```

train_data1是先用sample_generator.py中batch_grouped_pretrain_generate函数处理，train_data2先用sample_generator.py中batch_grouped_sft_generate函数处理是吗？
