### ISSUE TITLE
git clone报错？

### ISSUE THREAD

**Issue by erichuazhou** [LianjiaTech/BELLE#499]
用git clone代码时报错：

error: invalid path 'train/dschat_train_v1/reproduce_our_papers/Towards Better Instruction Following Language Models for Chinese: Investigating the Impact of Training Data and Evaluation.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Geraint-Dou** [comment]
我也遇到了同样的问题，尝试VPN，流量后依旧报错
下载zip并解压时报‘Towards Better Instruction Following Language Models for Chinese: Investigating the Impact of Training Data and Evaluation.md'文件错误

**Comment by Geraint-Dou** [comment]
> 用git clone代码时报错：
> 
> error: invalid path 'train/dschat_train_v1/reproduce_our_papers/Towards Better Instruction Following Language Models for Chinese: Investigating the Impact of Training Data and Evaluation.md' fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'

按照以下命令行修改git配置可解决问题：

忽略路径中的转义字符
git config --global core.protectNTFS false

禁用换行符转换
git config --global core.autocrlf false

中文文件名，乱码问题。设为false的话，就不会对0x80以上的字符进行quot
git config --global core.quotepath false
