### ISSUE TITLE
可以用 alpaca.cpp 运行吗

### ISSUE THREAD

**Issue by linonetwo** [LianjiaTech/BELLE#5]
可能需要量化。降低门槛才能有更多的人体验到。

**Comment by barius** [comment]
Belle模型基于Bloom，可以考虑https://github.com/NouamaneTazi/bloomz.cpp

**Comment by DLSeed** [comment]
目前放出的权重，可以用半精度做推理吗？比如在24GB的显卡上可跑？

**Comment by Yif1999** [comment]
> Belle模型基于Bloom，可以考虑https://github.com/NouamaneTazi/bloomz.cpp

请问可以使用Bloom仓库中的量化和转ggml模型指南来让belle模型运行在alpaca.cpp下吗

**Comment by Yif1999** [comment]
> > Belle模型基于Bloom，可以考虑https://github.com/NouamaneTazi/bloomz.cpp
> 
> 请问可以使用Bloom仓库中的量化和转ggml模型指南来让belle模型运行在alpaca.cpp下吗

尝试了一下这个流程，量化int4模型后丢到alpaca.cpp里无法运行，加载模型的过程会无限制地吃内存直到控制台kill掉进程，倒是可以用bloomz.cpp加载运行，但是对话效果很差

**Comment by bestpredicts** [comment]
我们也发现bloomz.cpp量化的效果存在问题，我们已经在做我们的模型量化工作了，预计本周会更新相关量化的权重和推理代码。
