### ISSUE TITLE
BELLE项目是不是暂时还不支持baichuan2-13b？

### ISSUE THREAD

**Issue by sun1092469590** [LianjiaTech/BELLE#506]
BELLE项目是不是暂时还不支持baichuan2-13b-base？跑pt_train.py时，在Running Evaluation时会报错：AttributeError：'Parameter' object has no attribute 'ds_status'.

**Comment by sun1092469590** [comment]
好像是因为使用了deepspeed stage3，baichuan2-13b-base 使用stage3都有这个问题。换stage2再试试看

**Comment by wen2cheng** [comment]
更新一下最新的Baichuan模型再试试

**Comment by sun1092469590** [comment]
> 好像是因为使用了deepspeed stage3，baichuan2-13b-base 使用stage3都有这个问题。换stage2再试试看

新的baichuan2吗？我更新一下，谢谢哈

**Comment by sun1092469590** [comment]
> 更新一下最新的Baichuan模型再试试

这两天baichuan2有更新模型文件是吗？huggingface进不去现在。。。

**Comment by larsoncs** [comment]
百川2效果不如belle，实测完毕，belle好强啊

**Comment by sun1092469590** [comment]
> 百川2效果不如belle，实测完毕，belle好强啊

啥意思？不如belle开源的模型吗？

**Comment by zzisbeauty** [comment]
> 百川2效果不如belle，实测完毕，belle好强啊

你这个说不好没说尺寸啊，为什么大家普遍对baichuan的评价很高。
