### ISSUE TITLE
求助，请问下在预训练时怎么关闭evaluation？

### ISSUE THREAD

**Issue by sun1092469590** [LianjiaTech/BELLE#509]
baichuan2-13B-Base模型二次预训练时（pt_train.py），会出错。请问下如果要关闭evaluation在哪里操作？

**Comment by xianghuisun** [comment]
> baichuan2-13B-Base模型二次预训练时（pt_train.py），会出错。请问下如果要关闭evaluation在哪里操作？

您好，您可以在torchrun的参数中指定 --evaluation_strategy "no"

**Comment by sun1092469590** [comment]
好的好的，谢谢快速回复，那如果我用deepspeed启动呢，也是使用 --evaluation_strategy "no"来关闭吗？

**Comment by wengieeee** [comment]
你好，请问你在训练时会报错说找不到src包吗？
![image](https://github.com/LianjiaTech/BELLE/assets/16257260/a0e1ec5d-bb73-41db-9a76-e4ee07f2ef88)

**Comment by sun1092469590** [comment]
> 你好，请问你在训练时会报错说找不到src包吗？ ![image](https://user-images.githubusercontent.com/16257260/268610467-a0e1ec5d-bb73-41db-9a76-e4ee07f2ef88.png)

把src目录加入~/.bashrc 全局变量，在train目录下执行这个：
export PYTHONPATH=$PYTHONPATH:/path/BELLE/train/src
