### ISSUE TITLE
BELLE-LLAMA-7B-2M load ERROR

### ISSUE THREAD

**Issue by jkkl** [LianjiaTech/BELLE#51]
![image](https://user-images.githubusercontent.com/3937341/227886421-270b3fff-fe63-4e93-8099-1c837bbf996c.png)

**Comment by jkkl** [comment]
已经运行了，pip install git+https://github.com/huggingface/transformers
执行的是，model card上的源码。

**Comment by jkkl** [comment]
发生异常: TypeError
dispatch_model() got an unexpected keyword argument 'offload_index'
  File "/..../model_test_BELLE_LLAMA.py", line 10, in <module>
    model = LlamaForCausalLM.from_pretrained(ckpt, device_map='auto', low_cpu_mem_usage=True)
TypeError: dispatch_model() got an unexpected keyword argument 'offload_index'

**Comment by jkkl** [comment]
@Life-0-1 感谢回复，我尝试去掉一些参数后，就正常了。
model = LlamaForCausalLM.from_pretrained(ckpt).to(device)

**Comment by byamao1** [comment]
> ![image](https://user-images.githubusercontent.com/3937341/227886421-270b3fff-fe63-4e93-8099-1c837bbf996c.png)

咨询下，这个代码地址能否提供一下
