### ISSUE TITLE
微调的模型缺少config.json文件

### ISSUE THREAD

**Issue by tendrillion** [LianjiaTech/BELLE#510]
运行 run_sft.sh采用lora方式训练llama模型，缺少config.json文件。
参考issues：使用lora微调后的模型进行生成时，报错Can't find config.json at trained_models/llama/checkpoint-*** #131
问题仍然存在。

**Comment by tothemoon96** [comment]
peft保存的模型是lora，不存在config.json，需要和原始的基座模型合并
