### ISSUE TITLE
微调llama模型，缺少adapter_model.bin和adapter_config.json文件

### ISSUE THREAD

**Issue by tendrillion** [LianjiaTech/BELLE#511]
运行 run_sft.sh采用lora方式训练llama模型，缺少adapter_model.bin和adapter_config.json文件。
issues：用lora模式训练出的模型缺少adapter_model.bin和adapter_config.json #370
这个issues中提到：训练结束后需要使用model.save_pretrained()方法才能保存 adapter_config和adapter_model，代码已修改。
但是目前版本BELLE v0.95 中仍然存在这个问题。

**Comment by tothemoon96** [comment]
请切换到最新的main分支
