### ISSUE TITLE
MIP的时候loss是怎么更新的

### ISSUE THREAD

**Issue by chloefresh** [LianjiaTech/BELLE#512]
请问是把pt数据的loss和sft数据的loss合并后更新，还是分别更新呢

**Comment by sun1092469590** [comment]
应该是分别？pt和sft都是分开跑的

**Comment by xianghuisun** [comment]
> 请问是把pt数据的loss和sft数据的loss合并后更新，还是分别更新呢

您可以理解是分开，具体来说，是把pt数据和sft数据统一放在一起，用concatenate_datasets方法拼接两个dataset，从而先在pt数据上训练，然后在sft数据上训练

**Comment by sun1092469590** [comment]
@xianghuisun  您好，我用MIP方式好像用错了。。。  您的意思是文本数据先和指令数据先统一放在一起，用concatenate_datasets方法拼接两个dataset，最后拼接成一个数据集吗？然后先在pt数据上训练，然后在sft数据上训练？

**Comment by chloefresh** [comment]
@xianghuisun 谢谢解答！

**Comment by parkLGW** [comment]
请问解决了吗？
