### ISSUE TITLE
代理设置无效 生成不了数据

### ISSUE THREAD

**Issue by wccccp** [LianjiaTech/BELLE#52]
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b2a250>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b2a400>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions
WARNING:root:OpenAIError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b2a040>: Failed to establish a new connection: [Errno 111] Connection refused'))).
WARNING:root:Hit request rate limit; retrying...
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b5ffa0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b5f4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions
WARNING:root:OpenAIError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b5f460>: Failed to establish a new connection: [Errno 111] Connection refused'))).
WARNING:root:Hit request rate limit; retrying...
![image](https://user-images.githubusercontent.com/55964850/227888646-9b9a73e7-951f-4e88-b281-0c2711ebb335.png)

**Comment by bestpredicts** [comment]
应

> WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b2a250>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b2a400>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions WARNING:root:OpenAIError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b2a040>: Failed to establish a new connection: [Errno 111] Connection refused'))). WARNING:root:Hit request rate limit; retrying... WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b5ffa0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b5f4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /v1/completions WARNING:root:OpenAIError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f65b5f460>: Failed to establish a new connection: [Errno 111] Connection refused'))). WARNING:root:Hit request rate limit; retrying... ![image](https://user-images.githubusercontent.com/55964850/227888646-9b9a73e7-951f-4e88-b281-0c2711ebb335.png)

应该是在util.py里面使用openai提供的接口设置代理。
```shell
openai.proxy = self.api_config['openai'].get('proxy', None)

```
