### ISSUE TITLE
how did you get category about dataset train_3.5M_CN_With_Category?

### ISSUE THREAD

**Issue by liwenju0** [LianjiaTech/BELLE#529]
here 

https://huggingface.co/datasets/BELLE-2/train_3.5M_CN_With_Category

Thank you for sharing this excellent data. May I ask how you obtained the category for each conversation? Did you train a classification model for this purpose? If so, would it be possible to open-source the model? Thank you.

**Comment by Emperorizzis** [comment]
Hi, thanks for you attention, we did train a category classification model to classify the data. And for the categories, We defined these categories with reference to instructgpt, traditional NLP tasks, and other classification logic.
