### ISSUE TITLE
context length 2049 我请求的3643token 请问在哪里设置

### ISSUE THREAD

**Issue by wccccp** [LianjiaTech/BELLE#54]
WARNING:root:Reducing target length to 0, Retrying...
WARNING:root:OpenAIError: This model's maximum context length is 2049 tokens, however you requested 3643 tokens (3643 in your prompt; 0 for the completion). Please reduce your prompt; or completion length..
WARNING:root:Reducing target length to 0, Retrying...
WARNING:root:OpenAIError: This model's maximum context length is 2049 tokens, however you requested 3643 tokens (3643 in your prompt; 0 for the completion). Please reduce your prompt; or completion length..
WARNING:root:Reducing target length to 0, Retrying...
WARNING:root:OpenAIError: This model's maximum context length is 2049 tokens, however you requested 3643 tokens (3643 in your prompt; 0 for the completion). Please reduce your prompt; or completion length..
WARNING:root:Reducing target length to 0, Retrying...
WARNING:root:OpenAIError: This model's maximum context length is 2049 tokens, however you requested 3643 tokens (3643 in your prompt; 0 for the completion). Please reduce your prompt; or completion length..
WARNING:root:Reducing target length to 0, Retrying...
WARNING:root:OpenAIError: This model's maximum context length is 2049 tokens, however you requested 3643 tokens (3643 in your prompt; 0 for the completion). Please reduce your prompt; or completion length..
WARNING:root:Reducing target length to 0, Retrying...
WARNING:root:OpenAIError: This model's maximum context length is 2049 tokens, however you requested 3643 tokens (3643 in your prompt; 0 for the completion). Please reduce your prompt; or completion length..
WARNING:root:Reducing target length to 0, Retrying...

**Comment by wccccp** [comment]
**python generate_instruction.py generate_instruction_following_data**  运行此命令出现上面结果

**Comment by bestpredicts** [comment]
请仔细阅读代码。
