### ISSUE TITLE
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).

### ISSUE THREAD

**Issue by wccccp** [LianjiaTech/BELLE#55]
ARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).                                | 0/1 [00:00<?, ?it/s]
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...

**Comment by wccccp** [comment]
python generate_instruction.py generate_instruction_following_data \
    --api=chat --model_name=gpt-3.5-turbo  运行的此命令会出现这种结果

**Comment by bestpredicts** [comment]
高频请求被open ai限制。可以看看代理是否美国代理。
