### ISSUE TITLE
如何训练vl模型

### ISSUE THREAD

**Issue by lucasjinreal** [LianjiaTech/BELLE#554]
没有看到相关脚本

**Comment by wen2cheng** [comment]
可以参考Qwen-vl，如果有需要我们后面可以考虑开源个微调的示例

**Comment by lucasjinreal** [comment]
有需要，qwen那个代码太乱了

**Comment by yuyq96** [comment]
@wen2cheng ViT是从Qwen-VL继承的吗？没有训练的情况下，分辨率为什么从阶段一的224变成阶段二的448了？

**Comment by wen2cheng** [comment]
1、是的，vit除了有几个线性层维度不一样，其余权重是基于Qwen-vl的vit
2、分辨率的调整也是参考的llava，Qwen-vl。他们也都在预训练之后将分辨率提高。首先高分辨率肯定信息损失更少，但训练成本会相对高一些。也算是个折中吧
