### ISSUE TITLE
VL模型效果非常差

### ISSUE THREAD

**Issue by lucasjinreal** [LianjiaTech/BELLE#555]
几乎已经丧失了对话能力

![image](https://github.com/LianjiaTech/BELLE/assets/21303438/7a991ec3-c4bf-4a3c-a15d-21ff23c4d15a)

Human: https://static001.geekbang.org/infoq/34/34cf57f74c8062958ba37e777fb3a8c2.jpeg

**Comment by wen2cheng** [comment]
目前数据里面以开源数据为主，包含中文ocr的很少，所以表现会差一些，另外想强化对话能力，基于少量纯文本指令再微调一下就可以

**Comment by lucasjinreal** [comment]
很难说是差一些，感觉完全不可用。

为什么chat能力变这么多？

**Comment by wen2cheng** [comment]
目前在指令微调阶段还没混合纯文本指令数据进去，另外微调阶段的中文多模态指令数据相比占比还是少一些，可能会影响在中文对话能力上的表现

**Comment by wen2cheng** [comment]
不过我们在混合多模态指令数据和中文的纯文本指令数据继续微调之后就会正常很多

**Comment by wen2cheng** [comment]
我这边试了一下，在中文对话场景下对话能力确实下降厉害，英文的好一些，主要原因应该还是中英数据占比问题，后续会再优化一下模型

**Comment by lucasjinreal** [comment]
是从qwen的chat模型训练的，还是base模型？

**Comment by wen2cheng** [comment]
chat模型

**Comment by wen2cheng** [comment]
目前在mme上评测的感知能力可以到1620分，不过还是以具体体验为准

**Comment by lucasjinreal** [comment]
指的是，对话能力是否能保持，非图片
