### ISSUE TITLE
为什么语音识别的文字前面有特殊符号：� ，如何取消呢？？？

### ISSUE THREAD

**Issue by Nicksooooo** [LianjiaTech/BELLE#570]
� 深化学生工作体系建设持续提升学方学员系统构建五项三文锐意学生工作体系打造锐意新事业邀请学员教授行业专家企业高管等做讲座
Processing file 1 of 40: Data/zyl40/zyl40_29.wav
� 二强化过程培养提升研究生教育质量全年成熟博士研究生两名硕士研究生九十六名其中学术型三十三名专业学位六十三名
Processing file 2 of 40: Data/zyl40/zyl40_37.wav
� 关爱助力学生成长持续开展锐意孵化器品牌活动提升学生综合素质学员师生团队承担复活程独白团计划必将是三项

**Comment by shuaijiang** [comment]
1. 是所有的开头都有这个符号吗？
2. 转写是基于哪个框架，什么配置呢？
