### ISSUE TITLE
请问基于transformers的中文转写可以加标点吗？

### ISSUE THREAD

**Issue by v3ucn** [LianjiaTech/BELLE#571]
请问基于transformers的中文转写可以加标点吗？whisper可以通过prompt引导，咱们这个transformers可以加吗？

**Comment by shuaijiang** [comment]
目前基于AISHELL、WENETSPEECH等数据做的微调，弱化了标点能力。
解决方法：
1. 可以基于标点模型 对转写文本加标点。例如 https://modelscope.cn/models/damo/punc_ct-transformer_cn-en-common-vocab471067-large/summary
2. 微调带标点的数据，这块开源数据可能比较少。

**Comment by v3ucn** [comment]
感谢，受益匪浅
