### ISSUE TITLE
执行 python setup_cuda.py install 报错

### ISSUE THREAD

**Issue by liuyunrui123** [LianjiaTech/BELLE#58]
已经安装过Microsoft Visual C++ 14.0，报错如下图所示，怎么解决呢
![image](https://user-images.githubusercontent.com/57593875/228004366-a96ae510-3563-4464-9968-b3cb716d80dc.png)

**Comment by liuyunrui123** [comment]
想知道具体是环境哪里少了啥么，cuda也装了

**Comment by mabaochang** [comment]
> 想知道具体是环境哪里少了啥么，cuda也装了

不好意思，windows环境没有尝试过，不是很清楚具体的问题在哪

**Comment by liuyunrui123** [comment]
已经解决，重装了最新的vc++，还有cuda可以了
