### ISSUE TITLE
large-v3-zh经过ctranslate转换之后识别中文音频，但是结果确实英文

### ISSUE THREAD

**Issue by bingogo888** [LianjiaTech/BELLE#586]
![image](https://github.com/LianjiaTech/BELLE/assets/34439206/c3e13e9e-8a5d-4607-bdcf-82e09d6b9e12)
![image](https://github.com/LianjiaTech/BELLE/assets/34439206/a277a4d9-33d5-461c-9a4d-bb17334347d9)

large-v3-zh经过ctranslate转换之后识别中文音频，但是结果确实英文，不经过ctranslate转换没有问题。
这该怎么解决？

**Comment by shuaijiang** [comment]
可能是tokenizer.json有问题？可以使用这个 https://huggingface.co/BELLE-2/Belle-whisper-large-v3-zh/blob/main/tokenizer.json

**Comment by paulcx** [comment]
不仅仅是英文，而且结果非常差。包括https://huggingface.co/BELLE-2/Belle-whisper-large-v3-zh-punct

**Comment by shuaijiang** [comment]
怎么调用的模型呢
