### ISSUE TITLE
BELLE-LLAMA-7B-2M能不能提供量化版本

### ISSUE THREAD

**Issue by whynothackme** [LianjiaTech/BELLE#59]
期待能用llama.cpp直接跑起来，可以使用 https://github.com/ggerganov/llama.cpp/blob/master/convert-pth-to-ggml.py 来转换模型到ggml， 然后再使用quantize.py来生成量化版本，这样就可以在任意设备上跑起来了

**Comment by mabaochang** [comment]
gptq以及llama.cpp的量化，稍后都会上传到huggingface

**Comment by whynothackme** [comment]
好的，期待中, 使用CPU跑了一下BELLE-LLAMA-7B-2M模型，效果很OK

**Comment by dihin11** [comment]
> 好的，期待中, 使用CPU跑了一下BELLE-LLAMA-7B-2M模型，效果很OK

这个用cpu怎么跑起来？

**Comment by whynothackme** [comment]
我的代码如下：

```
from transformers import LlamaForCausalLM, AutoTokenizer
import torch

ckpt = r'D:\AI\datasets\BELLE-LLAMA-7B-2M'
device = torch.device('cpu')
model = LlamaForCausalLM.from_pretrained(ckpt, device_map='auto', low_cpu_mem_usage=True)
tokenizer = AutoTokenizer.from_pretrained(ckpt)
print("load finished.")


def ask(question):
    prompt = f"Human: {question} \n\nAssistant: "
    # prompt = "Human: 写一首中文歌曲，赞美大自然 \n\nAssistant: "
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)
    generate_ids = model.generate(
        input_ids, max_new_tokens=500, do_sample=True, top_k=30, top_p=0.85, temperature=0.5,
        repetition_penalty=1., eos_token_id=2, bos_token_id=1, pad_token_id=0
    )
    output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
    response = output[len(prompt):]
    return response
```

其中 `ckpt = r'D:\AI\datasets\BELLE-LLAMA-7B-2M'` 可以换成你自己下载的路径，或者换成原来的在线路径

需要注意的是下载BELLE-LLAMA-7B-2M后需要对比一下相关文件的SHA256，比如 [pytorch_model.bin](https://huggingface.co/BelleGroup/BELLE-LLAMA-7B-2M/blob/main/pytorch_model.bin) 为  90a7ef87138fd465d0badd76059382fd5d5e9fb586c656f0392ab605e2f7bdb7，用git可能会因为内存而爆掉导致文件出错，我是用页面直接下载的，大概二十分钟可以下载好.

**Comment by dihin11** [comment]
> 

谢谢，你的内存好大

**Comment by ddzz0210** [comment]
你出现这种报错了吗？

Traceback (most recent call last):
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\transformers\utils\versions.py", line 80, in require_version
    got_ver = pkg_resources.get_distribution(pkg).version
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\pkg_resources\__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\pkg_resources\__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\pkg_resources\__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'regex' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\gpt\BELLE-main\BELLE-main\test.py", line 1, in <module>
    from transformers import LlamaForCausalLM, AutoTokenizer
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\transformers\__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\transformers\dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\transformers\utils\versions.py", line 94, in require_version_core
    return require_version(requirement, hint)
  File "D:\LenovoSoftstore\python 3.10\lib\site-packages\transformers\utils\versions.py", line 82, in require_version
    raise pkg_resources.DistributionNotFound(requirement, ["this application", hint])
pkg_resources.DistributionNotFound: The 'regex!=2019.12.17' distribution was not found and is required by this application, 
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git master

**Comment by whynothackme** [comment]
@ddzz0210 建议用conda来跑，只需要torch及以下内容

```
pip install git+https://github.com/huggingface/transformers
pip install accelerate
pip install sentencepiece
```

**Comment by whynothackme** [comment]
我尝试了进行转换到llama.cpp需要的ggml格式，过程如下，没有GPU(导致了失败)

过程如下，创建路径 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\`

使用以下代码加载模块
```
from transformers import LlamaForCausalLM, AutoTokenizer

ckpt = 'BelleGroup/BELLE-LLAMA-7B-2M'
tokenizer = AutoTokenizer.from_pretrained(ckpt)
model = LlamaForCausalLM.from_pretrained(ckpt, device_map='auto', low_cpu_mem_usage=True)
```

生成`params.json` 到 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\params.json`

内容: `{"dim": 4096, "multiple_of": 256, "n_heads": 32, "n_layers": 32, "norm_eps": 1e-06, "vocab_size": -1}`

生成 `tokenizer` 到 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH`

代码: `tokenizer.save_pretrained(r"D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH")`

生成 `model` 到 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\`

代码: `torch.save(model.state_dict(), r"D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\consolidated.00.pth")`

转换：

`python .\convert-pth-to-ggml.py D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH/7B 1`

我转换挂在了CPU不支持的参数上面，有些参数只有GPU才行。

```
TypeError: can't convert meta device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

如果谁有GPU可以跑起来可以帮忙转换得到对应的bin文件，再使用 量化命令转换就可以了

**Comment by ddzz0210** [comment]
> @ddzz0210 建议用conda来跑，只需要torch及以下内容
> 
> ```
> pip install git+https://github.com/huggingface/transformers
> pip install accelerate
> pip install sentencepiece
> ```

LlamaForCausalLM还是会标红是为什么呢

**Comment by whynothackme** [comment]
> > @ddzz0210 建议用conda来跑，只需要torch及以下内容
> > ```
> > pip install git+https://github.com/huggingface/transformers
> > pip install accelerate
> > pip install sentencepiece
> > ```
> 
> LlamaForCausalLM还是会标红是为什么呢

标啥红？截个图看看

**Comment by ddzz0210** [comment]
![屏幕截图 2023-03-29 091247](https://user-images.githubusercontent.com/128711621/228401081-f3f7af2f-9553-4a13-aa20-bc1ab9d734b0.png)

**Comment by whynothackme** [comment]
> ![屏幕截图 2023-03-29 091247](https://user-images.githubusercontent.com/128711621/228401081-f3f7af2f-9553-4a13-aa20-bc1ab9d734b0.png)

不影响吧，只要能跑，如果还是有问题就用 `pip install git+https://github.com/huggingface/transformers` 试试

**Comment by erictamhk** [comment]
有直接在[alpaca.cpp](https://github.com/antimatter15/alpaca.cpp)跑的版本嗎?

**Comment by ddzz0210** [comment]
> 有直接在[alpaca.cpp](https://github.com/antimatter15/alpaca.cpp)跑的版本嗎?

暂时还没有，我这几天试一试，谢谢大佬

**Comment by whynothackme** [comment]
> > > ![屏幕截图 2023-03-29 091247](https://user-images.githubusercontent.com/128711621/228401081-f3f7af2f-9553-4a13-aa20-bc1ab9d734b0.png)
> > 
> > 
> > 不影响吧，只要能跑，如果还是有问题就用 `pip install git+https://github.com/huggingface/transformers` 试试
> 
> 会报错，但是pip install git+https://github.com/huggingface/transformers 也是会报错，就不知道为什么

可能和网络有关系，你可以先git clone https://github.com/huggingface/transformers,再 cd transformers && pip install -e .

**Comment by whynothackme** [comment]
> gptq以及llama.cpp的量化，稍后都会上传到huggingface

量化的跑起来报错：size mismatch for model.layers.0.self_attn.k_proj.qzeros: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).

看起来是形状不对，运行命令如下：

```
python D:\AI\GPTQ-for-LLaMa\llama_inference.py . --wbits 4 --load llama7b-4bit-128g.pt --text "this is llama"
```

请问，这个命令是啥样的可以加载起来。

**Comment by whynothackme** [comment]
以下命令可以加载起来：(完美)
`python D:\AI\GPTQ-for-LLaMa\llama_inference.py . --wbits 4 --groupsize 128 --load llama7b-4bit-128g.pt --text "写一首赞美冬天的诗句。"  --max_length 500 --top_p 30 --temperature 0.9`

需要修改 llama_inference.py 为以下
```
    text = f"Human: {args.text} \n\nAssistant: "
    input_ids = tokenizer.encode(text, return_tensors="pt").to(DEV)
```

结果如下：
```
白雪皑皑覆苍穹，幽冷漫透心灵感。
```

```
白飘花落，寒意中心涌。
冬眼里的世界静谧，唤醒内心的梦想。
```

```
冬风呼啸落叶殊，
银装素裹天地清。
孕育出年的草木，
皆是自然的力。
霜花闪烁月华清，
浓郁的冬季风情。
岁末走过繁华，
更为寂静之约。
```

运行于 `windows 10 x64`, `GTX2070 8G`, 消费级电脑 (占用显卡内存5.5G)。

**Comment by BigZSmallY** [comment]
> 我尝试了进行转换到llama.cpp需要的ggml格式，过程如下，没有GPU(导致了失败)
> 
> 过程如下，创建路径 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\`
> 
> 使用以下代码加载模块
> 
> ```
> from transformers import LlamaForCausalLM, AutoTokenizer
> 
> ckpt = 'BelleGroup/BELLE-LLAMA-7B-2M'
> tokenizer = AutoTokenizer.from_pretrained(ckpt)
> model = LlamaForCausalLM.from_pretrained(ckpt, device_map='auto', low_cpu_mem_usage=True)
> ```
> 
> 生成`params.json` 到 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\params.json`
> 
> 内容: `{"dim": 4096, "multiple_of": 256, "n_heads": 32, "n_layers": 32, "norm_eps": 1e-06, "vocab_size": -1}`
> 
> 生成 `tokenizer` 到 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH`
> 
> 代码: `tokenizer.save_pretrained(r"D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH")`
> 
> 生成 `model` 到 `D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\`
> 
> 代码: `torch.save(model.state_dict(), r"D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH\7B\consolidated.00.pth")`
> 
> 转换：
> 
> `python .\convert-pth-to-ggml.py D:\AI\datasets\BELLE-LLAMA-7B-2M-PTH/7B 1`
> 
> 我转换挂在了CPU不支持的参数上面，有些参数只有GPU才行。
> 
> ```
> TypeError: can't convert meta device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
> ```
> 
> 如果谁有GPU可以跑起来可以帮忙转换得到对应的bin文件，再使用 量化命令转换就可以了

./quantize  ./BELLE-LLAMA-7B-2M-PTH/7B/ggml-model-f16.bin ./BELLE-LLAMA-7B-2M-PTH/7B/ggml-model-q4_0.bin 2 会提示错误： 
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
请问这个有遇到吗？有解决办法吗？

**Comment by kandeng** [comment]
> @dihin11 我的代码如下：
> 
> ```
> from transformers import LlamaForCausalLM, AutoTokenizer
> import torch
> 
> ckpt = r'D:\AI\datasets\BELLE-LLAMA-7B-2M'
> device = torch.device('cpu')
> model = LlamaForCausalLM.from_pretrained(ckpt, device_map='auto', low_cpu_mem_usage=True)
> tokenizer = AutoTokenizer.from_pretrained(ckpt)
> print("load finished.")
> 
> 
> def ask(question):
>     prompt = f"Human: {question} \n\nAssistant: "
>     # prompt = "Human: 写一首中文歌曲，赞美大自然 \n\nAssistant: "
>     input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)
>     generate_ids = model.generate(
>         input_ids, max_new_tokens=500, do_sample=True, top_k=30, top_p=0.85, temperature=0.5,
>         repetition_penalty=1., eos_token_id=2, bos_token_id=1, pad_token_id=0
>     )
>     output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
>     response = output[len(prompt):]
>     return response
> ```
> 
> 其中 `ckpt = r'D:\AI\datasets\BELLE-LLAMA-7B-2M'` 可以换成你自己下载的路径，或者换成原来的在线路径
> 
> 需要注意的是下载BELLE-LLAMA-7B-2M后需要对比一下相关文件的SHA256，比如 [pytorch_model.bin](https://huggingface.co/BelleGroup/BELLE-LLAMA-7B-2M/blob/main/pytorch_model.bin) 为 90a7ef87138fd465d0badd76059382fd5d5e9fb586c656f0392ab605e2f7bdb7，用git可能会因为内存而爆掉导致文件出错，我是用页面直接下载的，大概二十分钟可以下载好.
> 
> 运行起来大概占用内存在29GB左右, 模型推理非常慢

我复制粘贴您的程序，在程序末尾加了以下两行代码，然后运行，报错。会是什么原因呢？

加了两行代码：
response = ask("写一首中文歌曲，赞美大自然")
print(f" >> Response: \n'{response}' \n ")

报错信息：

$ python testrun_chatllama7b_2.py
load finished.
/home/mist/transformers-main/src/transformers/generation/utils.py:1405: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/mist/ChatLlama7b-medical/testrun_chatllama7b_2.py", line 23, in <module>
    response = ask("写一首中文歌曲，赞美大自然")
  File "/home/mist/ChatLlama7b-medical/testrun_chatllama7b_2.py", line 15, in ask
    generate_ids = model.generate(
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/mist/transformers-main/src/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/mist/transformers-main/src/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mistgpu/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/mist/transformers-main/src/transformers/models/llama/modeling_llama.py", line 700, in forward
    logits = self.lm_head(hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mistgpu/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/mistgpu/site-packages/accelerate/hooks.py", line 280, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "/mistgpu/site-packages/accelerate/utils/modeling.py", line 149, in set_module_tensor_to_device
    new_value = value.to(device)
RuntimeError: CUDA out of memory. Tried to allocate 500.00 MiB (GPU 0; 23.70 GiB total capacity; 21.82 GiB already allocated; 186.56 MiB free; 22.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by kandeng** [comment]
> 显存爆了，建议用量化的模型，改一下（ckpt = r'D:\AI\datasets\BELLE-LLAMA-7B-2M'）地址即可

想到一起去了，我打算今天尝试一下，多谢多谢
