### ISSUE TITLE
使用colab还是会这样 WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).

### ISSUE THREAD

**Issue by wccccp** [LianjiaTech/BELLE#60]
Loaded 175 human-written seed instructions
  0%|          | 0/1 [00:00<?, ?it/s]WARNING:root:Chat API only supports batch size = 1, overriding requested batch size of 1 .

prompt_batches:   0%|          | 0/1 [00:00<?, ?it/s]WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
WARNING:root:OpenAIError: Invalid URL (POST /v1/chat/completions).
WARNING:root:Hit request rate limit; retrying...
prompt_batches:   0%|          | 0/1 [00:06<?, ?it/s]
![Uploading image.png…]()

**Comment by bestpredicts** [comment]
如果使用colab的话，不建议使用代理。并且验证api的可用性。
