### ISSUE TITLE
考虑提供13B甚至65B的中文训练版本么？

### ISSUE THREAD

**Issue by ldfandian** [LianjiaTech/BELLE#63]
7B的效果总体上还是比较弱吧~

**Comment by tjadamlee** [comment]
in plan

**Comment by ldfandian** [comment]
> in plan

nice~ looking forward to it~

**Comment by LeeVinteuil** [comment]
great, looking forward to it

**Comment by tjadamlee** [comment]
> > in plan
> 
> nice~ looking forward to it~ do you have any expected time to share?

maybe this week
