### ISSUE TITLE
bloom.py

### ISSUE THREAD

**Issue by LiuChen19960902** [LianjiaTech/BELLE#71]
想请教一下大神。
如果在我理解正确的情况下：
gptq/bloom.py 应该是模型量化的脚本，那么（1）dataset参数的作用是什么呀，如果我先用中文微调了bloom，这里的dataset应该改成belle.train.json嘛。
想请教一下大神关于上面的这个问题。谢谢了

**Comment by bestpredicts** [comment]
不需要改dataset。

**Comment by LiuChen19960902** [comment]
> 不需要改dataset。

get，谢谢了
