### ISSUE TITLE
论文没有比较base model与微调后的模型的能力比较

### ISSUE THREAD

**Issue by EnHuiPug** [LianjiaTech/BELLE#72]
论文里面只有四个不同规模的指令集微调后在各个任务的评测比较。
让我觉得奇怪的点事为什么不加入没有微调的模型一起进行比较，这样一方面可以看出模型进行指令微调后有多大的提升。二是可以比较一下像翻译这类微调不变或者变差的任务在原模型是否能力更强还是参数量限制了上限。

**Comment by tjadamlee** [comment]
非常好的建议，论文主要关注instruct数据集对instruct learning的效果影响，虽然结论还比较straight forward
