### ISSUE TITLE
To fine-tune how much gpu is required for the BELLE-7B-2M model, I am now fine-tuning the error memory overflow reported on the a100

### ISSUE THREAD

**Issue by Amy234543** [LianjiaTech/BELLE#79]
To fine-tune how much gpu is required for the BELLE-7B-2M model, I am now fine-tuning the error memory overflow reported on the a100

**Comment by weberrr** [comment]
share your code

**Comment by Amy234543** [comment]
![image](https://user-images.githubusercontent.com/107381937/229062316-ee91fb9e-9f06-4155-abda-d4b8f5e062da.png)
@weberrr

**Comment by Amy234543** [comment]
A100 80G显存够微调 BELLE-7B-2M非量化的模型吗？量化版的模型微调后不能正确回答@weberrr

**Comment by whywhy258** [comment]
8卡16g能否train动BELLE-7B-2M模型？

**Comment by xianghuisun** [comment]
> 8卡16g能否train动BELLE-7B-2M模型？

可以尝试deepspeed采用offload cpu的配置，不然16g的显存是不够的

**Comment by whywhy258** [comment]
> > 8卡16g能否train动BELLE-7B-2M模型？
> 
> 可以尝试deepspeed采用offload cpu的配置，不然16g的显存是不够的

你好，请问我用lora的方式train起来了 但是loss到第二步就是0了，这是为啥呢
