### ISSUE TITLE
为什么BLOOMZ-7B1-mt模型只有14.1G，BELLE训练出来的模型却有28.3G？

### ISSUE THREAD

**Issue by liguodongiot** [LianjiaTech/BELLE#80]

**Comment by D1026** [comment]
@liguodongiot  The bigscience team saved all bloom model by " mode.half()"

**Comment by tjadamlee** [comment]
we are also considering re-upload those models by "model.half()", thanks for your advise.

**Comment by LangDaoAI** [comment]
@tjadamlee 该问题建议重新open， 而且size大小对于显存的压力很重要， 还请team考虑一下，谢谢！

**Comment by xxllp** [comment]
是不是多了某些东西

**Comment by zhangyanbo2007** [comment]
我也发现这个问题
