### ISSUE TITLE
为什么调整了训练的数据格式？

### ISSUE THREAD

**Issue by rayguo01** [LianjiaTech/BELLE#81]
为了方便模型训练，huggingface开源数据将原始生成文件中的"instruction"、"input"字段合并成"input"字段。
与alpaca相比，需要调整模型训练的代码么？这样做有什么好处么？

**Comment by shenyichen** [comment]
我也想咨询，我在下游再通过LoRA在领域数据微调，发现效果并不好，是不是因为输入输出格式的原因？

**Comment by weberrr** [comment]
> 我也想咨询，我在下游再通过LoRA在领域数据微调，发现效果并不好，是不是因为输入输出格式的原因？

可以分享下fine-tune代码吗

**Comment by tjadamlee** [comment]
> 为了方便模型训练，huggingface开源数据将原始生成文件中的"instruction"、"input"字段合并成"input"字段。 与alpaca相比，需要调整模型训练的代码么？这样做有什么好处么？

本质上没有差别
