### ISSUE TITLE
目前gpt4数学还比较差

### ISSUE THREAD

**Issue by zhangbo2008** [LianjiaTech/BELLE#82]
建议finetune一个数学版本. test做高考数学题试试

**Comment by zhangbo2008** [comment]
你们7b模型为什么27个G大小. 我内存都放不下.

**Comment by tjadamlee** [comment]
> 建议finetune一个数学版本. test做高考数学题试试

good point

**Comment by tjadamlee** [comment]
开放了一个数学集合，希望对大家有帮助
