### ISSUE TITLE
基于LLama的版本belle的协议还是apache 2.0吗？似乎与LLama的CC-BY-NC 4.0不兼容啊？

### ISSUE THREAD

**Issue by Trista0823** [LianjiaTech/BELLE#90]
有问llama单独要过授权吗？

**Comment by tjadamlee** [comment]
目前的apache 2.0只是对于代码的协议，模型部分是基于https://huggingface.co/decapoda-research，其中模型部分license也是继承https://huggingface.co/decapoda-research相关licences。
请注意，目前不能保证其是原版的LLaMA模型，也不能保证调优后的模型和LLaMA原版模型之间的关系。
目前仅供学习交流。请严遵守LLaMA的使用限制。
强烈建议大家基于训练脚本和开放数据调优模型。
