### ISSUE TITLE
Request for docker enviroment

### ISSUE THREAD

**Issue by JomeiLiu** [LianjiaTech/BELLE#96]
Thanks for your wok.
Would you mind providing the docker enviroment?
Cause my development was restricted, If using the docker, it will be easier to reproduce your work.

**Comment by xianghuisun** [comment]
Sorry for replying so late. We will provide a Docker environment within a week

**Comment by xianghuisun** [comment]
> Thanks for your wok. Would you mind providing the docker enviroment? Cause my development was restricted, If using the docker, it will be easier to reproduce your work.

Sorry for replying so late. We will provide a Docker environment within a week and notify you in time.

**Comment by xianghuisun** [comment]
https://github.com/LianjiaTech/BELLE/tree/main/train#11-docker%E9%95%9C%E5%83%8F
