### ISSUE TITLE
中文的推理能力

### ISSUE THREAD

**Issue by solojoe** [LianjiaTech/BELLE#97]
请问你们有尝试过中文文档阅读的推理和理解么，又或者有相关的数据集训练计划不
我尝试了现有的一些数据集，在推理和理解方面的能力都不太好

**Comment by bestpredicts** [comment]
你好，可以说一下目前在哪些数据集上面效果比较差嘛？感谢你的反馈

**Comment by solojoe** [comment]
> 你好，可以说一下目前在哪些数据集上面效果比较差嘛？感谢你的反馈

比如：张三在2018年9月12日被拘留，于同年10月12日被抓捕，那么张三被抓捕的时间是？正确答案应该是2018年10月12日

类似的前后语义推理，偶尔能回答和提取，如果语句较长一点就会回答一些不相关的
所以想咨询一下，是不是在做这些推理都比较困难，还是如果尝试用更多的数据集做lora会有比较好的效果

**Comment by tjadamlee** [comment]
提升close qa能力是一个很有意思的话题，我们感觉这个能力对于7b模型可能还是有一点挑战。lora相比finetune来说，相比还是会差一点。
现阶段的7b-2m等模型都没有针对close qa专门优化过，只是参考alpaca的方法生产的相对geneneral的data训练的模型。
