### ISSUE TITLE
请问在两张3090上推理时显存溢出，请问可以使用nn.DataParallel分布式推理吗？具体怎么操作呢？谢谢！

### ISSUE THREAD

**Issue by lcneyc** [LianjiaTech/BELLE#98]
`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 23.70 GiB total capacity; 22.02 GiB already allocated; 24.56 MiB free; 22.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
按照如下代码也无法实现，仍然显存溢出：
device_ids = [0,1]
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")
model_path = "" # You can modify the path for storing the local model
model =  AutoModelForCausalLM.from_pretrained(model_path)
model = nn.DataParallel(model,device_ids = device_ids).cuda()
tokenizer = AutoTokenizer.from_pretrained(model_path)

**Comment by ZhonghaoWang** [comment]
只是推理的话，试试载入模型的时候加上load_in_8bit=True
